# -*- coding: utf-8 -*-
"""Base de hechos por sector, lote 6: escrito contra los huecos del Top 3.

A diferencia de los lotes 4 y 5, estos cuatro sectores se han elegido mirando el
SERP real, no solo el inventario. Dos motivos:

1. informes/clusters_cruzados.txt se queda corto. El inventario de carrito5.com
   es un suelo, asi que hay colisiones entre dominios que el informe no ve pero
   Google si: lavanderia, merceria y padel salen con los dos dominios en la
   misma pagina de resultados y ninguna de las tres esta en el informe.
2. El hueco solo se ve en el SERP. Para acuarios y para moda flamenca no existe
   ninguna pagina especifica en el Top: los resultados caen a "tienda de
   mascotas" y a "tienda de ropa". Para peluqueria canina todos los
   competidores hablan de agenda y de reservas, y ninguno del mostrador.

De ahi que cada pagina ataque lo que los demas no cubren: la merma de animal
vivo, el bono prepagado, el traje que no se repone y la curva de tallas que las
marcas sirven mal.
"""

SECTORES_6 = {

# ================================================================= ACUARIOS
"negocio_acuarios.asp": dict(
  nombre="Tiendas de acuarios, peces y terrarios",
  crumb="Acuariofilia",
  icono="fa-fish",
  title="Software TPV para Tiendas de Acuarios y Peces",
  desc="TPV para acuariofilia: baja por mortalidad con su motivo, recuento por acuario, garantía de aclimatación y mantenimientos a empresas cobrados a fin de mes.",
  kw="tpv tienda acuarios, software acuariofilia, programa tpv peces, tpv tienda animales vivos, control merma tienda acuarios",
  h1='Software TPV para Tiendas de Acuarios. <span>Tu stock está nadando, y una parte se muere.</span>',
  sub='En acuariofilia el inventario no está en una estantería: está repartido en cuarenta urnas y respira. Ningún programa de tienda de mascotas contempla que el género se muera solo, y aquí es el coste que decide el año.',
  bloques=[
    ("La mortalidad es merma, y la merma sin medir se paga entera",
     ["Llegan cincuenta neones y a la semana quedan cuarenta y cuatro. Esos seis son el coste real del animal vivo, y su cifra separa a la tienda que gana dinero de la que cree que lo gana.",
      "Si las bajas se corrigen ajustando el stock a mano, el dato desaparece. Dado de alta como baja con motivo, en cambio, al cabo de un trimestre sabes qué proveedor te sirve peces que aguantan y cuál no, que es la decisión de compra más rentable de este sector."],
     ["<strong>Baja de stock con motivo</strong>: mortalidad, rotura, aclimatación o devolución.",
      "<strong>Porcentaje de merma por lote y por proveedor</strong>, que es lo que permite comparar.",
      "<strong>Coste real por unidad vendida</strong> incluyendo lo que se murió por el camino.",
      "<strong>Merma por especie</strong>, porque un disco y un guppy no se comportan igual."]),
    ("El recuento no se hace con un lector, se hace urna por urna",
     ["Los artículos secos tienen código de barras y se inventarían en una tarde. El pez no. El recuento del animal vivo se hace mirando el acuario, y por eso conviene que el programa sepa en qué urna vive cada referencia.",
      "Con la ubicación en la ficha, el inventario deja de ser una lista alfabética imposible y pasa a ser un recorrido por la tienda, acuario por acuario, que es como se hace de verdad."],
     ["<strong>Ubicación por urna</strong> en la ficha del artículo vivo, con su número de acuario.",
      "<strong>Recuento parcial por zona</strong>, sin cerrar la tienda ni parar la venta.",
      "<strong>Lector de código de barras para el género seco</strong>: acuarios, filtros, alimento y sustrato.",
      "<strong>Teclas rápidas por precio</strong> para el pez que se cobra por unidad y no lleva etiqueta."]),
    ("La garantía de aclimatación y el cliente que vuelve con la bolsa",
     ["Casi toda tienda seria da un plazo de garantía sobre el pez, normalmente de horas o de pocos días, a veces contra una muestra de agua. Cuando el cliente vuelve, hay que localizar la venta y decidir: reposición, vale o nada.",
      "Sin la venta localizable eso se resuelve de memoria y siempre a favor del que más protesta. Con el ticket delante se resuelve igual para todos, que además es lo que sostiene la reputación de la tienda."],
     ["<strong>Venta localizable por cliente y fecha</strong> dentro del plazo de garantía.",
      "<strong>Vale con número e importe</strong> en lugar de devolver efectivo.",
      "<strong>Registro de la reposición</strong> como baja con su motivo, para que no falsee la merma.",
      "<strong>Nota en la ficha del cliente</strong> con su montaje y sus parámetros, para no repetir la conversación."]),
    ("Mantenimientos, empresas y lo que hay que consultar antes de vender",
     ["La otra mitad del negocio son los mantenimientos: el acuario de la clínica dental, el del restaurante, el de la oficina. Es una cuota mensual, un desplazamiento y un consumo de material, y se cobra a fin de mes con factura, no con ticket. Con cuenta de cliente y factura agrupada eso deja de llevarse en una libreta.",
      "Y una advertencia que conviene tener presente: hay especies cuya tenencia y comercio están restringidos o requieren documentación, y el coral y algunas especies llevan su propio régimen. Antes de dar de alta género de ese tipo, contrasta la normativa aplicable con tu proveedor y con tu asesor. El programa te guarda la documentación asociada a la ficha, pero no decide qué se puede vender."]),
  ],
  faqs=[
    ("¿Cómo se lleva la mortalidad de los peces en el TPV?",
     "Como una baja de stock con motivo, no como un ajuste de inventario. Cada baja registra la especie, la cantidad, el lote y el motivo, de forma que al cabo de unos meses tienes el porcentaje de merma por proveedor y por especie, y el coste real de cada unidad vendida."),
    ("¿Puedo saber qué proveedor me sirve peces que aguantan mejor?",
     "Sí, comparando el porcentaje de merma por lote y por proveedor. Es el dato que no aparece si las bajas se corrigen ajustando el stock a mano, y suele ser la decisión de compra más rentable de una tienda de acuariofilia."),
    ("¿Se puede inventariar sin cerrar la tienda?",
     "Sí, con recuento parcial por zona. El género seco se cuenta con el lector de código de barras y el vivo se recorre acuario por acuario, apoyándose en la ubicación por urna que lleva cada ficha."),
    ("Un cliente vuelve con un pez muerto dentro del plazo. ¿Puedo comprobar la venta?",
     "Sí, localizándola por cliente o por fecha. Con el ticket delante decides reposición o vale con el mismo criterio para todos, y la reposición se registra como baja con su motivo para que no falsee la cifra de merma."),
    ("Llevo mantenimientos de acuarios en empresas. ¿Se pueden facturar a fin de mes?",
     "Sí, con cuenta de cliente. Cada visita se documenta como albarán con el material consumido y el desplazamiento, y a fin de mes se emite una factura que agrupa todos los albaranes de ese cliente, con su tarifa propia."),
    ("¿Cuándo tengo que estar adaptado a VeriFactu?",
     "El calendario vigente tras el Real Decreto-ley 15/2025 obliga a las sociedades desde el 1 de enero de 2027 y a los autónomos desde el 1 de julio de 2027; durante 2026 la adaptación es voluntaria. Caja 5 se compra una vez y no lleva cuota mensual obligatoria, así que adaptarte no te mete en una suscripción. Esto es información general: tu caso concreto lo confirma tu asesor."),
  ],
  rel=[("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Cuentas de cliente y cobro a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
       ("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("TPV para tiendas de mascotas y piensos","/negocio_petshop.asp"),
       ("Software TPV y VeriFactu","/verifactu-tpv.asp")]),

# ======================================================== PELUQUERIA CANINA
"negocio_peluqueria_canina.asp": dict(
  nombre="Peluquerías caninas con tienda de accesorios",
  crumb="Peluquería canina",
  icono="fa-dog",
  title="TPV para Peluquería Canina: caja, bonos y tienda",
  desc="TPV para peluquería canina: servicio y producto en el mismo ticket, bonos de sesiones con saldo vivo, tarifa por raza y tamaño, y arqueo Z separando ambos.",
  kw="tpv peluqueria canina, software peluqueria perros, programa bonos peluqueria canina, tpv estetica canina, caja peluqueria mascotas",
  h1='Software TPV para Peluquerías Caninas. <span>La agenda la lleva casi todo el mundo. La caja, casi nadie.</span>',
  sub='Los programas del sector se venden por su agenda: citas, recordatorios, ficha del animal. Todos paran donde empieza el mostrador, que es donde se cobra el baño, el pienso y el collar en el mismo ticket.',
  bloques=[
    ("Servicio y producto en un solo ticket, y en un solo arqueo",
     ["La clienta recoge a su perro, paga el corte y se lleva un champú y una golosina. Eso es una venta con dos naturalezas: un servicio que consume tiempo y un producto que sale del stock.",
      "Con una agenda que no cobra y una caja que no conoce las citas acabas tecleando dos veces y cuadrando a mano. Y al cierre del día no sabes cuánto ha entrado por servicio y cuánto por tienda, que es la información con la que se decide si merece la pena tener lineal."],
     ["<strong>Servicios y artículos en la misma línea de venta</strong>, con un único cobro.",
      "<strong>Arqueo Z al cierre</strong> con el desglose entre servicio y producto, y por forma de pago.",
      "<strong>Teclas rápidas por servicio</strong>: baño, corte de tijera, deslanado, corte de uñas, glándulas.",
      "<strong>Lector de código de barras</strong> para el pienso y el accesorio, que sí lo traen."]),
    ("Los bonos: dinero cobrado por un trabajo que aún no has hecho",
     ["El bono de cinco baños es la operación más rentable del sector y la peor controlada. La clienta paga hoy, y tú te quedas con una obligación de cinco servicios repartidos en medio año. Sobre un papel grapado en la ficha, o en la cabeza del peluquero.",
      "El programa debe llevar el saldo vivo: cuántas sesiones quedan por cliente, cuánto dinero representa el total de bonos sin consumir y cuáles caducan. Cómo se refleje eso en tu contabilidad, consúltalo con tu asesor: es dinero recibido a cuenta de un servicio pendiente."],
     ["<strong>Bono de sesiones con saldo vivo</strong> descontado en cada visita.",
      "<strong>Total de bonos sin consumir</strong>, en sesiones y en euros.",
      "<strong>Caducidad por bono</strong> y aviso cuando se acerca.",
      "<strong>Histórico de consumo</strong> por cliente, para saber quién compra bono y no vuelve."]),
    ("La tarifa es una tabla de raza por tamaño, no un precio suelto",
     ["Un corte de un yorkshire y uno de un golden no cuestan lo mismo ni tardan lo mismo. El precio sale de cruzar raza o tamaño con el servicio, y encima hay recargos reales: nudos, perro que no se deja, pelo muy sucio.",
      "Cuando eso no está en el programa, el precio lo pone cada peluquero de memoria y dos clientas del mismo barrio pagan distinto por lo mismo, que es una conversación que nadie quiere tener."],
     ["<strong>Tarifa cruzada</strong> de servicio por raza o por tramo de peso.",
      "<strong>Recargos como línea propia</strong>: desenredado, perro difícil, urgencia.",
      "<strong>Duración estimada por combinación</strong>, para que la agenda cuadre con la realidad.",
      "<strong>Producto consumido en el servicio</strong> descontado del stock aunque no se facture aparte."]),
    ("La ficha del animal es lo que hace que vuelvan",
     ["Raza, corte que se le hizo la última vez, número de peine, alergias, si se deja las uñas y si muerde. Eso es lo que convierte la segunda visita en un trabajo de veinte minutos menos y en una clienta que no se cambia de peluquería.",
      "Junto a eso, el listado de quién lleva meses sin aparecer es la herramienta comercial más barata que tiene el negocio: son clientes que ya te conocen y que se han ido por inercia, no por enfado."]),
  ],
  faqs=[
    ("¿Puedo cobrar el corte y un producto de la tienda en el mismo ticket?",
     "Sí. Servicios y artículos conviven en la misma venta con un solo cobro, y el arqueo Z del cierre te los desglosa por separado, además de por forma de pago, para saber cuánto entra por servicio y cuánto por tienda."),
    ("¿Cómo se controlan los bonos de varias sesiones?",
     "El bono se vende como saldo de sesiones asociado al cliente y se descuenta en cada visita. En cualquier momento ves cuántas sesiones quedan vivas por cliente y cuánto dinero suman los bonos sin consumir, además de los que están próximos a caducar."),
    ("¿Puedo tener precios distintos según la raza o el tamaño del perro?",
     "Sí, con una tarifa cruzada de servicio por raza o por tramo de peso, más los recargos habituales como desenredado o perro difícil, cada uno como línea propia del ticket."),
    ("El champú y la colonia que gasto en el baño, ¿salen del stock?",
     "Sí, si el servicio lleva su escandallo. Al cobrar el baño se descuenta el producto consumido aunque no se facture aparte, que es lo que hace que el inventario de la tienda cuadre a fin de mes."),
    ("¿Guarda el corte que se le hizo al perro la última vez?",
     "Sí, en la ficha del animal: raza, corte anterior, número de peine, alergias y carácter, junto con su histórico de visitas. Es lo que hace que la segunda cita sea más rápida y lo que evita repetir la conversación entera."),
    ("¿Tengo que pagar una cuota mensual para cumplir con VeriFactu?",
     "No necesariamente. La obligación es del sistema con el que emites tus facturas, y hay programas en propiedad de pago único como Caja 5 además de los de suscripción. El calendario vigente tras el Real Decreto-ley 15/2025 empieza el 1 de enero de 2027 para sociedades y el 1 de julio de 2027 para autónomos, con 2026 como año de adaptación voluntaria. Confirma con tu asesor lo que te aplica."),
  ],
  rel=[("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Vales y tarjetas regalo en el TPV","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Controlar la caja con varios empleados","/controlar-empleados-tpv.asp"),
       ("TPV para tiendas de mascotas y piensos","/negocio_petshop.asp"),
       ("Cuentas de cliente y cobro a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("Software TPV y VeriFactu","/verifactu-tpv.asp")]),

# ================================================================ FLAMENCA
"negocio_flamenca.asp": dict(
  nombre="Tiendas de moda flamenca y trajes de gitana",
  crumb="Moda flamenca",
  icono="fa-guitar",
  title="Software TPV para Tiendas de Moda Flamenca",
  desc="TPV para moda flamenca: traje por encargo con pruebas, tejido por metros y volantes, complementos en conjunto y venta a academias de baile a crédito.",
  kw="tpv moda flamenca, software tienda trajes flamenca, programa tienda traje gitana, tpv tienda feria, gestion tienda flamenca",
  h1='Software TPV para Moda Flamenca. <span>Un traje por encargo, una fecha de feria y ninguna reposición.</span>',
  sub='Busca «software TPV moda flamenca» y no hay nada: el buscador te devuelve programas de tienda de ropa hablando de tallas y colores. Un traje de gitana no tiene talla y color, tiene volantes, tejido, prueba y fecha.',
  bloques=[
    ("Lo que se vende no se repone, y por eso el catálogo es otro",
     ["Un traje de flamenca se hace por encargo o se compra en serie muy corta. No hay matriz de talla por color que valga: hay un modelo, un tejido, un número de volantes, un color de temporada y una clienta con sus medidas.",
      "El programa que trata esto como una referencia con stock reponible falla el primer día. Lo que hace falta es una ficha de encargo con las medidas y las decisiones tomadas, y una pieza de serie corta gestionada como unidad."],
     ["<strong>Encargo con las medidas de la clienta</strong> y las decisiones del modelo.",
      "<strong>Tejido, número de volantes y color</strong> como atributos del encargo, no como nombre del artículo.",
      "<strong>Pieza de serie corta con stock uno</strong>, con su fotografía en la ficha.",
      "<strong>Tejido por metros</strong> para la tienda que además vende tela, con su consumo por traje."]),
    ("La feria es la fecha, y no se mueve",
     ["De noviembre a abril se concentra el trabajo entero, con la Feria de Abril marcando el límite y detrás las de Jerez, Córdoba y el Rocío. Todo lo que no esté terminado el día antes no vale para nada.",
      "El calendario de entregas ordenado por fecha de evento es la vista que hay que tener delante en marzo, junto con la agenda de pruebas. Un traje con dos pruebas pendientes y quince días por delante es un aviso, no un dato."],
     ["<strong>Encargos ordenados por fecha de feria</strong>, no por fecha de pedido.",
      "<strong>Agenda de pruebas</strong> con lo que queda por ajustar en cada una.",
      "<strong>Estado del encargo</strong>: tomado, cortado, en taller, probado, terminado y entregado.",
      "<strong>Aviso de encargos con la fecha encima</strong> y trabajo sin cerrar."]),
    ("La clienta pregunta si alguien más lo lleva",
     ["En este oficio la pregunta se repite cada temporada: si ese modelo se lo ha llevado alguien de su peña, de su caseta o de su grupo de baile. Vender el mismo traje dos veces dentro del mismo círculo es el error que se paga con la clienta y con las que vienen con ella.",
      "Guardar en el encargo la peña, la caseta o la academia permite comprobarlo antes de comprometer el modelo, igual que se hace con los colegios en los trajes de comunión."],
     ["<strong>Peña, caseta o academia</strong> guardada en la ficha del encargo.",
      "<strong>Consulta de modelo comprometido</strong> dentro del mismo círculo antes de cerrar.",
      "<strong>Histórico de trajes por clienta</strong>, que vuelve cada año y no quiere repetirse a sí misma.",
      "<strong>Reserva del modelo</strong> retirada del disponible mientras se decide."]),
    ("Complementos, academias y el dinero que entra en cuatro veces",
     ["El traje se lleva con mantoncillo, flor, peineta, pendientes, zapato y a veces mantón, y casi siempre se venden en conjunto. Montado como pack con su escandallo, al venderlo baja el stock de cada pieza y sabes qué margen deja el conjunto de verdad.",
      "Y está el cliente profesional que casi nadie atiende bien: la academia de baile que viste a un cuadro entero, la compañía que prepara una gira, el grupo de sevillanas del ayuntamiento. Eso se sirve con albarán y se factura a fin de mes con su tarifa. Muchas tiendas alquilan además el traje de escenario, que sale con fianza y vuelve para la siguiente actuación, así que la misma pieza rota varias veces al año y conviene saber cuánto ha rentado y cuánto ha costado limpiarla."]),
  ],
  faqs=[
    ("¿Sirve un TPV de tienda de ropa para una tienda de moda flamenca?",
     "Se queda corto. Un programa de moda organiza el catálogo por matriz de talla y color con reposición, y un traje de flamenca es un encargo con medidas, tejido, número de volantes y una fecha de feria. Hace falta ficha de encargo y agenda de pruebas, no solo stock por talla."),
    ("¿Puedo saber si ese modelo ya se lo lleva alguien de la misma peña?",
     "Sí, si el encargo guarda la peña, la caseta o la academia. Antes de comprometer un modelo se consulta dentro de ese círculo, que es la pregunta que hace la clienta cada temporada."),
    ("¿Cómo llevo las pruebas y las entregas antes de la Feria?",
     "Con los encargos ordenados por fecha de evento y no por fecha de pedido, más la agenda de pruebas. El programa avisa de los encargos que tienen la fecha encima y siguen con trabajo sin cerrar."),
    ("Visto a una academia de baile entera. ¿Puedo facturarle a fin de mes?",
     "Sí, con cuenta de cliente: se sirve con albarán y a fin de mes se emite una factura que agrupa todo el periodo, con la tarifa propia de esa academia y un límite de riesgo que avisa al superarse."),
    ("Alquilo trajes de escenario a academias. ¿Se puede controlar?",
     "Sí, con contrato de alquiler por unidad: qué traje ha salido, a quién, con qué fianza y en qué fechas. La disponibilidad por fechas evita comprometer la misma pieza dos veces, y el coste de limpieza imputado a cada ciclo te dice cuánto renta el traje al cabo del año."),
    ("Vendo también la tela por metros. ¿Cuadra el stock?",
     "Sí, dando de alta el tejido como venta por medida. Se descuentan los metros que consume cada traje, con lo que sabes qué tejidos rotan y cuánta tela se te va en cada modelo."),
  ],
  rel=[("TPV para tiendas de trajes de comunión","/negocio_comunion.asp"),
       ("TPV para sombrererías y tocados","/negocio_sombreros.asp"),
       ("Cuentas de cliente y cobro a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("TPV para tiendas de complementos","/negocio_complementos.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp")]),

# ========================================================== TALLAS GRANDES
"negocio_tallas_grandes.asp": dict(
  nombre="Tiendas de ropa de tallas grandes",
  crumb="Tallas grandes",
  icono="fa-shirt",
  title="Software TPV para Tiendas de Tallas Grandes",
  desc="TPV para tallas grandes: curva real vendida frente a la comprada, equivalencia de talla entre marcas, arreglos de taller y clienta fiel que viene de lejos.",
  kw="tpv tallas grandes, software tienda curvy, programa tpv moda tallas grandes, curva de tallas tienda ropa, tpv tienda ropa arreglos",
  h1='Software TPV para Tiendas de Tallas Grandes. <span>La matriz de talla y color la tiene cualquiera. La curva, no.</span>',
  sub='Todos los programas de moda venden lo mismo: talla por color y stock en tiempo real. Ninguno resuelve lo que de verdad duele aquí, que es una curva que las marcas sirven mal y un 48 que cambia de tamaño según la etiqueta.',
  bloques=[
    ("La curva que compras y la curva que vendes no son la misma",
     ["El proveedor te sirve el modelo en un surtido pensado para la media del mercado, y tu clientela no está en esa media: se concentra en un tramo estrecho que se agota primero mientras las puntas se quedan colgadas hasta las rebajas.",
      "Verlo por modelo no sirve. Hay que poner la curva comprada al lado de la vendida, talla a talla, porque esa comparación es la que te da argumentos para pedirle al proveedor un surtido distinto en lugar de aceptar el que trae."],
     ["<strong>Curva comprada frente a curva vendida</strong>, talla a talla y por modelo.",
      "<strong>Aviso de tallas centrales agotadas</strong>, que son las que sostienen el modelo.",
      "<strong>Rotación por talla</strong>, para ver qué punta de la curva se queda siempre.",
      "<strong>Reposición por talla</strong> en la propuesta de pedido, y no por modelo entero."]),
    ("El 48 de una marca es el 44 de otra",
     ["La variación de horma entre marcas es el problema diario del mostrador. La clienta que gasta un 46 en una firma necesita un 50 en otra, y si eso no está escrito se prueba tres veces cada vez que entra.",
      "Guardar en su ficha la talla que gasta por marca convierte una prueba de media hora en una recomendación de dos minutos, y es la razón por la que vuelve aquí y no compra en internet."],
     ["<strong>Talla por marca en la ficha de la clienta</strong>, no una talla única.",
      "<strong>Equivalencias entre marcas</strong> guardadas en el catálogo.",
      "<strong>Histórico de compras</strong> con lo que se llevó y lo que devolvió.",
      "<strong>Aviso cuando entra su marca</strong>, que en una clienta fiel es la venta más fácil."]),
    ("Casi todo pasa por el taller",
     ["El bajo, la sisa, meter de cintura. Aquí el arreglo forma parte de la venta en la mayoría de las prendas, y a menudo lo hace una modista externa que cobra aparte. Si se apalabra de viva voz, ni se cobra bien ni se sabe cuándo estará.",
      "Como línea de servicio dentro de la venta queda facturado, con su coste y su fecha, y al cabo del año sabes cuánto margen se te va en taller, que suele ser bastante más de lo que se piensa."],
     ["<strong>Arreglo como línea de servicio</strong> con precio, coste y fecha comprometida.",
      "<strong>Resguardo de la prenda</strong> con lo que hay que hacerle y cuándo se recoge.",
      "<strong>Modista externa</strong> con su coste imputado, para ver el margen real.",
      "<strong>Listado de arreglos pendientes</strong> ordenado por fecha de recogida."]),
    ("Una clienta que viene de lejos y compra mucho de una vez",
     ["En tallas grandes la clientela recorre kilómetros porque no tiene tienda cerca, viene menos veces y se lleva más en cada visita. Eso cambia el negocio entero: la ficha con su talla por marca, la reserva de una prenda hasta que pueda venir a probársela y el aviso cuando entra lo suyo valen aquí mucho más que en una tienda de paso.",
      "Y cuando parte de la venta se va a internet, el stock tiene que ser el mismo para las dos: reservar en tienda algo que la web acaba de vender es el fallo que peor sienta a una clienta que ha hecho ochenta kilómetros."]),
  ],
  faqs=[
    ("¿Puedo comparar la curva de tallas que compro con la que vendo?",
     "Sí, talla a talla y por modelo. Es la comparación que enseña qué tramo se agota siempre y qué punta se queda hasta las rebajas, y el argumento con el que se le pide al proveedor un surtido distinto."),
    ("Cada marca talla distinto. ¿Puedo guardar la talla de cada clienta por marca?",
     "Sí. La ficha admite una talla por marca en lugar de una talla única, junto con su histórico de compras y devoluciones. Es lo que convierte una prueba larga en una recomendación de dos minutos."),
    ("¿Cómo llevo los arreglos si los hace una modista externa?",
     "Como línea de servicio dentro de la venta, con su precio, el coste de la modista y la fecha comprometida, más un resguardo de la prenda. Tienes el listado de arreglos pendientes ordenado por fecha de recogida."),
    ("¿Puedo reservar una prenda para una clienta que vive lejos?",
     "Sí. La reserva retira la unidad del stock disponible y queda a su nombre con una fecha límite, de forma que no se vende por error mientras ella organiza el viaje."),
    ("Vendo también por internet. ¿Se puede llevar un solo stock?",
     "Sí, trabajando contra el mismo catálogo y el mismo stock para tienda y web. Es lo que evita comprometer en tienda una prenda que la web acaba de vender."),
    ("¿Me avisa cuando entra la marca que le gusta a una clienta?",
     "Puedes sacar el listado de clientas por marca y por talla a partir de su histórico, que es la base del aviso cuando llega el pedido. En una clientela fiel y poco frecuente es la venta más rentable que hay."),
  ],
  rel=[("Cómo hacer una devolución o cambio en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("TPV para tiendas de lencería y corsetería","/negocio_lenceria.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp")]),

}
