# -*- coding: utf-8 -*-
"""Base de hechos por sector, lote 4: las paginas de sector mas cortas del sitio.

Estas ocho existian ya en la web del cliente con 692-732 palabras y un texto
intercambiable entre ellas. Aqui se reescriben desde lo que cada oficio hace de
verdad en el mostrador: el compro oro lleva libro registro y compra a
particulares, la tienda de vinilos vende ejemplares unicos con estado, la de
skate monta completas a partir de componentes. El generador solo pone la
maqueta.

Ninguna de las ocho aparece en informes/clusters_cruzados.txt, o sea que no
compite con ninguna pagina de carrito5.com. Fue el criterio para elegirlas.
"""

SECTORES_4 = {

# ================================================================ SOUVENIRS
"negocio_souvenirs_tienda.asp": dict(
  nombre="Tiendas de souvenirs y regalo turístico",
  crumb="Souvenirs",
  icono="fa-gift",
  title="Software TPV para Tiendas de Souvenirs | Caja 5",
  desc="TPV para tiendas de souvenirs: lotes de importación repartidos en unidades, artículos sin código de barras, temporada alta y devolución del IVA al viajero.",
  kw="tpv souvenirs, software tienda souvenirs, tpv tienda regalos turista, programa tpv recuerdos, tpv tienda turistica",
  h1='Software TPV para Tiendas de Souvenirs. <span>Mucho ticket pequeño y una temporada que decide el año.</span>',
  sub='Una tienda de recuerdos hace en julio y agosto lo que otras hacen en seis meses, con artículos de dos euros que llegan en lotes de cien y casi ninguno trae código de barras impreso.',
  bloques=[
    ("Compras por lote y vendes por unidad",
     ["El importador no te sirve imanes: te sirve una caja de cien imanes surtidos. Lo que entra en el almacén es un bulto con una referencia de proveedor, y lo que sale por caja son unidades sueltas de doce modelos distintos.",
      "Si das de alta la caja como un artículo, el inventario te dirá que tienes 4 cajas cuando en realidad tienes 380 imanes repartidos. Y si das de alta los doce modelos a mano cada vez que llega un pedido, se te va la mañana."],
     ["<strong>Alta por lote con reparto.</strong> Recibes la caja y el programa sube el stock de los modelos que la componen, en la cantidad que traiga cada uno.",
      "<strong>Unidad de compra distinta de la de venta.</strong> Compras por caja, vendes por unidad, y el coste unitario sale solo.",
      "<strong>Referencia del importador en la ficha.</strong> Para volver a pedir sin tener que traducir tu código al suyo.",
      "<strong>Precio por escalado.</strong> Uno para la pieza suelta y otro para el pack de tres, que es como se llevan la mitad."]),
    ("Artículos sin código de barras, y una cola que no espera",
     ["El llavero de resina no trae EAN. El abanico pintado tampoco. En temporada alta tienes ocho personas delante del mostrador y un dependiente de refuerzo que empezó el lunes, así que el catálogo tiene que poder teclearse rápido o la venta se apunta mal.",
      "Lo que funciona en este oficio son los botones de venta directa por precio y familia. El artículo de 2,50 se cobra desde una tecla, no buscándolo en una lista de mil líneas."],
     ["<strong>Teclas rápidas por familia y precio.</strong> Imanes, llaveros, postales y abanicos a un toque.",
      "<strong>Etiqueta propia con código.</strong> Para lo que sí conviene controlar por unidad, como la cerámica o la camiseta por talla.",
      "<strong>Búsqueda por descripción parcial</strong> cuando el refuerzo de verano no se sabe el catálogo.",
      "<strong>Redondeo de precios al cambio</strong> para que el cajón no se llene de céntimos."]),
    ("La temporada manda, y hay que verla en números",
     ["El error caro de este sector es comprar en marzo mirando lo que se vendió el agosto anterior de memoria. Los modelos que funcionan cambian, y el stock que sobra en septiembre se queda dos años en la trastienda ocupando dinero.",
      "Con el histórico de ventas por modelo y por semana sabes qué pediste de más y qué se agotó el 10 de agosto, que es la información que de verdad te hace falta cuando el importador te pasa el catálogo nuevo."],
     ["<strong>Ventas por artículo y por semana</strong> comparando la temporada de este año con la anterior.",
      "<strong>Rotación y stock muerto</strong> para localizar lo que lleva dos veranos sin moverse.",
      "<strong>Control por punto de venta</strong> si tienes el quiosco del paseo además de la tienda.",
      "<strong>Cierre de temporada</strong> con liquidación y cambio de precios en masa por familia."]),
    ("El viajero extracomunitario y la devolución del IVA",
     ["Parte de tu clientela no reside en la Unión Europea y puede pedir la devolución del IVA de su compra. Para eso hace falta emitir la venta con los datos del viajero y su documento, no un ticket simple, y tramitarla por el sistema electrónico correspondiente.",
      "No todas las tiendas se acogen a esto, y la operativa concreta depende de a qué entidad colaboradora estés adherido. Lo que sí conviene es que el programa te deje emitir una factura completa con los datos del comprador en el momento, sin salir de la caja. Consulta con tu asesor los requisitos que te aplican."]),
  ],
  faqs=[
    ("Compro cajas surtidas de cien piezas. ¿Puedo controlar el stock por modelo?",
     "Sí. El lote se da de alta como una composición: la caja del proveedor contiene tantas unidades de cada modelo. Al recibir el pedido registras una caja y el programa sube el stock de cada modelo en la cantidad correspondiente, con su coste unitario repartido."),
    ("Casi nada de lo que vendo trae código de barras. ¿Me obliga a etiquetar todo?",
     "No. Lo habitual en souvenirs es trabajar con teclas rápidas por familia y precio para el artículo pequeño, y etiquetar solo lo que conviene controlar unidad a unidad, como la cerámica, el textil por talla o cualquier cosa que pase de cierto importe."),
    ("En agosto meto una persona de refuerzo. ¿Puedo saber lo que vende cada una?",
     "Sí. Cada dependiente entra con su usuario y todas las ventas quedan asociadas a quien las cobró. En el arqueo del día ves el desglose por persona, que es lo que evita discusiones cuando el cajón no cuadra."),
    ("¿Puedo emitir factura a un turista que pide la devolución del IVA?",
     "El programa emite factura completa con los datos del comprador desde la propia caja, que es el documento que necesitas. El trámite de la devolución en sí depende de la entidad colaboradora con la que trabajes y de la normativa aplicable, así que conviene revisarlo con tu asesor."),
    ("Tengo la tienda y un puesto en el paseo marítimo. ¿Se pueden llevar los dos?",
     "Sí, como dos puntos de venta con su stock y su caja. Ves las ventas juntas o por separado, y puedes mover mercancía de uno a otro dejando registro del traspaso."),
    ("¿Cómo sé qué modelos pedir para la temporada que viene?",
     "Con el informe de ventas por artículo comparado entre temporadas. Te dice qué se agotó pronto, qué se quedó en la estantería y cuánto stock muerto arrastras, que es lo que necesitas delante cuando el importador te enseña el catálogo nuevo."),
  ],
  rel=[("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Cambiar precios en masa","/cambiar-precios-masivamente-tpv.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("Controlar la caja con varios empleados","/controlar-empleados-tpv.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("TPV para tiendas de regalo y bisutería","/negocio_bisuteria.asp")]),

# ============================================================== COMPRO ORO
"negocio_compro_oro.asp": dict(
  nombre="Compro oro y joyería de ocasión",
  crumb="Compro oro",
  icono="fa-scale-balanced",
  title="TPV para Compro Oro: libro registro y peso | Caja 5",
  desc="Programa para compro oro: compra a particular con identificación, libro registro, peso y ley por gramo, plazo de conservación y venta de ocasión.",
  kw="tpv compro oro, programa compro oro, software compraventa oro, libro registro compro oro, tpv joyeria ocasion",
  h1='Software para Compro Oro. <span>Aquí la operación importante es la compra, no la venta.</span>',
  sub='Un compro oro registra cada día operaciones en las que el dinero sale del cajón, con un particular delante, un peso, una ley y un documento de identidad. Un TPV de tienda normal no contempla nada de eso.',
  bloques=[
    ("La compra a particular es una operación con forma propia",
     ["En una tienda al uso el flujo va del proveedor al cliente. Aquí entra un particular por la puerta con una pulsera, se pesa, se calcula a cuánto sale según la ley y se le paga. Esa operación necesita quedar documentada con el detalle de lo que se ha comprado y a quién.",
      "El programa tiene que emitir un documento de compra numerado, no un ticket de venta en negativo. Y tiene que guardar la ficha del vendedor particular, con su documento de identidad, porque esa información se conserva."],
     ["<strong>Documento de compra numerado</strong> con la descripción de la pieza, su peso y su ley.",
      "<strong>Ficha del vendedor</strong> con nombre, documento de identidad y fecha, asociada a cada operación.",
      "<strong>Fotografía de la pieza</strong> adjunta a la línea de compra, para poder identificarla después.",
      "<strong>Salida de caja registrada</strong> y cuadrada en el arqueo, que es donde se ve el efectivo que se ha pagado en el día."]),
    ("Peso, ley y cotización: el precio cambia cada mañana",
     ["El oro de 18 quilates no se paga igual que el de 14 ni que el de 9, y el precio por gramo se mueve a diario. Trabajar con un precio fijo escrito en un papel pegado al mostrador es la forma más rápida de comprar caro un mes entero sin enterarte.",
      "Lo práctico es tener tablas de precio por ley que se actualicen a la vez, con su margen ya aplicado, y que el cálculo salga de multiplicar los gramos que marca la balanza."],
     ["<strong>Tarifa por ley</strong>: 24, 22, 18, 14 y 9 quilates, plata y platino, cada una con su precio por gramo.",
      "<strong>Actualización de la tabla en un paso</strong> cuando cambia la cotización, sin tocar artículo por artículo.",
      "<strong>Balanza conectada</strong> para que el peso entre en la línea sin teclearlo.",
      "<strong>Descuento de soldaduras y piedras</strong> antes de calcular el neto a pagar."]),
    ("El libro registro y el plazo de conservación",
     ["La compraventa de objetos usados de metal precioso a particulares está sujeta a obligaciones de registro y de conservación de la pieza durante un plazo antes de poder transformarla o revenderla. El detalle exacto depende de la normativa estatal y de la de tu comunidad autónoma.",
      "Lo que puede hacer el programa es que ese registro no dependa de una libreta: numeración correlativa, datos del vendedor, descripción, peso, ley e importe, y un aviso cuando una pieza cumple el plazo y ya se puede fundir o poner a la venta. Cómo se presenta y ante quién, consúltalo con tu asesor o con la autoridad competente en tu zona."],
     ["<strong>Libro registro de operaciones</strong> correlativo y exportable.",
      "<strong>Estado de cada pieza</strong>: en plazo, disponible para venta, fundida o devuelta.",
      "<strong>Aviso de cumplimiento de plazo</strong> por operación.",
      "<strong>Histórico consultable por vendedor</strong>, por fecha y por número de operación."]),
    ("La otra mitad del negocio: vender la ocasión",
     ["Buena parte de los compro oro tienen escaparate de segunda mano, y ahí la pieza deja de ser gramos para pasar a ser un artículo único con su precio. Cada anillo es una unidad, no hay reposición y no vale gestionarlo como un catálogo con stock.",
      "Además, la venta de bienes usados adquiridos a particulares tiene su propio tratamiento en el IVA a través del régimen especial de bienes usados. Que el programa te separe esas ventas de las ordinarias te ahorra el trabajo de reconstruirlo después. El encaje concreto de tu actividad en ese régimen lo tiene que confirmar tu asesor."]),
  ],
  faqs=[
    ("¿Puedo registrar la compra a un particular, y no solo las ventas?",
     "Sí, y es la operación central del programa en este sector. Se emite un documento de compra numerado con la descripción de la pieza, su peso, su ley y el importe pagado, junto con los datos del vendedor y su documento de identidad. La salida de efectivo queda reflejada en el arqueo del día."),
    ("El precio del oro cambia cada día. ¿Tengo que cambiar todos los artículos?",
     "No. Se trabaja con una tarifa por ley, un precio por gramo para cada quilataje. Cuando la cotización se mueve actualizas la tabla y todas las compras posteriores calculan con el precio nuevo."),
    ("¿Se puede conectar la balanza para que el peso entre solo?",
     "Sí. El peso se toma de la balanza conectada y entra en la línea de compra, con lo que se evita el error de teclado, que en gramos de oro cuesta dinero real."),
    ("¿Lleva el libro registro de operaciones?",
     "El programa mantiene el registro correlativo de las compras con vendedor, fecha, descripción, peso, ley e importe, y lo exporta. Las obligaciones concretas de llevanza, presentación y plazo de conservación dependen de la normativa estatal y autonómica aplicable a tu establecimiento, así que revísalas con tu asesor."),
    ("¿Me avisa de cuándo puedo fundir o poner a la venta una pieza?",
     "Cada operación guarda su fecha y el estado de la pieza. El programa marca cuándo se ha cumplido el plazo que tengas configurado y la pieza pasa a estar disponible, de forma que no dependas de mirar fechas a mano."),
    ("Vendo también joya de ocasión. ¿Cómo se lleva eso?",
     "Como artículo único con stock uno, con su ficha, su fotografía y su precio de venta, enlazado con la operación de compra de la que salió. Las ventas de bienes usados se pueden separar de las ordinarias para el tratamiento que corresponda en el IVA."),
  ],
  rel=[("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Controlar la caja con varios empleados","/controlar-empleados-tpv.asp"),
       ("Copias de seguridad del TPV","/copia-seguridad-tpv.asp"),
       ("TPV para joyerías","/negocio_joyeria.asp"),
       ("TPV para tiendas de segunda mano","/negocio_vintage_segundamano.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# =============================================================== ALFOMBRAS
"negocio_alfombras.asp": dict(
  nombre="Tiendas de alfombras, moquetas y suelos textiles",
  crumb="Alfombras",
  icono="fa-rug",
  title="Software TPV para Tiendas de Alfombras a Medida",
  desc="TPV para tiendas de alfombras y moquetas: venta por metro cuadrado, corte y ribeteado a medida, presupuestos con señal, pedido bajo demanda e instalación.",
  kw="tpv alfombras, software tienda alfombras, tpv moquetas, programa venta metro cuadrado, tpv suelos textiles",
  h1='Software TPV para Tiendas de Alfombras. <span>Se vende por metro cuadrado y casi nada sale de la estantería.</span>',
  sub='Aquí la venta empieza con un cliente que trae las medidas del salón y termina tres semanas después con una instalación. Entre medias hay un presupuesto, una señal y un pedido al proveedor.',
  bloques=[
    ("Venta por superficie, con corte y ribete",
     ["Una moqueta se vende a tantos euros el metro cuadrado, en un ancho de rollo que es fijo. El cliente quiere 3,20 por 2,45, así que el importe sale de multiplicar, y el rollo baja en la cantidad que se ha cortado más el recorte que se pierde.",
      "Si el programa solo sabe sumar unidades enteras, el rollo de 30 metros te dirá siempre que está entero. Y el ribeteado del borde, que se cobra por metro lineal, se queda sin facturar más veces de las que parece."],
     ["<strong>Venta por metro cuadrado con decimales</strong>, con el ancho del rollo tomado de la ficha del artículo.",
      "<strong>Ribeteado y remates por metro lineal</strong> como línea propia del presupuesto.",
      "<strong>Descuento del rollo por metros consumidos</strong>, incluido el recorte que no se aprovecha.",
      "<strong>Precio distinto por calidad y por colección</strong>, que es como los tarifica el fabricante."]),
    ("El presupuesto es el documento que manda",
     ["Nadie compra una alfombra a medida en el mostrador y se la lleva. Lo que sale de la tienda es un presupuesto con medidas, calidad, ribete, transporte y colocación, y de ahí a la venta pueden pasar semanas.",
      "Ese presupuesto tiene que poder convertirse en pedido sin volver a teclearlo, y llevar asociada la señal que ha dejado el cliente. Media docena de presupuestos abiertos a la vez es lo normal en este oficio."],
     ["<strong>Presupuesto con validez y conversión directa a pedido</strong> sin reescribir las líneas.",
      "<strong>Señal o anticipo</strong> registrado y descontado en la liquidación final.",
      "<strong>Estado del encargo</strong>: presupuestado, pedido al proveedor, recibido, instalado y cobrado.",
      "<strong>Aviso de presupuestos que caducan</strong> para llamar antes de perderlos."]),
    ("Casi todo se pide, poco se almacena",
     ["El escaparate es un muestrario. El stock de verdad está en el almacén del fabricante, y lo que tú tienes son cartas de color, retales de muestra y dos o tres modelos de rotación. Eso cambia la forma de trabajar del programa: el artículo existe en catálogo aunque no tengas ni un metro.",
      "Lo importante entonces es enlazar cada encargo con el pedido de compra que lo cubre, para saber en cualquier momento qué le contestas al cliente que llama preguntando por su alfombra."],
     ["<strong>Artículo de catálogo sin stock</strong>, que se pide al confirmar la venta.",
      "<strong>Pedido de compra enlazado al encargo del cliente.</strong>",
      "<strong>Control de muestrarios prestados</strong> con fecha de salida y de devolución.",
      "<strong>Plazo de entrega por proveedor</strong> guardado en la ficha, para prometer con criterio."]),
    ("Transporte, colocación y lo que pasa después",
     ["La instalación es un servicio con su precio, y a menudo la hace un colocador externo que cobra aparte. Facturarlo como una línea del encargo, y no de palabra, es lo que te deja saber al final del año cuánto margen te queda de verdad después de pagar el porte y la mano de obra.",
      "Y queda el servicio de limpieza y arreglo de alfombras, que muchas tiendas prestan y casi ninguna controla. Un resguardo con la prenda, su estado de entrada y la fecha de recogida evita la discusión de la mancha que ya venía."]),
  ],
  faqs=[
    ("¿Puedo vender moqueta por metro cuadrado con decimales?",
     "Sí. El artículo se da de alta como venta por superficie con el ancho del rollo en la ficha. Introduces largo y ancho, el programa calcula los metros y el importe, y descuenta del rollo los metros consumidos."),
    ("¿Se puede cobrar el ribeteado del borde aparte?",
     "Sí, como línea de servicio por metro lineal dentro del mismo encargo. Al ir en el presupuesto queda facturado y deja de ser lo que se olvida cobrar."),
    ("Trabajo con presupuestos que tardan semanas en cerrarse. ¿Los guarda?",
     "Sí, con su fecha de validez y su estado. Cuando el cliente acepta, el presupuesto se convierte en pedido sin volver a teclear las líneas, arrastrando medidas, calidad y servicios."),
    ("El cliente deja una señal. ¿Cómo se registra?",
     "Como anticipo asociado al encargo. Entra en la caja del día en que se cobra y se descuenta del importe pendiente cuando se liquida la venta al entregar."),
    ("No tengo stock de casi nada, lo pido al fabricante. ¿Me sirve igual?",
     "Sí. Los artículos viven en el catálogo con precio y plazo aunque el stock sea cero, y cada encargo se enlaza con el pedido de compra que lo cubre, de forma que sabes qué contestar cuando el cliente llama preguntando."),
    ("¿Puedo llevar el servicio de limpieza y arreglo de alfombras?",
     "Sí, con un resguardo numerado donde queda la descripción de la pieza, su estado al entrar y la fecha prevista de recogida. Al entregar se cobra y se cierra el resguardo."),
  ],
  rel=[("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Cuentas de cliente y cobro a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("TPV para tiendas de muebles y decoración","/negocio_muebles.asp"),
       ("TPV para tiendas de ropa de cama y textil hogar","/negocio_textil_hogar.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ============================================================== JUGUETERIA
"negocio_jugueteria.asp": dict(
  nombre="Jugueterías tradicionales y educativas",
  crumb="Jugueterías",
  icono="fa-shapes",
  title="Software TPV para Jugueterías: campaña y apartados",
  desc="TPV para jugueterías: apartados con señal antes de Reyes, refuerzo de personal en campaña, edad y licencia como atributos, devoluciones de enero y regalo.",
  kw="tpv jugueteria, software jugueteria, programa tpv juguetes, tpv campaña navidad jugueteria, gestion stock jugueteria",
  h1='Software TPV para Jugueterías. <span>Seis semanas que valen medio año de facturación.</span>',
  sub='Entre el puente de diciembre y el 5 de enero una juguetería hace una parte enorme de su año, con personal de refuerzo, apartados pagados a plazos y una segunda quincena de enero llena de cambios.',
  bloques=[
    ("Los apartados: la venta que se cobra en tres veces",
     ["El apartado es la operación propia de este oficio. La clienta viene en noviembre, elige la cocinita, deja veinte euros y pasa a pagar otro poco a mediados de diciembre. La caja del día tiene ese dinero, pero la venta todavía no ha ocurrido y el juguete no puede venderse a otro.",
      "Llevar eso con post-its en la trastienda funciona hasta que hay cuarenta apartados a la vez y dos dependientas nuevas. Y en el peor momento del año."],
     ["<strong>Reserva con señal</strong> que retira el artículo del stock disponible y lo deja identificado con el cliente.",
      "<strong>Entregas a cuenta sucesivas</strong>, cada una registrada en la caja del día en que se cobra.",
      "<strong>Listado de apartados pendientes</strong> con lo entregado y lo que falta, para llamar a quien no ha vuelto.",
      "<strong>Liquidación al recoger</strong> descontando todo lo entregado, con su ticket o su factura."]),
    ("Edad, licencia y marcado: los datos por los que pregunta el cliente",
     ["En una juguetería el cliente pregunta por «algo para un niño de cuatro años» o por «algo de la serie esa», rara vez por una referencia de catálogo. Si esos datos no están en la ficha del artículo, el catálogo no sirve para vender, solo para inventariar.",
      "Los juguetes llevan además marcado CE y datos del fabricante o importador, y la edad recomendada forma parte de la información de seguridad del producto. Tenerlo en la ficha ayuda tanto en el mostrador como cuando hay que localizar un lote."],
     ["<strong>Franja de edad como atributo</strong> por el que se puede filtrar en caja.",
      "<strong>Licencia o marca</strong> para poder responder a la pregunta que trae la mitad de los clientes.",
      "<strong>Datos de fabricante o importador</strong> guardados en la ficha del artículo.",
      "<strong>Familias por tipo de juego</strong>: primera infancia, construcción, mesa, exterior, educativo."]),
    ("Campaña: más gente detrás del mostrador y más ojos en la caja",
     ["En campaña metes refuerzo, a veces gente que no volverá en marzo. El cajón lo abren cinco personas y el arqueo tiene que poder desglosarse por quién ha cobrado qué. No es desconfianza: es que un descuadre de ochenta euros sin saber de qué turno viene no se resuelve nunca.",
      "Lo mismo con los descuentos. Si cualquiera puede quitar un diez por ciento sin dejar rastro, en enero verás el margen y no sabrás explicarlo."],
     ["<strong>Usuario propio por dependiente</strong> y venta asociada a quien la cobra.",
      "<strong>Arqueo desglosado por persona y por turno.</strong>",
      "<strong>Permisos por perfil</strong>: quién puede anular una línea, hacer una devolución o aplicar descuento.",
      "<strong>Segunda caja en campaña</strong> trabajando contra el mismo catálogo y el mismo stock."]),
    ("Enero es el mes de las devoluciones y los regalos repetidos",
     ["Después de Reyes llega la otra mitad del trabajo: cambios, devoluciones y juguetes repetidos que vuelven sin ticket. Un ticket regalo que se pueda emitir en el momento de la compra, sin precio, y localizar después por su número resuelve casi todos esos casos sin discusión.",
      "Y el vale de saldo, que es lo que te deja que el dinero se quede en la tienda en lugar de salir por la puerta. Conviene que tenga número, importe y caducidad, y que el programa sepa cuánto vale acumulado tienes pendiente."]),
  ],
  faqs=[
    ("¿Puedo llevar los apartados de Navidad con sus entregas a cuenta?",
     "Sí. La reserva retira el artículo del stock disponible y queda a nombre del cliente. Cada entrega a cuenta se registra en la caja del día en que se cobra, y al recoger se liquida el pendiente descontando todo lo entregado."),
    ("¿Cómo sé qué apartados están sin recoger a fecha 3 de enero?",
     "Con el listado de apartados pendientes, que muestra el artículo, el cliente, lo entregado y lo que falta. Es la lista con la que se hacen las llamadas de los últimos días de campaña."),
    ("¿Puedo buscar juguetes por edad recomendada en el mostrador?",
     "Sí, si la edad está dada de alta como atributo del artículo. Se puede filtrar por franja de edad y por licencia o marca, que son las dos formas en que pregunta el cliente."),
    ("En campaña tengo tres personas de refuerzo. ¿Puedo controlar la caja?",
     "Cada persona entra con su usuario y sus ventas quedan asociadas. El arqueo se desglosa por persona y por turno, y puedes limitar por perfil quién anula, quién devuelve y quién aplica descuentos."),
    ("¿Emite ticket regalo sin precio?",
     "Sí, en el momento de la compra. Lleva su número, con el que se localiza la venta original en enero aunque el cliente no traiga el ticket normal, de forma que el cambio se hace sin discutir el importe."),
    ("¿Y los vales de las devoluciones?",
     "Se emiten como vale con número, importe y caducidad, y se descuentan de una compra posterior. El programa te dice cuánto saldo en vales tienes pendiente de que vuelva a la tienda."),
  ],
  rel=[("Cómo hacer una devolución o cambio en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("Controlar la caja con varios empleados","/controlar-empleados-tpv.asp"),
       ("Cómo abrir una juguetería","/abrir-jugueteria.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("TPV para papelerías","/negocio_papeleria.asp")]),

# ================================================================= VINILOS
"negocio_vinilos.asp": dict(
  nombre="Tiendas de discos de vinilo y música de ocasión",
  crumb="Vinilos",
  icono="fa-record-vinyl",
  title="TPV para Tiendas de Vinilos y Disco de Ocasión",
  desc="TPV para tiendas de vinilos: cada ejemplar es único con su estado de disco y carpeta, compra de colecciones a particulares, depósito y reservas.",
  kw="tpv tienda discos, software tienda vinilos, programa tpv vinilo, tpv segunda mano musica, gestion tienda discos",
  h1='Software TPV para Tiendas de Vinilos. <span>Cada ejemplar es una unidad distinta, aunque el disco sea el mismo.</span>',
  sub='Dos copias del mismo álbum no valen igual: una es una reedición precintada y la otra es una primera edición del 72 con la carpeta rozada. El catálogo tiene que poder distinguirlas.',
  bloques=[
    ("Stock uno, y el estado forma parte del precio",
     ["En la tienda de discos de ocasión el artículo es este ejemplar de «Kind of Blue», con su prensaje, su sello, su número de catálogo y su estado. La reedición que tienes tres cajones más allá lleva el mismo título y se vende a otro precio. Cada una se vende una vez y se acabó.",
      "Y el estado se valora en dos partes, disco y carpeta, porque se estropean por separado. Un programa que trate el catálogo como referencias con stock reponible no encaja en este oficio."],
     ["<strong>Artículo único con stock uno</strong>, que desaparece del catálogo al venderse.",
      "<strong>Estado del disco y estado de la carpeta</strong> como dos campos, con la escala que uses en la tienda.",
      "<strong>Sello, año y número de catálogo</strong> en la ficha, que es como se identifica una edición.",
      "<strong>Ubicación en la tienda</strong>: cajón, sección y letra, para encontrarlo cuando alguien pregunta por él."]),
    ("Comprar colecciones a particulares",
     ["Buena parte del género entra por la puerta: alguien vacía la casa de su padre y aparece con seis cajas. Eso es una compra a particular, con su documento y su importe, y a menudo con doscientos discos que hay que dar de alta uno a uno.",
      "Lo que hace manejable el trabajo es poder registrar la compra como un lote con su coste total y luego ir sacando fichas individuales, repartiendo el coste, sin tener que decidir en el momento el precio de cada disco."],
     ["<strong>Documento de compra a particular</strong> con sus datos y el importe pagado.",
      "<strong>Alta por lote</strong> con coste global, y reparto posterior al ir fichando disco a disco.",
      "<strong>Estado «por catalogar»</strong> para lo que está comprado y todavía no tiene precio.",
      "<strong>Margen real por lote</strong>, para saber si aquella compra de seis cajas salió a cuenta."]),
    ("El disco que no es tuyo: depósito y consigna",
     ["Muchas tiendas tienen fondo en depósito, de un particular o de un sello pequeño, que se liquida cuando se vende. Ese disco ocupa sitio en el cajón pero no es stock tuyo, y confundirlos hace que el inventario valga más de lo que tienes.",
      "Con el propietario marcado en la ficha, al cerrar el mes sale solo lo que hay que liquidarle a cada uno y lo que se ha quedado la tienda de comisión."],
     ["<strong>Propietario del artículo</strong> distinguiendo fondo propio de depósito.",
      "<strong>Comisión por depositante</strong>, fija o por porcentaje.",
      "<strong>Liquidación mensual por propietario</strong> con lo vendido y el importe a pagarle.",
      "<strong>Devolución de lo no vendido</strong> dejando registro de qué se le devolvió y cuándo."]),
    ("Novedades, reservas y el día grande del año",
     ["Junto al fondo de ocasión está la novedad, que sí funciona como catálogo normal con su código de barras y su reposición. Ahí lo que hace falta son reservas: el cliente que aparta la edición limitada antes de que salga y pasa a por ella el viernes.",
      "El Record Store Day concentra en una mañana una cantidad de gente que no se parece a ningún otro día, con tiradas cortas y una lista de reservas que hay que poder consultar sin abrir un cuaderno."]),
  ],
  faqs=[
    ("Cada disco de segunda mano es distinto. ¿Puedo llevarlos uno a uno?",
     "Sí. Cada ejemplar se da de alta como artículo único con stock uno, con su sello, su año, su número de catálogo y su ubicación en la tienda. Al venderse desaparece del catálogo disponible."),
    ("¿Puedo guardar el estado del disco y el de la carpeta por separado?",
     "Sí, son dos campos distintos en la ficha, cada uno con la escala de conservación que uses habitualmente. Es lo que permite que dos copias del mismo título tengan precios diferentes."),
    ("Compro colecciones enteras a particulares. ¿Cómo se registra?",
     "Como una compra a particular con sus datos y el importe total. El lote entra con su coste global y vas creando las fichas individuales a medida que catalogas, repartiendo el coste, sin tener que poner precio a doscientos discos el mismo día."),
    ("Tengo discos en depósito de otras personas. ¿Se distinguen de los míos?",
     "Sí, marcando el propietario en la ficha. El inventario separa fondo propio de depósito, y al cerrar el mes sale la liquidación de lo vendido de cada depositante con su comisión aplicada."),
    ("¿Puedo llevar reservas de novedades?",
     "Sí. La reserva queda a nombre del cliente y retira la unidad del disponible, con aviso al llegar el pedido. Es lo que evita vender por error el ejemplar que alguien tenía apartado."),
    ("¿Sirve también para el CD, el casete y el merchandising?",
     "Sí. Conviven en el mismo catálogo el artículo único de ocasión y el artículo con reposición y código de barras, cada uno con su forma de trabajar, y las ventas salen desglosadas por familia."),
  ],
  rel=[("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("TPV para tiendas de segunda mano y vintage","/negocio_vintage_segundamano.asp"),
       ("TPV para tiendas de instrumentos musicales","/negocio_instrumentos.asp"),
       ("TPV para tiendas de cómics y manga","/negocio_comics.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ============================================================ INSTRUMENTOS
"negocio_instrumentos.asp": dict(
  nombre="Tiendas de instrumentos musicales y taller",
  crumb="Instrumentos",
  icono="fa-guitar",
  title="TPV para Tiendas de Instrumentos y Taller | Caja 5",
  desc="TPV para tiendas de música: número de serie por unidad, partes de reparación del taller, alquiler escolar, consumibles de rotación alta y ocasión.",
  kw="tpv tienda instrumentos musicales, software tienda musica, programa tpv luthier, tpv alquiler instrumentos, gestion tienda musica",
  h1='Software TPV para Tiendas de Instrumentos. <span>Tres negocios en el mismo local: venta, taller y alquiler.</span>',
  sub='Una tienda de música vende cuerdas de cinco euros y saxofones de tres mil, repara lo que trae la gente y alquila clarinetes a estudiantes cada septiembre. Cada una de las tres cosas se controla distinto.',
  bloques=[
    ("El instrumento se identifica por número de serie",
     ["Cinco guitarras del mismo modelo son cinco unidades con cinco números de serie. Cuando una vuelve por garantía hace falta saber cuál de ellas se vendió, a quién y en qué fecha.",
      "El número de serie es también lo que te permite contestar cuando alguien llama diciendo que le han robado un instrumento, y lo que hace verificable la trazabilidad de una venta de ocasión."],
     ["<strong>Número de serie por unidad</strong> capturado en la entrada y en la venta.",
      "<strong>Garantía asociada al cliente</strong> con la fecha de venta y su plazo.",
      "<strong>Histórico de la unidad</strong>: entrada, ventas, devoluciones y reparaciones.",
      "<strong>Ficha con marca, modelo y acabado</strong>, que es como pregunta el músico."]),
    ("El taller: lo que entra a reparar no es stock",
     ["El clarinete que deja un cliente para cambiar zapatillas no es mercancía tuya, pero está en tu local, tiene un presupuesto pendiente de aprobación y una fecha comprometida. Si eso vive en una libreta, antes o después se pierde un instrumento o se entrega sin cobrar la mano de obra.",
      "El parte de reparación resuelve las dos cosas: identifica el instrumento con su serie y su estado de entrada, guarda el presupuesto y acumula las piezas y las horas que se le van dedicando."],
     ["<strong>Parte de reparación numerado</strong> con el instrumento, su estado al entrar y el aviso al cliente.",
      "<strong>Presupuesto previo</strong> con aprobación registrada antes de empezar.",
      "<strong>Piezas y mano de obra imputadas al parte</strong>, descontando el material del stock.",
      "<strong>Estados del trabajo</strong>: recibido, presupuestado, en curso, terminado y entregado."]),
    ("Septiembre y el alquiler a estudiantes",
     ["Cada curso empieza igual: los padres del conservatorio vienen a por un instrumento de estudio en alquiler, con su cuota mensual y a veces con opción de compra al cabo de dos años. Eso es una unidad concreta que sale de la tienda y tiene que volver.",
      "Lo que se controla aquí es el contrato: qué unidad, a quién, desde cuándo, cuánto se cobra al mes y en qué estado se devolvió. Sin eso, en junio nadie sabe qué instrumentos hay fuera."],
     ["<strong>Contrato de alquiler por unidad</strong> con su número de serie y su fianza.",
      "<strong>Cuota periódica</strong> con control de lo cobrado y lo pendiente.",
      "<strong>Estado de entrega y de devolución</strong> para poder reclamar el desperfecto.",
      "<strong>Listado de instrumentos fuera</strong> en cualquier momento del curso."]),
    ("Cuerdas, cañas y baquetas: el otro extremo del catálogo",
     ["El consumible es lo contrario del instrumento. Rota constantemente, tiene código de barras, se vende por juego o por unidad suelta y es donde se gana el margen del día a día. Que no se agote un martes por la tarde depende de tener un stock mínimo por artículo y un pedido que salga solo cuando se baja de él.",
      "La ocasión y la tasación cierran el círculo: el cliente que cambia su guitarra por otra deja una unidad usada que entra al catálogo con su serie, su estado y el importe que se le ha descontado."]),
  ],
  faqs=[
    ("¿Puedo guardar el número de serie de cada instrumento que vendo?",
     "Sí. La unidad entra con su número de serie y se vincula al cliente en la venta, con lo que puedes recuperar el histórico completo de esa unidad: cuándo entró, a quién se vendió, su garantía y las reparaciones que ha tenido."),
    ("¿Lleva los partes de reparación del taller?",
     "Sí, con su numeración, el instrumento y su estado al entrar, el presupuesto y su aprobación, y las piezas y horas que se le imputan. Las piezas se descuentan del stock al usarse y el trabajo pasa por sus estados hasta la entrega."),
    ("Alquilo instrumentos a estudiantes por curso. ¿Se puede controlar?",
     "Sí, con contrato por unidad. Queda registrado qué instrumento ha salido, a quién, desde cuándo, la fianza y la cuota, y en cualquier momento tienes el listado de lo que está fuera de la tienda."),
    ("¿Puedo saber si una reparación se entregó sin cobrar?",
     "Sí. El parte no se cierra hasta que se liquida, y tienes el listado de trabajos terminados pendientes de cobro, que es donde suele estar el dinero olvidado en este oficio."),
    ("¿Cómo evito quedarme sin cuerdas o sin cañas?",
     "Fijando un stock mínimo por artículo. El programa te saca la propuesta de pedido con lo que ha bajado del mínimo, agrupada por proveedor, para que salga en un solo pedido."),
    ("Acepto instrumentos usados como parte del pago. ¿Se registra?",
     "Sí. La unidad usada entra al catálogo con su número de serie, su estado y el importe tasado que se le ha descontado al cliente, de forma que después puedes ver el margen real de esa operación."),
  ],
  rel=[("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Cuentas de cliente y cobro a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("TPV para tiendas de vinilos","/negocio_vinilos.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ========================================================= FIESTAS Y DISFRACES
"negocio_fiestas_disfraces.asp": dict(
  nombre="Tiendas de disfraces y artículos de fiesta",
  crumb="Disfraces y fiesta",
  icono="fa-masks-theater",
  title="TPV para Tiendas de Disfraces y Fiesta | Caja 5",
  desc="TPV para tiendas de fiesta y disfraces: alquiler con fianza y fechas, tallas, packs de cumpleaños, dos temporadas al año y globos de helio como servicio.",
  kw="tpv tienda disfraces, software alquiler disfraces, tpv articulos fiesta, programa tienda cotillon, tpv globos helio",
  h1='Software TPV para Tiendas de Fiesta y Disfraces. <span>La mitad del género se alquila y vuelve.</span>',
  sub='Un disfraz que sale de la tienda por Carnaval tiene fecha de vuelta, una fianza y una talla. Y el resto del año la tienda vive de cumpleaños, globos y cotillón, que funcionan de otra manera.',
  bloques=[
    ("Alquilar es prestar, y lo prestado hay que traerlo de vuelta",
     ["La venta se acaba en el mostrador. El alquiler empieza ahí: sale una unidad concreta, con su talla, en una fecha, con una fianza en el cajón, y tiene que volver el martes. Mientras está fuera no se puede alquilar a nadie más.",
      "En la semana de Carnaval hay decenas de trajes fuera a la vez. La lista de lo que tiene que volver cada día es lo que evita el clásico de alquilar dos veces el mismo traje para el mismo sábado."],
     ["<strong>Contrato de alquiler</strong> con la unidad, la talla, la fecha de salida y la de devolución.",
      "<strong>Fianza registrada</strong>, devuelta al entregar o descontada si hay desperfecto.",
      "<strong>Disponibilidad por fechas</strong>, para no comprometer dos veces el mismo traje.",
      "<strong>Listado de devoluciones del día</strong> y aviso de los que se han pasado de fecha."]),
    ("Tallas, complementos y el traje que se compone",
     ["Un disfraz de pirata es la casaca, el sombrero, el cinto y el garfio, y a veces se alquila entero y a veces por piezas. Además existe en cinco tallas, y la talla es lo primero que pregunta el cliente por teléfono.",
      "El catálogo tiene que llevar la talla como variante del mismo modelo, no como cinco artículos sin relación, o no habrá forma de saber qué tienes disponible de verdad."],
     ["<strong>Talla y color como variantes</strong> de un mismo modelo, con stock propio cada una.",
      "<strong>Conjuntos formados por piezas</strong> que también se pueden alquilar sueltas.",
      "<strong>Estado de la prenda</strong>: disponible, alquilada, en tintorería o retirada.",
      "<strong>Coste de limpieza</strong> imputado al ciclo de alquiler, para saber el margen real de cada traje."]),
    ("Dos temporadas y once meses de cumpleaños",
     ["Halloween y Carnaval concentran el alquiler, pero la caja de un martes de mayo la hacen los cumpleaños infantiles: el pack de mesa, las bolsas de chuches, los globos y el cotillón. Ahí el artículo es barato, se vende en cantidad y a menudo se compone en un pack con precio cerrado.",
      "Ese pack conviene que sea un artículo con su escandallo, para que al venderlo baje el stock de cada componente y sepas qué te cuesta de verdad."],
     ["<strong>Packs con escandallo</strong> que descuentan del stock cada componente al venderse.",
      "<strong>Venta por unidad desde bolsas grandes</strong>, con la conversión hecha en la ficha.",
      "<strong>Comparativa entre temporadas</strong> para pedir con datos y no de memoria.",
      "<strong>Precios de campaña</strong> aplicados por familia y con fecha de fin."]),
    ("Los globos de helio y lo que no es producto",
     ["Inflar globos, montar un arco o preparar una decoración a domicilio son servicios con su precio y su mano de obra, y en muchas tiendas suman más de lo que parece. Facturarlos como línea propia es lo que te deja saber al cabo del año si compensa el alquiler de la botella de helio.",
      "El encargo con fecha ayuda además a organizar la semana: un arco de globos para el sábado a las diez es un trabajo, no una venta de mostrador."]),
  ],
  faqs=[
    ("¿Puedo llevar el alquiler de disfraces con su fianza?",
     "Sí. El contrato registra la unidad concreta, la talla, la fecha de salida y la prevista de devolución, junto con la fianza cobrada, que se devuelve al entregar o se descuenta en parte si hay desperfecto."),
    ("¿Cómo evito alquilar dos veces el mismo traje para el mismo día?",
     "Con la disponibilidad por fechas. Al comprometer una unidad para un fin de semana deja de aparecer como libre en ese rango, con lo que la reserva por teléfono se puede hacer con seguridad."),
    ("Las tallas. ¿Tengo que dar de alta un artículo por cada una?",
     "No. La talla es una variante del mismo modelo, con su stock propio. Ves de un vistazo qué tallas te quedan de ese disfraz sin recorrer un listado de artículos sueltos."),
    ("¿Me avisa de los disfraces que no han vuelto?",
     "Sí, con el listado de devoluciones previstas de cada día y el de los que se han pasado de fecha, que es con el que se hacen las llamadas del lunes después de Carnaval."),
    ("Vendo packs de cumpleaños con varios artículos. ¿Descuenta el stock de cada uno?",
     "Sí, si el pack se da de alta con su escandallo. Al venderlo baja el stock de cada componente y el programa te dice cuánto te cuesta el pack en material, que es lo que te deja fijar el precio con criterio."),
    ("¿Puedo cobrar aparte el inflado de globos o el montaje de un arco?",
     "Sí, como servicios con precio propio. Al ir como línea de la venta quedan facturados y puedes ver al cabo del año cuánto has hecho por servicio frente a producto."),
  ],
  rel=[("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Cambiar precios en masa","/cambiar-precios-masivamente-tpv.asp"),
       ("Cómo hacer una devolución o cambio en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("TPV para jugueterías","/negocio_jugueteria.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# =================================================================== SKATE
"negocio_skate.asp": dict(
  nombre="Tiendas de skate, patinaje y rollers",
  crumb="Skate",
  icono="fa-person-skating",
  title="Software TPV para Tiendas de Skate y Patinaje",
  desc="TPV para skate shops: completas montadas por componentes, montaje como servicio, medidas en pulgadas, calzado por tallas y garantía de tabla.",
  kw="tpv skate shop, software tienda skate, programa tpv patines, tpv tienda longboard, gestion skate shop",
  h1='Software TPV para Skate Shops. <span>Una completa son siete piezas y media hora de taller.</span>',
  sub='El cliente que entra a por su primera tabla sale con una completa que has montado tú: tabla, ejes, ruedas, rodamientos, tornillería y lija. Siete artículos que salen del stock y una tarifa de montaje.',
  bloques=[
    ("La completa: un artículo que se compone en el momento",
     ["Vender una completa es descontar una tabla de 8,25 pulgadas, un juego de ejes, cuatro ruedas, ocho rodamientos, la tornillería y la lija, y cobrar además el montaje. Y cada cliente la quiere con una combinación distinta.",
      "Si eso se teclea como una línea de «completa 180 €», el stock no baja de ningún componente y a final de mes tienes ruedas fantasma en el inventario."],
     ["<strong>Escandallo configurable</strong>: el cliente elige tabla, ejes y ruedas y el programa arma la venta con esos componentes.",
      "<strong>Descuento de stock por componente</strong>, no por el conjunto.",
      "<strong>Montaje como línea de servicio</strong> con su precio, para que no se regale.",
      "<strong>Completas cerradas de catálogo</strong> para quien no quiere elegir, con su propio escandallo."]),
    ("Medidas que son atributos, no descripción suelta",
     ["Una tabla se pide por pulgadas de ancho, unas ruedas por milímetros y dureza, unos rodamientos por su clasificación. El cliente entra sabiendo lo que quiere y pregunta por la medida, así que si eso vive dentro del nombre del artículo no hay forma de filtrar.",
      "Con las medidas como atributos puedes contestar en diez segundos qué tienes en 8,0 y en 8,5, que es la diferencia entre vender y que se vaya a mirarlo en el móvil."],
     ["<strong>Ancho de tabla en pulgadas</strong> como atributo filtrable.",
      "<strong>Diámetro y dureza de rueda</strong> por separado.",
      "<strong>Talla de calzado</strong> como variante del modelo, con su curva de tallas.",
      "<strong>Marca y modelo</strong>, que es como está montada la cabeza del cliente en este sector."]),
    ("El calzado, que es media tienda y funciona distinto",
     ["Las zapatillas se venden por talla, y la curva es lo que decide si el pedido fue bueno. Tener ocho pares del modelo pero ninguno del 42 y del 43 es tener stock parado, y eso solo se ve si el programa te desglosa por talla y no por modelo.",
      "En cierre de temporada la misma información te dice qué modelo liquidar y en qué tallas, en lugar de rebajar todo un veinte por ciento a ciegas."],
     ["<strong>Curva de tallas por modelo y color</strong>, con stock y ventas de cada una.",
      "<strong>Alerta de tallas centrales agotadas</strong>, que son las que hacen la venta.",
      "<strong>Reposición por talla</strong> en la propuesta de pedido al proveedor.",
      "<strong>Liquidación selectiva</strong> por modelo, color y talla al cerrar temporada."]),
    ("Tablas rotas, garantías y el cliente que vuelve cada mes",
     ["La tabla que se parte en una semana llega al mostrador y hay que decidir. Tener la venta localizada por fecha y por cliente, con la marca y el lote, es lo que te deja tramitar la garantía con el distribuidor en lugar de comerte la pieza para no perder al chaval.",
      "Y el chaval vuelve. Es un cliente de recurrencia alta que gasta poco cada vez, así que la ficha con su histórico y su talla de zapatilla vale más aquí que en casi cualquier otro comercio."]),
  ],
  faqs=[
    ("Monto completas a medida. ¿Descuenta el stock de cada componente?",
     "Sí. La completa se arma como un escandallo con los componentes que elige el cliente, y al cobrarla baja el stock de tabla, ejes, ruedas, rodamientos, tornillería y lija por separado, con el montaje como línea de servicio."),
    ("¿Puedo cobrar el montaje aparte del material?",
     "Sí, como servicio con su precio dentro de la misma venta. Al ir en línea propia sabes al cabo del año cuánto has facturado por taller, que en una skate shop suele ser más de lo que se piensa."),
    ("¿Se pueden buscar tablas por ancho en pulgadas?",
     "Sí, si el ancho está dado de alta como atributo. Lo mismo con el diámetro y la dureza de las ruedas, de forma que puedes contestar al momento qué tienes en cada medida sin recorrer el catálogo entero."),
    ("¿Cómo controlo la curva de tallas de las zapatillas?",
     "La talla es una variante del modelo y el color, con su stock y sus ventas propias. El desglose te enseña dónde se te han agotado las tallas centrales, que es cuando el modelo deja de venderse aunque el stock total parezca alto."),
    ("Se me parte una tabla en garantía. ¿Puedo localizar la venta?",
     "Sí, buscando por cliente o por fecha. Recuperas la venta con la marca, el modelo y el importe, que es lo que necesitas para tramitarlo con el distribuidor."),
    ("¿Puedo ver qué me compra habitualmente cada cliente?",
     "Sí, con la ficha de cliente y su histórico de compras. En una tienda de recurrencia alta como esta sirve para saber su talla y sus medidas sin preguntar, y para avisarle cuando entra lo que suele llevarse."),
  ],
  rel=[("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("TPV para tiendas de montaña y outdoor","/negocio_montana.asp"),
       ("TPV para tiendas de bicicletas","/negocio_bicicletas.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

}
