# -*- coding: utf-8 -*-
"""Base de hechos por sector, lote 5: segunda tanda de paginas de sector cortas.

Mismo criterio que sectores_4: las mas cortas de la web del cliente (734-743
palabras) de entre las que no aparecen ni en la seccion A ni en la seccion B de
informes/clusters_cruzados.txt, o sea que no compiten con carrito5.com ni con
otra pagina del propio abacosoftware.

Queda fuera a proposito negocio_herbodietetica.asp: el motor no la marca, pero
negocio_herboristeria.asp si aparece en la seccion A y las dos hablan del mismo
mostrador. Profundizar una sin la otra delante es pedir una canibalizacion.
"""

SECTORES_5 = {

# ================================================================= MALETAS
"negocio_maletas.asp": dict(
  nombre="Tiendas de maletas y marroquinería de viaje",
  crumb="Maletas",
  icono="fa-suitcase-rolling",
  title="Software TPV para Tiendas de Maletas y Viaje",
  desc="TPV para tiendas de maletas: medidas de cabina por compañía, juegos de tres, reparación de ruedas y cremalleras con recambio, y garantía del fabricante.",
  kw="tpv tienda maletas, software marroquineria, programa tpv equipaje, tpv tienda viaje, gestion tienda maletas",
  h1='Software TPV para Tiendas de Maletas. <span>Se vende por medidas, y la venta no acaba en la caja.</span>',
  sub='El cliente pregunta si le entra en la cabina de la compañía con la que vuela, se lleva un juego de tres y vuelve a los diez meses con una rueda rota. Las tres cosas se controlan distinto.',
  bloques=[
    ("La medida es el argumento de venta, así que va en la ficha",
     ["Nadie compra una maleta por su referencia. Se compra por si mide 55 por 40 por 20, por cuántos litros tiene y por lo que pesa vacía, porque de eso depende que pase como equipaje de mano o que haya que facturarla.",
      "Cuando esos datos viven dentro del nombre del artículo no hay forma de filtrar, y el dependiente acaba midiendo con una cinta delante del cliente."],
     ["<strong>Alto, ancho y fondo como atributos</strong> por los que se puede buscar en caja.",
      "<strong>Capacidad en litros y peso en vacío</strong>, que es lo que decide la compra de una cabina.",
      "<strong>Material y tipo de cierre</strong>: rígida, blanda, policarbonato, con o sin cierre TSA.",
      "<strong>Comparación rápida entre dos modelos</strong> para el cliente que duda entre la mediana y la grande."]),
    ("Juegos de tres que también se venden sueltos",
     ["El set de cabina, mediana y grande se vende como un artículo con su precio cerrado, pero la mediana suelta también se vende. Y cuando alguien se lleva el juego, del almacén salen tres piezas, no una.",
      "Si el juego se teclea como una línea suelta, el stock de las tres medidas deja de cuadrar el mismo día, y en un artículo caro eso se nota rápido en el inventario."],
     ["<strong>Juego con escandallo</strong> que descuenta las tres piezas al venderse.",
      "<strong>Venta por unidad suelta</strong> del mismo modelo y color.",
      "<strong>Color como variante</strong> con su stock propio, que es la otra pregunta del mostrador.",
      "<strong>Precio del juego distinto de la suma</strong> de las tres piezas, que es como lo tarifica la marca."]),
    ("La rueda rota vuelve a tu puerta",
     ["Una maleta se rompe siempre por lo mismo: rueda, asa o cremallera. El cliente vuelve contigo, no con la marca, y la diferencia entre perderlo y fidelizarlo es poder decirle en el momento si está en garantía y cuánto tarda el recambio.",
      "Para eso hace falta localizar la venta, saber la fecha y tener el recambio como artículo con su referencia, porque las ruedas no son universales."],
     ["<strong>Venta localizable por cliente y fecha</strong> para saber si la garantía sigue viva.",
      "<strong>Recambios como artículos</strong> con su referencia de marca y modelo compatible.",
      "<strong>Parte de reparación</strong> con presupuesto, estado y aviso al cliente cuando está lista.",
      "<strong>Reparación en garantía separada de la de pago</strong>, para saber cuánto te cuesta cada marca."]),
    ("Dos picos al año y un escaparate que se mira mucho",
     ["Junio y diciembre concentran la venta, y el resto del año lo sostienen el bolso, la mochila escolar y el artículo de regalo. Comparar la campaña de este verano con la del anterior por modelo es lo que te dice qué pedir, en lugar de repetir el pedido del año pasado.",
      "Es además un artículo voluminoso y caro que se expone en la puerta, así que conviene tener el inventario al día por modelo y color, y no solo por familia, para saber qué se está yendo del expositor."]),
  ],
  faqs=[
    ("¿Puedo buscar maletas por medidas para saber si valen de cabina?",
     "Sí, si el alto, el ancho y el fondo están dados de alta como atributos del artículo. Se filtra por medida y por litros, que es como pregunta el cliente cuando ya sabe con qué compañía vuela."),
    ("Vendo juegos de tres maletas. ¿Descuenta las tres del stock?",
     "Sí, si el juego se da de alta con su escandallo. Al venderlo bajan las tres piezas por separado, y el juego puede tener un precio distinto de la suma de las tres sueltas."),
    ("¿Puedo saber si una maleta que vuelve rota sigue en garantía?",
     "Sí, localizando la venta por cliente o por fecha. Recuperas el modelo, el importe y el día, que es lo que necesitas para decidir en el mostrador si el arreglo va en garantía o se presupuesta."),
    ("¿Se pueden llevar los recambios de ruedas y cremalleras?",
     "Sí, como artículos con su referencia y los modelos con los que son compatibles. Así se pide el recambio correcto a la primera y se descuenta del stock al montarlo."),
    ("¿Cómo controlo los arreglos que tengo en el taller?",
     "Con un parte por reparación: el artículo, la avería, el presupuesto y su estado hasta la entrega. Tienes en todo momento la lista de lo que está pendiente de recambio y de lo que ya se puede avisar."),
    ("¿Puedo comparar la campaña de verano con la del año pasado?",
     "Sí, con el informe de ventas por artículo entre dos periodos. Ves por modelo y color qué se agotó y qué se quedó, que es la información con la que se hace el pedido de la campaña siguiente."),
  ],
  rel=[("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Cómo hacer una devolución o cambio en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("TPV para tiendas de complementos","/negocio_complementos.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ================================================================= MONTAÑA
"negocio_montana.asp": dict(
  nombre="Tiendas de montaña, trekking y outdoor",
  crumb="Montaña",
  icono="fa-mountain-sun",
  title="TPV para Tiendas de Montaña y Trekking | Caja 5",
  desc="TPV para tiendas de montaña: material de seguridad con lote y vida útil, alquiler de raquetas y crampones, curva de tallas de bota y temporada de nieve.",
  kw="tpv tienda montaña, software tienda deportes montaña, tpv trekking outdoor, alquiler material montaña, tpv tienda esqui",
  h1='Software TPV para Tiendas de Montaña. <span>Hay material que caduca y material que se alquila.</span>',
  sub='Una cuerda y un arnés tienen fecha de fabricación y una vida útil que marca el fabricante. Las raquetas de nieve salen alquiladas el viernes y vuelven el domingo. Nada de eso lo lleva un TPV corriente.',
  bloques=[
    ("El material de seguridad se controla por lote y por fecha",
     ["Cuerdas, arneses, cascos, mosquetones y cintas son equipos de protección cuyo fabricante fija una vida útil y una fecha de caducidad recomendada, y que llevan identificación de lote. Vender una cuerda fabricada hace seis años es un problema que conviene no tener.",
      "El programa puede llevar ese control si el artículo admite lote con fecha: se sabe qué queda en la estantería, cuánto le falta y a quién se le vendió si el fabricante saca un aviso. Las obligaciones concretas que te apliquen conviene revisarlas con el fabricante y con tu asesor."],
     ["<strong>Lote y fecha en la entrada de mercancía</strong>, con alerta según se acerca el límite.",
      "<strong>Trazabilidad de la venta por lote</strong>, para poder avisar si hay una retirada.",
      "<strong>Rotación por lote más antiguo primero</strong>, que es lo que evita que se quede fondo caducando.",
      "<strong>Ficha con la documentación del artículo</strong>: referencia del fabricante y norma que declara cumplir."]),
    ("Alquilar raquetas, crampones y piolets",
     ["El fin de semana de nieve mueve más alquiler que venta. Sale un juego de raquetas del 40 el viernes por la tarde con una fianza, y tiene que volver el domingo en condiciones de salir otra vez el siguiente.",
      "Lo que se controla es la unidad: qué par ha salido, a quién, con qué fianza y en qué estado volvió. Con dos docenas de pares fuera, la libreta deja de funcionar el primer puente."],
     ["<strong>Contrato de alquiler por unidad</strong> con fechas de salida y de devolución.",
      "<strong>Fianza cobrada y devuelta</strong>, o descontada si el material vuelve dañado.",
      "<strong>Disponibilidad por fechas y por talla</strong>, para reservar por teléfono con seguridad.",
      "<strong>Coste de mantenimiento por unidad</strong>, para saber cuándo un par deja de rentar."]),
    ("La bota es una zapatería dentro de la tienda",
     ["El calzado técnico se vende por talla y por horma, y la curva es lo que decide si el pedido fue bueno. Un modelo con ocho pares pero ninguno del 42 está agotado en la práctica, aunque el stock total diga otra cosa.",
      "Y el cliente de montaña se prueba tres modelos con calcetín técnico y una mochila cargada. Saber al momento qué tallas quedan de cada uno evita el paseo al almacén cuatro veces."],
     ["<strong>Curva de tallas por modelo y color</strong>, con stock y ventas de cada talla.",
      "<strong>Aviso de tallas centrales agotadas</strong>, que son las que sostienen el modelo.",
      "<strong>Reposición por talla</strong> en la propuesta de pedido.",
      "<strong>Horma y ancho</strong> como atributo, para el cliente que ya sabe cuál le va."]),
    ("Una temporada de nieve y otra de travesía",
     ["El año tiene dos campañas con material distinto y un cliente que a veces es el mismo. Comparar la temporada de nieve de este año con la anterior, por familia y por modelo, es lo que evita comprar crampones de más y quedarse corto de bastones.",
      "Al cierre de cada una queda el trabajo de liquidar lo que no ha salido. Poder rebajar por familia, modelo y talla, y no todo un veinte por ciento a ciegas, es la diferencia entre recuperar caja y regalar margen."]),
  ],
  faqs=[
    ("¿Puedo controlar la caducidad de cuerdas y arneses?",
     "Sí, dando de alta el artículo con control de lote y fecha. Al recibir la mercancía se registra el lote, y el programa avisa según se acerca el límite de vida útil que marque el fabricante. Los requisitos que te apliquen conviene contrastarlos con el fabricante y con tu asesor."),
    ("Si el fabricante retira un lote, ¿puedo saber a quién se lo vendí?",
     "Sí, si la venta quedó asociada al lote. Recuperas las ventas de ese lote concreto con su cliente y su fecha, que es lo que necesitas para avisar."),
    ("Alquilo raquetas de nieve los fines de semana. ¿Se puede llevar?",
     "Sí, con contrato de alquiler por unidad. Queda registrado qué par ha salido, la talla, a quién, la fianza y las fechas, y la disponibilidad por fechas te deja reservar por teléfono sin comprometer dos veces el mismo material."),
    ("¿Cómo llevo la curva de tallas de las botas?",
     "La talla es una variante del modelo y el color, con su stock propio. El desglose enseña dónde se han agotado las tallas centrales, que es cuando un modelo deja de venderse aunque el total parezca alto."),
    ("¿Puedo comparar la temporada de nieve con la del año pasado?",
     "Sí, con ventas por artículo y familia entre dos periodos. Es la base del pedido de la campaña siguiente, en lugar de repetir el del año anterior."),
    ("Al cerrar temporada quiero rebajar solo lo que sobra. ¿Se puede?",
     "Sí, cambiando precios en masa con filtro por familia, modelo, color o talla, con fecha de fin. Así la rebaja cae donde hay stock parado y no sobre lo que se vende solo."),
  ],
  rel=[("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Cambiar precios en masa","/cambiar-precios-masivamente-tpv.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("TPV para tiendas de skate y patinaje","/negocio_skate.asp"),
       ("TPV para tiendas de bicicletas","/negocio_bicicletas.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp")]),

# ======================================================== CALZADO INFANTIL
"negocio_calzado_infantil.asp": dict(
  nombre="Zapaterías infantiles y calzado respetuoso",
  crumb="Calzado infantil",
  icono="fa-shoe-prints",
  title="TPV para Zapaterías Infantiles y Calzado Respetuoso",
  desc="TPV para zapaterías infantiles: medida del pie y horma en la ficha del niño, curva de tallas por edad, vuelta al cole y avisos de cambio de número.",
  kw="tpv zapateria infantil, software zapateria niños, tpv calzado respetuoso, programa tienda calzado infantil, curva tallas calzado",
  h1='Software TPV para Zapaterías Infantiles. <span>El cliente vuelve cada cuatro meses porque el pie crece.</span>',
  sub='En una zapatería de adultos vender bien es cerrar la venta. Aquí es que la madre vuelva en marzo, y para eso hay que saber qué número gastaba el niño en noviembre y qué horma le iba.',
  bloques=[
    ("La ficha se lleva por niño, con su talla y su horma",
     ["Quien paga es la madre, pero quien tiene talla, horma y ancho es el niño, y a menudo son tres. Guardar en la ficha de la familia cada niño con su número y su última compra es lo que convierte una venta suelta en un cliente que vuelve tres veces al año.",
      "Con eso puedes avisar cuando entra el modelo que le gustó en el número siguiente, que es la venta más fácil que hay en este oficio y la que casi nadie trabaja."],
     ["<strong>Varios niños por ficha de familia</strong>, cada uno con su número y su horma.",
      "<strong>Histórico de compras por niño</strong>, con el modelo y la fecha.",
      "<strong>Medida real del pie en milímetros</strong>, además del número, porque no equivalen entre marcas.",
      "<strong>Aviso de cambio de número</strong> según el tiempo transcurrido desde la última compra."]),
    ("La curva de tallas manda más que en ningún otro calzado",
     ["El rango va del 18 al 39 y cada marca tiene su equivalencia. Un modelo con veinte pares repartidos en veintidós tallas está agotado en la práctica, y el stock total no te lo dice.",
      "Además la venta se concentra en las tallas centrales de cada tramo, que son las que primero desaparecen. Verlo por talla y no por modelo es lo que permite reponer a tiempo dentro de la temporada."],
     ["<strong>Stock y ventas por talla</strong> dentro de cada modelo y color.",
      "<strong>Tramos por edad</strong>: primeros pasos, preandante, párvulo y juvenil, cada uno con su rango.",
      "<strong>Reposición por talla</strong> en la propuesta de pedido al proveedor.",
      "<strong>Equivalencia entre marcas</strong>, porque el 24 de una no es el 24 de otra."]),
    ("Ancho, horma y el calzado respetuoso",
     ["Una parte creciente de la clientela viene buscando suela flexible, puntera ancha y cero de drop, y pregunta por eso antes que por el color. Si la horma y el ancho no están en la ficha, el dependiente tiene que saberse el catálogo de memoria.",
      "Lo mismo con el pie que necesita plantilla o el que viene con una indicación del podólogo. Anotar en la ficha del niño lo que le sirve evita repetir la prueba entera en cada visita, y ese detalle es lo que se recuerda."],
     ["<strong>Horma, ancho y flexibilidad</strong> como atributos filtrables.",
      "<strong>Marca de calzado respetuoso</strong> para poder ofrecer solo esa selección.",
      "<strong>Nota en la ficha del niño</strong> con lo que le va y lo que le ha rozado.",
      "<strong>Compatibilidad con plantilla</strong> señalada en el artículo."]),
    ("Septiembre, y la venta que se reserva antes de tenerla",
     ["La vuelta al cole concentra en tres semanas una parte del año, con colas y con la talla justa agotándose el primer sábado. Poder reservar un par que todavía está en el pedido del proveedor, con su señal, es lo que evita que la venta se vaya a la tienda de al lado.",
      "Y conviene tener a mano las ventas del septiembre anterior por talla, no por modelo, porque lo que se agota es siempre lo mismo y siempre se pide corto."]),
  ],
  faqs=[
    ("¿Puedo guardar el número que gasta cada niño?",
     "Sí. La ficha de la familia admite varios niños, cada uno con su número, su medida en milímetros y su horma, además del histórico de lo que se ha llevado y cuándo."),
    ("¿Me avisa de cuándo toca cambiar de número?",
     "Puedes sacar el listado de niños cuya última compra pasa de los meses que fijes, que es la base de un aviso de temporada. Es la venta más fácil de esta tienda y la que se pierde por no llevar la cuenta."),
    ("¿Cómo controlo la curva de tallas del 18 al 39?",
     "Cada talla es una variante del modelo y el color, con su stock y sus ventas. Ves dónde se han agotado las tallas centrales de cada tramo de edad, que son las que hacen la caja."),
    ("Trabajo calzado respetuoso. ¿Puedo filtrar por horma ancha?",
     "Sí, si la horma, el ancho y la flexibilidad están dados de alta como atributos. Puedes enseñar solo esa selección, que es lo que pide esa clientela nada más entrar."),
    ("¿Puedo reservar un par que todavía no ha llegado?",
     "Sí, con reserva sobre el pedido pendiente y su señal. Al recibir la mercancía el par queda apartado a nombre del cliente y se avisa, en lugar de venderse a quien entre primero."),
    ("¿Sirve para saber qué pedir para la vuelta al cole?",
     "Sí. Las ventas del mismo periodo del año anterior desglosadas por talla te dicen dónde te quedaste corto, que es información distinta de las ventas por modelo."),
  ],
  rel=[("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Cómo hacer una devolución o cambio en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Cómo abrir una zapatería","/abrir-zapateria.asp"),
       ("TPV para tiendas de puericultura","/negocio_puericultura.asp"),
       ("TPV para tiendas de moda infantil","/negocio_infantil.asp")]),

# =============================================================== MODELISMO
"negocio_modelismo.asp": dict(
  nombre="Tiendas de modelismo, maquetas y radiocontrol",
  crumb="Modelismo",
  icono="fa-helicopter",
  title="Software TPV para Tiendas de Modelismo y Maquetas",
  desc="TPV para modelismo: pinturas por código de color, escalas como atributo, recambios de radiocontrol, encargos de importación y baterías con su control.",
  kw="tpv tienda modelismo, software tienda maquetas, tpv radiocontrol, programa tienda hobby, gestion tienda modelismo",
  h1='Software TPV para Tiendas de Modelismo. <span>Cuatro mil referencias y trescientas son botes de pintura.</span>',
  sub='El cliente entra pidiendo el 70.950 de una marca concreta y una escala 1:35. Aquí el catálogo no se navega: se busca por código, y el que no lo tenga bien montado pierde la venta.',
  bloques=[
    ("La pintura se pide por código, no por nombre",
     ["Trescientos botes en una pared, cada uno con su código de fabricante, y un cliente que trae apuntado el que le falta. La búsqueda por código de color es la operación más repetida del día en esta tienda.",
      "Y son artículos de importe pequeño con reposición constante, así que el hueco en el expositor se ve enseguida. Un stock mínimo por referencia es lo que evita que el cliente se lleve cuatro botes y no el quinto."],
     ["<strong>Código de fabricante como clave de búsqueda</strong>, además del código propio.",
      "<strong>Gama y acabado</strong>: mate, satinado, metalizado, imprimación, lavado y pigmento.",
      "<strong>Stock mínimo por referencia</strong> con propuesta de pedido automática.",
      "<strong>Equivalencias entre marcas de pintura</strong>, que es la pregunta cuando falta un color."]),
    ("La escala organiza la tienda y el catálogo",
     ["Un cliente de aviación en 1:72 y otro de blindados en 1:35 no comparten casi nada. La escala es lo primero por lo que se pregunta y lo que ordena tanto la estantería como el fichero.",
      "Con la escala y la temática como atributos puedes contestar en el momento qué tienes de barcos en 1:350, en lugar de recorrer el expositor con el cliente detrás."],
     ["<strong>Escala como atributo filtrable</strong>, no como parte del nombre.",
      "<strong>Temática</strong>: aviación, blindados, naval, civil, figuras, ciencia ficción.",
      "<strong>Marca y referencia del kit</strong>, que es como lo pide quien ya sabe lo que busca.",
      "<strong>Nivel de dificultad</strong>, útil para el regalo y para el que empieza."]),
    ("El radiocontrol es recambio, y el recambio es compatibilidad",
     ["Quien vuela o rueda rompe. La segunda venta de esta tienda son piñones, servos, hélices, diferenciales y carrocerías, y lo que decide si vendes es saber qué recambio encaja en qué modelo.",
      "Además están las baterías, que se guardan y se transportan con cuidado y conviene tener controladas por lote y por fecha de entrada, porque no envejecen bien en un cajón."],
     ["<strong>Compatibilidad recambio-modelo</strong> guardada en la ficha del artículo.",
      "<strong>Despiece por modelo</strong> para localizar la pieza sin catálogo de papel.",
      "<strong>Control de entrada de baterías</strong> por lote y fecha, para rotar el stock antiguo primero.",
      "<strong>Servicio de montaje y reparación</strong> como línea con su precio."]),
    ("Lo que hay que traer por encargo",
     ["Buena parte del género viene de fuera y no se tiene en tienda: el kit descatalogado, la referencia que solo trae un distribuidor, el pedido de un cliente que espera seis semanas. Ese encargo necesita quedar registrado con su señal y su estado, o se olvida.",
      "Y conviene enlazar el encargo con el pedido de compra que lo cubre, para poder contestar cuando el cliente llama a la tercera semana preguntando por su maqueta."]),
  ],
  faqs=[
    ("¿Puedo buscar pinturas por el código del fabricante?",
     "Sí. Además del código propio, la ficha guarda la referencia del fabricante, que es por la que pregunta el cliente. La búsqueda funciona con cualquiera de las dos."),
    ("¿Se pueden filtrar los kits por escala?",
     "Sí, si la escala está dada de alta como atributo y no dentro del nombre. Se combina con la temática, de forma que puedes contestar al momento qué tienes de naval en 1:350."),
    ("¿Cómo sé qué recambio vale para cada modelo de radiocontrol?",
     "Guardando la compatibilidad en la ficha del recambio. Puedes ver el despiece de un modelo y localizar la pieza sin recurrir al catálogo de papel del fabricante."),
    ("Trabajo con muchos encargos que tardan semanas. ¿Los controla?",
     "Sí. El encargo queda registrado con el cliente, la señal, la fecha prevista y su estado, enlazado con el pedido de compra que lo cubre. Tienes la lista de lo pendiente y qué contestar cuando llaman."),
    ("¿Puedo evitar quedarme sin los colores que más salen?",
     "Con stock mínimo por referencia. El programa saca la propuesta de pedido con lo que ha bajado del mínimo, agrupada por proveedor, para que salga en un solo pedido."),
    ("¿Puedo llevar las baterías con control de fecha?",
     "Sí, dando de alta el artículo con lote y fecha de entrada, y sacando primero el stock más antiguo. En un artículo que envejece en la estantería es lo que evita quedarse con fondo sin salida."),
  ],
  rel=[("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("TPV para tiendas de cómics y manga","/negocio_comics.asp"),
       ("TPV para tiendas de bellas artes","/negocio_bellas_artes.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# =============================================================== SOMBREROS
"negocio_sombreros.asp": dict(
  nombre="Sombrererías, tocados y accesorios de cabeza",
  crumb="Sombrererías",
  icono="fa-hat-cowboy",
  title="Software TPV para Sombrererías y Tocados",
  desc="TPV para sombrererías: talla de cabeza en centímetros, ajuste y arreglo en taller, tocados por encargo con pruebas y la temporada de bodas y feria.",
  kw="tpv sombrereria, software tienda sombreros, tpv tocados, programa tienda complementos cabeza, gestion sombrereria",
  h1='Software TPV para Sombrererías. <span>La talla se mide en centímetros de contorno, no en pequeña y grande.</span>',
  sub='Un sombrero de fieltro se ajusta en el taller, un tocado de boda se hace por encargo con dos pruebas y la feria de abril concentra en seis semanas lo que otros meses no dan.',
  bloques=[
    ("Contorno de cabeza, horma y ajuste",
     ["La talla de un sombrero es el contorno en centímetros, y entre un 57 y un 58 hay una venta que se cierra o no se cierra. El cliente rara vez la sabe, así que se mide en la tienda y conviene guardarla.",
      "Después está el ajuste, que es trabajo de taller: se ensancha con horma, se mete badana o se recorta el ala. Eso es un servicio con su precio y su tiempo, y en muchas sombrererías no se cobra por no tenerlo dado de alta."],
     ["<strong>Talla en centímetros de contorno</strong> como variante del modelo, con su stock.",
      "<strong>Contorno guardado en la ficha del cliente</strong>, para la siguiente visita y para el encargo.",
      "<strong>Ajuste y arreglo como servicios</strong> con precio propio dentro de la venta.",
      "<strong>Material y ala</strong> como atributos: fieltro, paja, panamá, con su medida de ala."]),
    ("El tocado por encargo: dos pruebas y una fecha que no se mueve",
     ["Un tocado para una boda se hace a medida, con su color de conjunto, su boceto y una fecha que es la del enlace. Entre el encargo y la entrega hay una señal, a veces una prueba y siempre una llamada.",
      "Lo que hace falta es una ficha de encargo con la fecha del evento delante, porque el resto de plazos se pueden negociar y ese no."],
     ["<strong>Encargo con fecha del evento</strong> y estado del trabajo hasta la entrega.",
      "<strong>Señal registrada</strong> y descontada al liquidar.",
      "<strong>Notas y referencia del conjunto</strong>: color, tejido y foto del vestido.",
      "<strong>Agenda de pruebas</strong> con aviso de las entregas de la semana."]),
    ("Bodas, feria y romería concentran el año",
     ["Entre marzo y junio se junta la temporada de bodas con la de feria, y ahí la tienda vende tocados, peinetas, sombreros de ala ancha y complementos que el resto del año apenas se mueven. Lo que sobra en julio se queda un año entero.",
      "Comparar la campaña con la del año anterior por modelo y por color, y no por familia, es lo que permite pedir con criterio a un proveedor que trabaja con series cortas."],
     ["<strong>Ventas por modelo y color entre dos temporadas.</strong>",
      "<strong>Stock muerto</strong> con los que llevan dos campañas sin salir.",
      "<strong>Precios de campaña</strong> con fecha de fin, aplicados por familia.",
      "<strong>Reserva de pieza única</strong> para la clienta que vuelve con el vestido."]),
    ("Piezas únicas y el sombrero de armario",
     ["En este oficio conviven la serie corta y la pieza única, a veces hecha a mano en el propio taller. La pieza única es stock uno con su ficha y su fotografía, y no se gestiona como una referencia con reposición.",
      "Y queda el servicio de limpieza y reforma del sombrero de toda la vida, que llega con su resguardo, su estado de entrada y su fecha de recogida. Cobrarlo como línea propia es lo que te dice al cabo del año cuánto vale de verdad tener taller."]),
  ],
  faqs=[
    ("¿Puedo llevar las tallas por contorno de cabeza?",
     "Sí. La talla en centímetros es una variante del modelo con su stock propio, de forma que ves de un vistazo qué contornos te quedan de cada sombrero."),
    ("¿Se puede guardar la talla del cliente para la próxima vez?",
     "Sí, en su ficha, junto con lo que se ha llevado. Es lo que evita volver a medir y lo que permite avisarle cuando entra algo de su contorno."),
    ("¿Puedo cobrar el ajuste de talla como servicio?",
     "Sí, como línea de servicio con su precio dentro de la misma venta. Al quedar facturado sabes al final del año cuánto ha aportado el taller, que suele ser más de lo que parece."),
    ("Hago tocados por encargo para bodas. ¿Cómo los controlo?",
     "Con una ficha de encargo que lleva la fecha del evento, la señal, las notas del conjunto y el estado del trabajo. La agenda te enseña las entregas de la semana, que en temporada es lo que hay que tener delante."),
    ("Tengo piezas únicas hechas a mano. ¿Se pueden llevar?",
     "Sí, como artículo con stock uno, su ficha y su fotografía. Al venderse desaparece del disponible, sin tratarlo como una referencia con reposición."),
    ("¿Puedo comparar la campaña de feria con la del año pasado?",
     "Sí, con ventas por modelo y color entre dos periodos, más el listado de lo que lleva dos campañas sin moverse. Es lo que hace falta delante cuando el proveedor de serie corta te pasa la colección."),
  ],
  rel=[("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Cambiar precios en masa","/cambiar-precios-masivamente-tpv.asp"),
       ("TPV para tiendas de moda flamenca","/negocio_flamenca.asp"),
       ("TPV para tiendas de complementos","/negocio_complementos.asp"),
       ("TPV para tiendas de trajes de comunión","/negocio_comunion.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ================================================================== HIPICA
"negocio_hipica.asp": dict(
  nombre="Tiendas de hípica y equitación",
  crumb="Hípica",
  icono="fa-horse",
  title="Software TPV para Tiendas de Hípica y Equitación",
  desc="TPV para tiendas de hípica: medidas del caballo y tallas del jinete, pienso por saco y a peso, cuentas de cuadra a fin de mes y encargos de concurso.",
  kw="tpv tienda hipica, software tienda equitacion, tpv material ecuestre, programa tienda caballos, tpv pienso caballos",
  h1='Software TPV para Tiendas de Hípica. <span>Media tienda viste al jinete y la otra media al caballo.</span>',
  sub='Una cabezada se pide por tamaño de caballo, una silla por medida de fuste y una chaqueta de concurso por talla de persona. Y el pienso se vende en sacos de veinte kilos a cuadras que pagan a fin de mes.',
  bloques=[
    ("Dos sistemas de tallas que no se parecen en nada",
     ["El artículo de jinete va por tallas de ropa y calzado, con su curva. El de caballo va por medidas propias: cob, full, pony para la cabezada; centímetros de manta según la alzada; pulgadas de fuste en la silla.",
      "Meterlos en el mismo esquema de tallas hace que ninguno de los dos funcione. Son dos catálogos con reglas distintas conviviendo en la misma tienda."],
     ["<strong>Tallas de jinete</strong> con su curva por modelo y color.",
      "<strong>Medidas de caballo</strong> como atributo propio: cob, full, pony y centímetros de manta.",
      "<strong>Medida de fuste y de asiento</strong> en la silla, que es lo que decide la venta.",
      "<strong>Filtro por disciplina</strong>: doma, salto, raid o vaquera, que cambia el material entero."]),
    ("El pienso y el forraje se venden por peso y por saco",
     ["El saco de veinte kilos es una unidad de venta, pero también se vende a granel y se compra por palés. Eso obliga a que el artículo tenga unidad de compra, unidad de venta y su conversión, o el stock miente desde la primera entrega.",
      "Además el pienso caduca y se compra por lotes, así que conviene sacar primero lo más antiguo y saber qué lote se sirvió a qué cuadra si el fabricante avisa de algo."],
     ["<strong>Compra por palé y venta por saco</strong> con su factor de conversión.",
      "<strong>Venta a peso</strong> conectando la balanza para el granel.",
      "<strong>Lote y caducidad</strong> en la entrada, rotando primero el más antiguo.",
      "<strong>Entrega a domicilio</strong> como línea de servicio con su porte."]),
    ("La cuadra es un cliente profesional, no un mostrador",
     ["Los centros hípicos, los picaderos y los profesionales no pagan pieza a pieza. Retiran material y pienso durante el mes y liquidan a fin de mes con una factura que agrupa todos los albaranes, a menudo con su propia tarifa.",
      "Llevar eso en albaranes de papel es donde se pierde el dinero de este sector, porque un albarán traspapelado no se factura nunca."],
     ["<strong>Albarán en vez de ticket</strong> para el cliente con cuenta abierta.",
      "<strong>Factura mensual agrupada</strong> con todos los albaranes del periodo.",
      "<strong>Tarifa por cliente</strong>, distinta de la de mostrador y por familia.",
      "<strong>Riesgo por cliente</strong> con saldo pendiente y aviso al pasar del límite."]),
    ("Concursos, temporada y el material que se encarga",
     ["El calendario de concursos marca los picos, y hay material que se pide para una fecha concreta: la chaqueta de competición, el casco homologado que hay que traer en la talla justa. El encargo con su señal y su fecha es lo que evita que el cliente compre por internet.",
      "Y la tienda de hípica suele estar lejos de su clientela, así que una parte del trabajo es servir pedidos a distancia. Que el albarán, el porte y el cobro salgan del mismo sitio ahorra media mañana a la semana."]),
  ],
  faqs=[
    ("¿Puedo llevar a la vez tallas de jinete y medidas de caballo?",
     "Sí. Son dos esquemas distintos conviviendo en el catálogo: la ropa y el calzado del jinete con su curva de tallas, y el material del caballo con sus medidas propias, cob, full, pony o centímetros de manta."),
    ("Vendo pienso en sacos y también a granel. ¿Cuadra el stock?",
     "Sí, dando de alta el artículo con unidad de compra y unidad de venta distintas y su conversión. Compras por palé, vendes por saco o a peso con la balanza conectada, y el stock baja en la proporción correcta."),
    ("¿Puedo controlar el lote y la caducidad del pienso?",
     "Sí. El lote y la fecha se registran en la entrada, el programa saca primero el más antiguo y puedes saber qué lote se sirvió a cada cuadra si hace falta avisar."),
    ("Los centros hípicos me pagan a fin de mes. ¿Se puede llevar?",
     "Sí, con cuenta de cliente. Se emite albarán en lugar de ticket y a fin de mes se genera una factura que agrupa todos los del periodo, con la tarifa propia de ese cliente y un límite de riesgo que avisa al superarse."),
    ("¿Puedo registrar encargos para una fecha de concurso?",
     "Sí, con su señal, la fecha comprometida y el estado del pedido al proveedor. Tienes la lista de lo que tiene que estar antes de cada fin de semana de competición."),
    ("Sirvo pedidos a clientes que están lejos. ¿Lo contempla?",
     "Sí. El albarán, el porte como línea de servicio y el cobro salen de la misma venta, con lo que el pedido a distancia se documenta igual que la venta de mostrador."),
  ],
  rel=[("Cuentas de cliente y cobro a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("TPV para tiendas de mascotas y piensos","/negocio_petshop.asp"),
       ("TPV para tiendas de montaña y outdoor","/negocio_montana.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ================================================================ COMUNION
"negocio_comunion.asp": dict(
  nombre="Tiendas de trajes de comunión, bautizo y arras",
  crumb="Comunión",
  icono="fa-child-dress",
  title="TPV para Tiendas de Comunión y Bautizo | Caja 5",
  desc="TPV para trajes de comunión: reserva por colegio para que el modelo no se repita, pruebas y arreglos, pagos a plazos y una campaña de cinco meses.",
  kw="tpv tienda comunion, software trajes comunion, tpv tienda bautizo, programa tienda ceremonia infantil, gestion tienda comunion",
  h1='Software TPV para Tiendas de Comunión. <span>El año entero se decide entre enero y mayo.</span>',
  sub='Una comunión se reserva en enero, se prueba en marzo y se entrega en abril, pagada en tres veces. Y hay una regla que ningún programa genérico contempla: dos niños del mismo colegio no pueden llevar el mismo traje.',
  bloques=[
    ("La reserva por colegio y fecha, que es la regla del oficio",
     ["Las madres preguntan lo mismo en enero: si ese modelo se lo ha llevado alguien del colegio de su hija y de qué fecha es la ceremonia. Vender el mismo vestido a dos niñas de la misma parroquia es el error que te cuesta la clienta y la recomendación.",
      "Eso se resuelve guardando en la reserva el colegio y la fecha de la ceremonia, de forma que al ir a comprometer un modelo se pueda comprobar antes de decir que sí."],
     ["<strong>Colegio y fecha de ceremonia</strong> en la ficha de la reserva.",
      "<strong>Consulta de modelo comprometido</strong> por colegio antes de cerrar la venta.",
      "<strong>Reserva del modelo y la talla</strong> retirada del disponible.",
      "<strong>Listado por fecha de ceremonia</strong> para ordenar las entregas de abril y mayo."]),
    ("Pruebas, arreglos y una fecha que no admite retraso",
     ["Entre la reserva y la entrega hay una o dos pruebas y casi siempre un arreglo: bajo, mangas, ancho de talle. Es trabajo de taller con su coste, hecho por una modista que puede ser externa, y que hay que tener terminado para una fecha que no se mueve.",
      "El calendario de entregas por fecha de ceremonia es la herramienta central de esta tienda entre marzo y mayo."],
     ["<strong>Agenda de pruebas</strong> con la cita y lo que queda por ajustar.",
      "<strong>Arreglo como línea de servicio</strong>, propio o de modista externa con su coste.",
      "<strong>Estado del encargo</strong>: reservado, recibido, probado, en arreglo, listo y entregado.",
      "<strong>Aviso de las entregas de la semana</strong> ordenadas por fecha de ceremonia."]),
    ("Se paga en tres veces y a lo largo de cuatro meses",
     ["La señal se deja en enero, hay una entrega a cuenta en la prueba y el resto se liquida al recoger. Ese dinero entra en la caja de tres días distintos y la venta se cierra en el tercero.",
      "Si no queda registrado por encargo, en mayo nadie sabe qué se ha cobrado de cada uno, que es justo cuando hay cuarenta entregas en tres semanas."],
     ["<strong>Entregas a cuenta sucesivas</strong>, cada una en la caja del día en que se cobra.",
      "<strong>Pendiente por encargo</strong> a la vista en cualquier momento.",
      "<strong>Liquidación al recoger</strong> descontando todo lo entregado.",
      "<strong>Listado de reservas con señal sin recoger</strong> según se acerca la fecha."]),
    ("El complemento vende tanto como el traje",
     ["Zapatos, limosnera, corona, guantes, arras, cojín y el ramo se llevan casi siempre con el traje, y a menudo se ofrecen como conjunto con un precio cerrado. Montarlo como pack con su escandallo hace que al venderlo baje el stock de cada pieza y sepas qué margen te deja el conjunto.",
      "Y queda el bautizo, que reparte algo de trabajo por el resto del año con la misma forma de trabajar: encargo, talla, fecha y arreglo."]),
  ],
  faqs=[
    ("¿Puedo saber si un modelo ya está comprometido en un colegio?",
     "Sí, si la reserva guarda el colegio y la fecha de la ceremonia. Antes de comprometer un modelo se consulta, que es lo que evita que dos niños de la misma parroquia lleven el mismo traje."),
    ("¿Cómo llevo las pruebas y los arreglos?",
     "Con la agenda de pruebas y el arreglo dado de alta como servicio dentro del encargo, con su coste, sea del taller propio o de una modista externa. El encargo pasa por sus estados hasta la entrega."),
    ("El pago se hace en tres veces. ¿Queda registrado?",
     "Sí. Cada entrega a cuenta entra en la caja del día en que se cobra y queda asociada al encargo, de forma que ves en todo momento lo entregado y lo pendiente de cada uno."),
    ("¿Puedo ordenar las entregas por fecha de comunión?",
     "Sí, y es la vista que hace falta entre marzo y mayo. El listado sale por fecha de ceremonia con el estado de cada encargo, para saber qué tiene que estar listo esta semana."),
    ("Vendo el traje con los complementos como conjunto. ¿Se puede?",
     "Sí, como pack con escandallo. Al venderlo bajan del stock los zapatos, la limosnera y el resto de piezas por separado, y sabes qué te cuesta el conjunto en material."),
    ("¿Me avisa de las reservas con señal que nadie ha recogido?",
     "Sí, con el listado de encargos pendientes de recoger ordenado por fecha. Es con el que se hacen las llamadas de las últimas semanas de campaña."),
  ],
  rel=[("Cómo hacer una devolución o cambio en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("TPV para tiendas de moda infantil","/negocio_infantil.asp"),
       ("TPV para sombrererías y tocados","/negocio_sombreros.asp"),
       ("TPV para tiendas de moda flamenca","/negocio_flamenca.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp")]),

# =========================================================== SUPLEMENTACION
"negocio_suplementacion.asp": dict(
  nombre="Tiendas de nutrición deportiva y suplementación",
  crumb="Nutrición deportiva",
  icono="fa-dumbbell",
  title="TPV para Tiendas de Nutrición Deportiva | Caja 5",
  desc="TPV para tiendas de suplementación: lote y caducidad de cada bote, sabor y formato como variantes, cliente que repite cada mes y promociones con fecha.",
  kw="tpv tienda suplementos, software nutricion deportiva, tpv tienda proteinas, programa tienda suplementacion, control lotes suplementos",
  h1='Software TPV para Tiendas de Nutrición Deportiva. <span>El mismo producto en cuatro sabores y tres tamaños.</span>',
  sub='Una proteína es una referencia con doce combinaciones de sabor y formato, un lote, una caducidad y un cliente que vuelve el mismo día de cada mes. Eso son cuatro cosas que controlar, no una.',
  bloques=[
    ("Sabor y formato son variantes, no artículos sueltos",
     ["El bote de dos kilos de chocolate y el de quinientos gramos de vainilla son el mismo producto en dos presentaciones. Darlos de alta como artículos sin relación hace imposible saber qué se vende de ese producto y cuál es el sabor que sobra siempre.",
      "Con sabor y formato como variantes ves el conjunto y el detalle a la vez, que es lo que necesitas para pedirle al proveedor la proporción correcta."],
     ["<strong>Sabor y formato como variantes</strong> del mismo producto, cada una con su stock.",
      "<strong>Ventas agregadas por producto</strong> y desglosadas por variante.",
      "<strong>Precio por unidad y por kilo</strong>, que es como compara el cliente informado.",
      "<strong>Marca y familia</strong>: proteína, creatina, aminoácidos, pre-entreno, vitaminas."]),
    ("Lote y caducidad en un producto que se consume",
     ["Los complementos alimenticios llevan lote y fecha de consumo preferente, y en una tienda con doscientas referencias el fondo de estantería caduca sin que nadie se dé cuenta hasta que un cliente lo ve.",
      "Registrar el lote en la entrada y sacar primero el más antiguo resuelve el problema del día a día, y deja además la trazabilidad si el fabricante retira una partida."],
     ["<strong>Lote y fecha en la entrada de mercancía.</strong>",
      "<strong>Aviso de caducidades próximas</strong> con margen para darles salida.",
      "<strong>Rotación del lote más antiguo primero.</strong>",
      "<strong>Trazabilidad de la venta por lote</strong> si hay que avisar de una retirada."]),
    ("Un cliente que vuelve cada mes",
     ["La suplementación es consumo recurrente: el mismo bote, el mismo sabor, cada cuatro o cinco semanas. Saber quién compra qué y cada cuánto convierte esta tienda en una de recurrencia alta, que se gestiona distinto de una de compra ocasional.",
      "Con el histórico por cliente se puede avisar cuando llega su marca, tener preparado su sabor y saber a quién has dejado de ver, que es información que en una tienda de barrio vale dinero."],
     ["<strong>Ficha de cliente con su histórico</strong> de producto, sabor y formato.",
      "<strong>Clientes que llevan tiempo sin volver</strong>, listados para poder recuperarlos.",
      "<strong>Reserva de producto</strong> para el cliente que viene a por él el día 1.",
      "<strong>Tarjeta de fidelización o saldo acumulado</strong>, que en recurrencia alta rinde."]),
    ("Promociones, packs y lo que se puede decir del producto",
     ["Este sector vive de promociones con fecha: el dos por uno del proveedor, el pack de proteína con shaker, el descuento de temporada. Conviene que la promoción tenga fecha de fin en el programa y no se quede aplicada tres meses de más, que es el error clásico.",
      "Y una advertencia que no es de software: la información que acompaña a un complemento alimenticio está regulada y no se le pueden atribuir propiedades de prevención o curación de enfermedades. Lo que escribas en la ficha, en la etiqueta del lineal o en el cartel del escaparate conviene contrastarlo con la normativa aplicable y con tu asesor."]),
  ],
  faqs=[
    ("Tengo el mismo producto en cuatro sabores y tres tamaños. ¿Cómo se lleva?",
     "Como un producto con sabor y formato de variantes, cada una con su stock y sus ventas. Ves lo que se vende del producto en conjunto y qué sabor es el que se queda siempre en la estantería."),
    ("¿Puedo controlar la caducidad de los botes?",
     "Sí. El lote y la fecha se registran al recibir la mercancía, el programa avisa de las caducidades próximas con margen para darles salida y saca primero el lote más antiguo."),
    ("Si el fabricante retira un lote, ¿sé a quién se lo he vendido?",
     "Sí, si la venta quedó asociada al lote. Recuperas las ventas de esa partida con su cliente y su fecha."),
    ("¿Puedo saber qué compra cada cliente habitual?",
     "Sí, con la ficha de cliente y su histórico. En una tienda de recurrencia alta sirve para tener preparado su sabor, avisarle cuando llega su marca y detectar a quién has dejado de ver."),
    ("¿Las promociones se pueden programar con fecha de fin?",
     "Sí, con fecha de inicio y de fin por artículo o por familia. Es lo que evita el descuento que se queda aplicado meses después de que el proveedor lo haya retirado."),
    ("¿Puedo montar packs de producto más accesorio?",
     "Sí, como artículo con escandallo. Al venderlo bajan del stock el bote y el accesorio por separado, y el pack puede tener un precio distinto de la suma."),
  ],
  rel=[("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("Cambiar precios en masa","/cambiar-precios-masivamente-tpv.asp"),
       ("TPV para parafarmacias","/negocio_parafarmacia.asp"),
       ("TPV para tiendas de montaña y outdoor","/negocio_montana.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ============================================================= ENMARCACION
"negocio_enmarcacion.asp": dict(
  nombre="Tiendas de cuadros y enmarcación a medida",
  crumb="Enmarcación",
  icono="fa-image",
  title="Software TPV para Enmarcación y Tiendas de Cuadros",
  desc="TPV para tiendas de enmarcación: presupuesto por metro de moldura y paspartú, resguardo de la obra del cliente y taller con fecha de recogida.",
  kw="tpv enmarcacion, software tienda cuadros, programa marcos a medida, tpv taller enmarcado, gestion tienda enmarcacion",
  h1='Software TPV para Tiendas de Enmarcación. <span>Cada trabajo es un presupuesto distinto y una obra que no es tuya.</span>',
  sub='Entra alguien con la lámina de su abuela, se elige moldura y paspartú, se calcula por metro lineal y se recoge en diez días. Mientras tanto la obra está en tu taller bajo tu responsabilidad.',
  bloques=[
    ("El presupuesto se calcula por metro lineal y por superficie",
     ["Un marco se cobra por los metros lineales de moldura que consume, más el cristal y el trasero por superficie, más el paspartú con su ventana, más la mano de obra. Cambiar la moldura cambia el precio entero.",
      "Hacer ese cálculo a mano delante del cliente es lento y sale mal. Con la medida de la obra y la referencia de la moldura el importe debería salir solo, incluido el desperdicio del corte a inglete."],
     ["<strong>Cálculo por medidas de la obra</strong>: metros lineales de moldura y superficie de cristal y trasero.",
      "<strong>Precio por metro de cada moldura</strong>, tomado de su ficha.",
      "<strong>Paspartú con su ventana</strong> y su color como línea propia.",
      "<strong>Mano de obra y montaje</strong>, para que el trabajo del taller no se regale."]),
    ("La obra del cliente no es stock, pero está en tu casa",
     ["El óleo, el título universitario, la camiseta firmada o la foto de la boda son de otro, tienen valor sentimental y a veces económico, y están en tu taller diez días. Ese es el riesgo real de este oficio.",
      "El resguardo lo cubre: qué se ha dejado, en qué estado, qué se ha encargado, cuánto cuesta y cuándo se recoge. Con una copia para el cliente y su número."],
     ["<strong>Resguardo numerado</strong> con la descripción de la obra y su estado de entrada.",
      "<strong>Fotografía de la obra</strong> adjunta al encargo.",
      "<strong>Fecha comprometida de recogida</strong> y aviso cuando está lista.",
      "<strong>Listado de obras en taller</strong> con su antigüedad, para que nada se quede dos años."]),
    ("Moldura por barras, y lo que sobra de cada corte",
     ["La moldura se compra en barras de tres metros y se consume en trozos. Un marco de 40 por 50 gasta 1,80 metros, y del resto de la barra queda un retal que a veces sirve para el siguiente trabajo y a veces no.",
      "Controlar el consumo por metros es lo que te dice de verdad qué molduras rotan y cuáles llevan dos años en el expositor ocupando pared."],
     ["<strong>Compra por barra y consumo por metros</strong> con su conversión.",
      "<strong>Consumo real por trabajo</strong>, incluido el desperdicio del inglete.",
      "<strong>Rotación por referencia de moldura</strong>, para retirar del muestrario lo que no sale.",
      "<strong>Muestrario</strong> con la referencia del proveedor a la vista."]),
    ("Señal, plazo y el cuadro que nadie recoge",
     ["Casi todos los talleres cobran una señal al encargar, y el resto al recoger. Eso reparte la venta en dos días distintos y conviene que quede asociado al resguardo, no anotado aparte.",
      "Después está el problema de siempre: los cuadros que llevan meses hechos y sin recoger. Un listado por antigüedad con el teléfono del cliente delante resuelve en una tarde lo que de otra forma acaba apilado detrás de la puerta."]),
  ],
  faqs=[
    ("¿Calcula el precio del marco por las medidas de la obra?",
     "Sí. Con el alto y el ancho y la referencia de la moldura sale el importe: los metros lineales que consume, el cristal y el trasero por superficie, el paspartú y la mano de obra, contando el desperdicio del corte."),
    ("¿Puedo dejar constancia de la obra que me deja el cliente?",
     "Sí, con un resguardo numerado que recoge la descripción, el estado de entrada, una fotografía y la fecha comprometida de recogida, con copia para el cliente."),
    ("¿Cómo controlo lo que tengo en el taller?",
     "Con el listado de encargos en curso y su estado, ordenado por antigüedad. Ves lo que tiene que estar esta semana y lo que lleva demasiado tiempo sin recogerse."),
    ("Compro la moldura en barras. ¿Puedo saber lo que consumo?",
     "Sí, dando de alta la moldura con compra por barra y consumo por metros. Cada trabajo descuenta los metros que gasta, con lo que ves qué referencias rotan de verdad y cuáles llevan años en el muestrario."),
    ("Cobro una señal al encargar. ¿Se registra?",
     "Sí, asociada al resguardo. Entra en la caja del día en que se cobra y se descuenta del importe pendiente cuando el cliente recoge."),
    ("¿Puedo sacar la lista de cuadros sin recoger?",
     "Sí, por antigüedad y con el teléfono del cliente. Es lo que evita que los trabajos terminados se acumulen detrás de la puerta durante meses."),
  ],
  rel=[("Cuentas de cliente y cobro a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("Gestión de proveedores y pedidos","/gestion-de-proveedores-y-pedidos.asp"),
       ("TPV para tiendas de bellas artes","/negocio_bellas_artes.asp"),
       ("TPV para tiendas de decoración","/negocio_decoracion.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

}
