# -*- coding: utf-8 -*-
"""Blog de carrito5.com: octubre de 2026.

Halloween, la decision sobre el Black Friday, el etiquetado previo a campaña y
Todos los Santos en la floristeria. Mismas reglas que blog_2026_09.py.
"""

BLOG_2026_10 = {

# ------------------------------------------------------------------ 6 oct
"halloween-tienda-disfraces-tres-semanas": dict(
  title="Halloween 2026 en la Tienda de Disfraces: Tres Semanas",
  desc="Halloween 2026 cae en sábado y la tienda de disfraces se juega el año entre el 10 y el 31 de octubre. Tallas, política de cambios y la cola del viernes 30.",
  kw="halloween tienda disfraces, vender disfraces halloween, tienda disfraces octubre, halloween 2026 comercio, tpv tienda disfraces",
  h1="Halloween 2026: tres semanas para la tienda de disfraces",
  sub="El 31 de octubre de 2026 es sábado. Eso significa fiesta el viernes y el sábado, y una cola el jueves 29 y el viernes 30 que decide si la campaña sale bien o regular.",
  publicado="2026-10-06",
  para="Tiendas de disfraces, fiesta y cosmética",
  resumen=[
    "Halloween 2026 cae en sábado, así que la venta se concentra en la semana del 26 al 31 de octubre, con el pico el jueves 29 y el viernes 30. Una tienda de disfraces vende en esas dos semanas lo que no vende en cinco meses, y las tres cosas que la frenan son las tallas, las devoluciones y la cola.",
      "Las tres se resuelven antes: cada disfraz dado de alta con su matriz de tallas, la política de cambios en un cartel y en el ticket, y todo el género con etiqueta para que la caja sea pasar el lector.",
  ],
  cuerpo=[
    ("Un sábado cambia el calendario",
     ["Cuando Halloween cae entre semana la venta se reparte. Cuando cae en sábado, como en 2026, hay dos noches de fiesta y todo el mundo compra a la vez, el jueves y el viernes. Además, los colegios celebran el viernes 30, así que el disfraz infantil se vende esa misma semana, y el adulto también.",
      "Para la tienda eso significa que el escaparate tiene que estar montado el 10 de octubre, que el género tiene que estar en tienda y etiquetado el 20, y que la última semana no se hace nada más que cobrar."],
     None),
    ("Las tallas: donde se pierde la venta",
     ["Un disfraz de bruja viene en cuatro tallas infantiles y tres de adulto. Con veinte modelos, son ciento cuarenta combinaciones, y la pregunta de cada cliente es la misma: «¿lo tienes en la 8?». Si la respuesta es «voy a mirar», con la tienda llena, se pierde tiempo y a veces la venta.",
      "Con cada disfraz dado de alta como modelo con su matriz de tallas, la respuesta está en pantalla: qué tallas quedan de ese modelo, sin ir al almacén. Y al pedir la reposición de mitad de campaña, se pide por talla, que es lo que se ha agotado, y no por modelo. En Carrito5 la matriz de tallas y colores está en el plan gratuito."],
     ["<strong>Alta por modelo</strong> con sus tallas, no un artículo por talla.",
      "<strong>Consulta en caja</strong> de qué tallas quedan, sin moverse.",
      "<strong>Reposición por talla</strong> el 20 de octubre, con lo que se ha agotado en la primera semana."]),
    ("Los cambios: política escrita antes del primer disfraz",
     ["En disfraces la devolución es un problema propio: el disfraz que se compra el viernes y se devuelve el lunes ya usado. La ley no obliga a aceptar cambios en tienda física salvo defecto, así que la política la fija la tienda, y tiene que estar escrita y visible antes de vender el primero.",
      "Lo habitual y defendible: cambio de talla dentro de 48 horas con etiqueta y sin usar, sin cambios a partir del 29 de octubre, y sin devolución de dinero. Puesto en un cartel junto a la caja y en el pie del ticket. Cuando alguien reclame, la venta está en la ficha del cliente con su fecha y su talla, y el vale, si lo hay, queda registrado."],
     None),
    ("La cola del viernes 30",
     ["La cola es la que decide. Con maquillaje, complementos y disfraces mezclados en la misma compra, un ticket puede tener ocho líneas, y si tres de ellas hay que buscarlas en una lista, la cola se dobla. Todo el género con código de barras, propio o del proveedor, y la caja es pasar el lector ocho veces.",
      "Lo que suele llegar sin código en esta campaña: el maquillaje a granel, los complementos sueltos, las pelucas de proveedor pequeño. Eso se etiqueta el día que llega, con el programa asignando el código e imprimiendo la etiqueta, y se acabó."],
     None),
    ("Y el 1 de noviembre, Carnaval",
     ["Lo que no se vende en Halloween se vende en Carnaval, que en 2027 cae del 6 al 9 de febrero. Entre medias hay Navidad y cotillones. El género que sobre el 31 de octubre se guarda con su código y su stock en el programa, y en enero se saca sin dar de alta nada. Es la ventaja de una tienda que tiene el stock en la caja y no en la cabeza."],
     None),
  ],
  cierre=("Tres semanas dan para instalar un TPV",
          ["Si la tienda de disfraces cobra este Halloween con calculadora, la cola del viernes 30 va a ser larga. Carrito5 se instala en el ordenador que tienes, lee códigos de barras, imprime etiquetas para lo que no los trae y da de alta cada disfraz con sus tallas. Es gratuito hasta 1.000 artículos, y para una tienda de disfraces suele bastar.",
           "Hoy es 6 de octubre. Instalado el 8, con el género dado de alta el 20, cobrando en la semana grande."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué día de la semana es Halloween en 2026?",
     "Sábado, 31 de octubre de 2026. Los colegios lo celebran el viernes 30, y la venta se concentra el jueves 29 y el viernes 30."),
    ("¿Cómo llevo las tallas de los disfraces sin volverme loco?",
     "Dando de alta cada disfraz como un modelo con su matriz de tallas. En caja ves qué tallas quedan y al reponer pides por talla."),
    ("¿Estoy obligado a aceptar un disfraz devuelto?",
     "En tienda física, solo si tiene defecto. Los cambios son una política tuya: escríbela, ponla en un cartel y en el ticket, y aplícala igual a todos."),
    ("¿Qué hago con lo que sobre después de Halloween?",
     "Guardarlo con su código y su stock en el programa para Carnaval, del 6 al 9 de febrero de 2027, y para cotillones. No hay que darlo de alta otra vez."),
    ("¿Da tiempo a poner un TPV antes del 31?",
     "Sí. Carrito5 se instala en unos minutos, y dar de alta veinte modelos con sus tallas es una tarde. El género se etiqueta según llega."),
  ],
  relacionadas=[("Matriz de tallas y colores", "tallas-y-colores.html", "Un disfraz, todas sus tallas"),
                ("TPV para tiendas de cosmética", "tpv-tienda-cosmetica-natural.html", "Maquillaje y granel"),
                ("Calendario comercial 2026-2027", "blog/calendario-comercial-2026-2027-fechas-clave.html", "Carnaval 2027 y el resto"),
                ("Descargar Carrito5", "descargar-tpv-gratis.html", "Antes del 20 de octubre")]),

# ------------------------------------------------------------------ 13 oct
"black-friday-comercio-local-participar-o-no": dict(
  title="Black Friday 2026 en la Tienda de Barrio: Cómo Hacerlo",
  desc="El Black Friday es el 27 de noviembre de 2026. Una tienda pequeña puede no participar, hacer descuento acotado o participar sin descuento. Las tres, con cuentas.",
  kw="black friday comercio local, black friday tienda pequeña, black friday 2026 españa, black friday tienda fisica, participar black friday tienda, black friday comercio barrio",
  h1="Black Friday 2026 en una tienda de barrio: tres formas de hacerlo",
  sub="El 27 de noviembre no es obligatorio. Pero si no decides ahora qué vas a hacer ese día, lo decidirá la tienda de al lado con un cartel del 50 %.",
  publicado="2026-10-13",
  para="Todo el comercio de calle",
  resumen=[
    "El Black Friday de 2026 es el viernes 27 de noviembre, y para una tienda de barrio hay tres opciones válidas: no participar y decirlo, participar con un descuento acotado a lo que interesa liquidar antes de Navidad, o participar sin descuento con otra cosa (un vale para diciembre, un regalo por compra, horario ampliado).",
    "Lo que no funciona es el 20 % sobre todo el catálogo: regala margen sobre lo que se iba a vender igual en Navidad. La decisión se toma a mediados de octubre, porque el cartel, el género y los precios hay que tenerlos listos el 20 de noviembre.",
  ],
  cuerpo=[
    ("Lo que el Black Friday es para una tienda pequeña",
     ["Para la gran superficie y el comercio online el Black Friday es una semana de volumen con márgenes finos. Para una tienda de sesenta metros con una persona en caja es otra cosa: un viernes en que la gente sale a comprar con la cartera abierta y una expectativa de descuento. La pregunta es si la tienda quiere ese tráfico y a qué precio.",
      "Hay una diferencia que juega a favor del comercio local: el cliente de barrio no va a comparar tu precio con veinte pestañas del navegador. Va a entrar porque pasa por delante y hay algo en el escaparate. Eso permite participar sin regalar el margen."],
     None),
    ("Opción uno: no participar, y decirlo",
     ["Es legítimo y cada vez más comercios lo hacen. Lo que no funciona es no participar y no decir nada, porque el cliente entra esperando el descuento y sale decepcionado. Un cartel del tipo «aquí no hacemos Black Friday: el precio justo es el de todo el año» convierte la ausencia en posicionamiento, y a una parte de la clientela le gusta.",
      "Encaja en tiendas con producto de autor, de proximidad o con precio ya ajustado: herboristería, librería, artesanía, alimentación."],
     None),
    ("Opción dos: descuento, pero solo sobre lo que interesa mover",
     ["Si hay descuento, que sea sobre lo que conviene liquidar antes de Navidad: la temporada anterior, las tallas sueltas, las referencias que llevan seis meses sin venderse. Eso se ve en el stock del programa, referencia por referencia. El resto del catálogo, a su precio.",
      "Con el género identificado, se marca con etiqueta nueva la semana anterior. Con un TPV con impresión de etiquetas eso es una tarde: se imprime la etiqueta con el precio del Black Friday para las referencias elegidas y se coloca. El resto no se toca. Y el 28 de noviembre las referencias que hayan sobrado vuelven a su etiqueta o se quedan como saldo, según lo que decidas."],
     ["<strong>Temporada anterior</strong> y tallas sueltas: descuento fuerte, que es lo que las va a mover.",
      "<strong>Referencias sin venta en seis meses</strong>: fuera, al precio que haga falta.",
      "<strong>Lo que se vende solo en Navidad</strong>: ni tocarlo."]),
    ("Opción tres: participar sin descuento",
     ["La que mejor funciona en muchas tiendas de barrio. En vez de bajar el precio, se da algo: un vale de 10 euros para gastar en diciembre por cada compra de 50, un regalo pequeño por compra, horario ampliado el viernes por la tarde, un café. El cliente sale contento, el margen se queda y, con el vale, vuelve en diciembre.",
      "El vale se registra en la ficha del cliente para que en diciembre se localice sin buscar papeles, y para saber cuántos se han emitido y cuántos se han usado."],
     None),
    ("La cuenta que hay que hacer antes de decidir",
     ["Un 20 % de descuento sobre toda la tienda en un día de ventas fuertes puede costar más margen del que aporta el volumen extra. La cuenta rápida: lo que vendiste el último viernes de noviembre del año pasado, multiplicado por el 20 %, es lo que regalas seguro. Lo que ganas es incierto. Si no tienes la cifra del año pasado, este año es para empezar a tenerla."],
     None),
  ],
  cierre=("Decide en octubre, ejecuta en noviembre",
          ["Cualquiera de las tres opciones necesita saber qué hay en la tienda y qué se ha vendido, y las dos con descuento o vale necesitan etiquetas y ficha de cliente. Carrito5 hace las tres cosas y es gratuito hasta 1.000 artículos. Instalado en octubre, el 20 de noviembre tienes el género de Black Friday etiquetado y el resto a su precio."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué día es el Black Friday de 2026?",
     "El viernes 27 de noviembre de 2026. El Cyber Monday es el lunes 30."),
    ("¿Una tienda pequeña tiene que hacer Black Friday?",
     "No. Puede no participar, participar con descuento acotado, o participar sin descuento con vale, regalo u horario. Lo importante es decidirlo y decirlo en el escaparate."),
    ("¿Sobre qué conviene hacer descuento?",
     "Sobre lo que interesa liquidar antes de Navidad: temporada anterior, tallas sueltas y referencias sin venta en meses. Nunca sobre lo que se va a vender igual en diciembre."),
    ("¿Cómo etiqueto solo las referencias del Black Friday?",
     "Imprimiendo etiqueta nueva con el precio de ese día solo para esas referencias, la semana anterior. El resto del catálogo no se toca."),
    ("¿Qué hago con los vales que doy el Black Friday?",
     "Registrarlos en la ficha de cada cliente, con su importe. En diciembre se localizan sin papeles y sabes cuántos se han usado."),
  ],
  relacionadas=[("La Navidad se prepara en septiembre", "blog/campana-navidad-tienda-preparar-en-septiembre.html", "Pedidos y entrada de género"),
                ("Etiquetar antes de la campaña", "blog/etiquetar-genero-antes-de-campana.html", "Códigos y etiquetas paso a paso"),
                ("TPV para comercio local", "software-tpv-comercio-local.html", "Pensado para la tienda de barrio"),
                ("Calendario comercial 2026-2027", "blog/calendario-comercial-2026-2027-fechas-clave.html", "Todas las fechas")]),

# ------------------------------------------------------------------ 20 oct
"etiquetar-genero-antes-de-campana": dict(
  title="Etiquetar el Género antes de la Campaña, sin Colas",
  desc="Cómo dar de alta y etiquetar el género de campaña en una tarde: lo que trae código de barras, lo que no, y que en diciembre cobrar sea solo pasar el lector.",
  kw="etiquetar productos tienda, codigo de barras tienda pequeña, imprimir etiquetas codigo barras, lector codigo barras tpv, etiquetas precio tienda, como poner codigo de barras a mis productos",
  h1="Etiquetar antes de la campaña: que cobrar sea pasar el lector",
  sub="Cada artículo que hay que buscar en una lista en diciembre son treinta segundos de cola. Multiplicado por cada ticket, es la diferencia entre una tienda que fluye y una que se atasca.",
  publicado="2026-10-20",
  para="Todo el comercio con género de campaña",
  resumen=[
    "Etiquetar el género de campaña es una tarde de trabajo en noviembre que evita semanas de cola en diciembre. Lo que trae código de barras del fabricante se da de alta leyéndolo con el lector y poniéndole precio. Lo que no lo trae recibe un código propio del programa y una etiqueta impresa.",
    "Un lector USB cuesta menos de 40 euros y funciona como un teclado. En Carrito5 la lectura, el código propio y la impresión de etiquetas están en el plan gratuito.",
  ],
  cuerpo=[
    ("Dos tipos de género, dos formas de entrarlo",
     ["Casi todo lo que llega de un proveedor grande trae código de barras EAN impreso: juguete, perfumería, electrónica, libro, la mayor parte de la moda de marca. Eso se da de alta en un minuto por referencia: se pasa el código por el lector, el programa crea el artículo con ese código, se escribe el nombre y el precio, y ya se cobra pasándolo.",
      "Lo que no trae código es lo que da trabajo: artesanía, complementos de proveedor pequeño, cosmética a granel, regalo de importación sin etiquetar, la mercería, todo lo que se compra en paquetes y se vende suelto. Para eso el programa asigna un código propio a cada referencia e imprime la etiqueta. Se pega en el artículo o en el estante, y en la caja se pasa por el lector como cualquier otro."],
     None),
    ("El lector: qué comprar y qué no",
     ["Un lector de códigos de barras USB de mano, de los de 30 o 40 euros, funciona como un teclado: se conecta, se apunta al código y el número entra en el programa donde esté el cursor. No necesita instalar nada. Sirve para el 99 % de las tiendas.",
      "No hace falta un lector de mostrador fijo salvo en alimentación con mucho volumen, ni uno inalámbrico salvo que se lea en el almacén. Y no compres una impresora de etiquetas especial sin preguntar: muchas tiendas imprimen etiquetas en hojas adhesivas con la impresora normal, y para una campaña basta."],
     ["<strong>Lector USB de mano</strong>: menos de 40 euros, se conecta y funciona.",
      "<strong>Impresora</strong>: la que tengas, con hojas de etiquetas adhesivas, o una de etiquetas si el volumen lo pide.",
      "<strong>Nada más</strong>: ni software aparte ni licencia del lector."]),
    ("La tarde de etiquetado, paso a paso",
     ['<ol class="c5-pasos">'
      '<li><strong>Abre las cajas por proveedor</strong>, no por tipo de artículo. Así el precio de compra y el margen se aplican de golpe.</li>'
      '<li><strong>Para cada referencia con código</strong>: lector, nombre, precio de venta. Siguiente.</li>'
      '<li><strong>Para cada referencia sin código</strong>: nombre, precio, y el programa asigna el código. Marca cuántas etiquetas necesitas.</li>'
      '<li><strong>En moda</strong>: el modelo con su matriz de tallas y colores, y el stock por variante. Cada variante lleva su código.</li>'
      '<li><strong>Imprime las etiquetas</strong> de todo lo que no traía código, de una vez, y pégalas.</li>'
      '<li><strong>Haz una venta de prueba</strong> con tres artículos: uno con código de fábrica, uno con etiqueta propia y una prenda con talla.</li>'
      '</ol>',
      "Una campaña de doscientas referencias se entra así en una tarde. Lo que no se hace esa tarde se paga en la cola de diciembre, referencia a referencia."],
     None),
    ("Lo que cambia en la caja",
     ["Con todo etiquetado, un ticket de seis artículos son seis pasadas de lector y un cobro. Sin buscar, sin preguntar el precio, sin teclear. Con la tienda llena, es la diferencia entre atender a un cliente cada dos minutos o cada cinco.",
      "Y hay un efecto secundario que se nota en enero: como cada venta descuenta su referencia exacta, el stock del programa dice qué sobra sin recontar, y el pedido de la campaña siguiente sale de ahí."],
     None),
  ],
  cierre=("Un lector, una tarde y un programa gratuito",
          ["Carrito5 lee códigos de barras con cualquier lector USB, asigna código propio a lo que no lo trae e imprime la etiqueta. Está en el plan Inicio, gratuito hasta 1.000 artículos, para Windows. Instálalo esta semana, compra el lector y la tarde de etiquetado de noviembre está resuelta."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué lector de códigos de barras necesito?",
     "Uno USB de mano, de los de menos de 40 euros. Funciona como un teclado y no necesita instalación. Vale para la mayoría de tiendas."),
    ("¿Cómo pongo código de barras a productos que no lo traen?",
     "El programa asigna un código propio a cada referencia e imprime la etiqueta. Se pega en el producto o en el estante y se lee igual que un código de fábrica."),
    ("¿Necesito una impresora de etiquetas?",
     "Para una campaña, no necesariamente: hojas de etiquetas adhesivas en la impresora normal sirven. Si etiquetas cientos de referencias cada mes, una impresora de etiquetas ahorra tiempo."),
    ("¿Y la ropa, que tiene tallas y colores?",
     "Se da de alta el modelo con su matriz de tallas y colores. Cada variante lleva su código y su stock, y en la caja se pasa la etiqueta de la prenda."),
    ("¿Cuánto tiempo lleva etiquetar una campaña entera?",
     "Unas doscientas referencias, una tarde, si se hace por proveedor y con el lector. Lo que llega sin código es lo que más tiempo lleva."),
  ],
  relacionadas=[("Matriz de tallas y colores", "tallas-y-colores.html", "Entrar moda por variante"),
                ("Black Friday en la tienda de barrio", "blog/black-friday-comercio-local-participar-o-no.html", "Qué etiquetar con descuento"),
                ("La Navidad se prepara en septiembre", "blog/campana-navidad-tienda-preparar-en-septiembre.html", "Pedido y entrada de género"),
                ("Programa de caja registradora gratis", "programa-caja-registradora-gratis.html", "Tu PC como caja")]),

# ------------------------------------------------------------------ 27 oct
"todos-los-santos-floristeria-semana-grande": dict(
  title="Todos los Santos en la Floristería: la Semana Grande",
  desc="El 1 de noviembre de 2026 es domingo: la floristería vende del jueves al sábado lo que no vende en dos meses. Flor fresca, merma, clientes que repiten y cobrar sin cola.",
  kw="todos los santos floristeria, floristeria 1 noviembre ventas, flores todos los santos, floristeria campaña noviembre, tpv floristeria",
  h1="Todos los Santos: la semana grande de la floristería",
  sub="Crisantemos, claveles y la misma señora que viene cada año el 31 por la mañana. Es la campaña donde más se pierde por merma y donde más vale acordarse del cliente.",
  publicado="2026-10-27",
  para="Floristerías",
  resumen=[
    "Todos los Santos de 2026 cae en domingo, así que la floristería vende del jueves 29 al sábado 31 de octubre, con el pico el sábado por la mañana. Es la campaña con más volumen del año para muchas floristerías, por encima de San Valentín, y la de más merma si se compra de más.",
    "Lo que la decide: comprar flor fresca por lo que se vendió el año pasado, tener la ficha de los clientes que vienen cada año, y cobrar rápido el sábado con los ramos y centros ya dados de alta con su precio.",
  ],
  cuerpo=[
    ("Por qué el domingo lo cambia todo",
     ["Cuando el 1 de noviembre cae en domingo los cementerios se llenan el sábado y el domingo, y la flor se compra el viernes y el sábado por la mañana. Casi toda la venta de la campaña se concentra en 36 horas. Eso obliga a tener la flor en tienda el jueves, preparada el viernes, y a cobrar el sábado sin pensar.",
      "El riesgo es el de siempre en flor fresca: comprar de más y tirarlo el lunes. La merma en Todos los Santos puede ser la diferencia entre una campaña buena y una que solo ha dado trabajo."],
     None),
    ("Comprar por lo que se vendió, no por lo que se teme",
     ["El pedido de crisantemo, clavel y verde se hace a mercado con una semana, y la cantidad se decide con una cifra: lo que se vendió el año pasado, por tipo de producto. Ramos, centros, plantas de temporada, flor suelta. Si el año pasado esa cifra quedó apuntada en el programa de caja, el pedido de este año sale de ahí. Si no, este año se apunta.",
      "Con los ramos y centros dados de alta como artículos con su precio, cada venta del sábado queda registrada por tipo, y el lunes se sabe qué sobró y qué se agotó a las once de la mañana."],
     ["<strong>Ramos y centros</strong> con precio cerrado, dados de alta como artículos: se cobran de una pasada.",
      "<strong>Flor suelta y plantas</strong> con su precio por unidad.",
      "<strong>Lo que sobró el año pasado</strong>: la mitad este año."]),
    ("La ficha del cliente que viene cada año",
     ["En Todos los Santos vuelve la misma gente cada año, y muchos con el mismo pedido: el centro para el mismo nicho, el ramo de las mismas flores. Una ficha de cliente con el historial dice qué compró el año pasado, y eso sirve para dos cosas: atenderla mejor, y avisarla la semana anterior si quiere reservar lo mismo.",
      "En Carrito5 cada venta queda en la ficha del cliente con sus artículos, así que el año que viene, cuando entre por la puerta el 30 de octubre, sabes qué se llevó."],
     None),
    ("El sábado por la mañana: la caja",
     ["Con la tienda llena y la flor recién montada, la caja tiene que ser rápida. Los centros y ramos con precio cerrado y su etiqueta o su código se cobran de una pasada; la flor suelta se cobra por unidad desde el catálogo. Nada de calcular a mano con la cola en la puerta.",
      "Y si ese sábado se cae internet, que en un barrio con todo el mundo en la calle pasa, un programa que guarda los datos en el propio ordenador sigue cobrando e imprimiendo tickets."],
     None),
    ("Después: San Valentín ya está a cien días",
     ["La floristería encadena tres campañas de encargo: Todos los Santos, San Valentín el 14 de febrero de 2027 (domingo, así que se vende el viernes 12 y el sábado 13) y el Día de la Madre el 2 de mayo. Con los clientes en su ficha y las ventas apuntadas, cada una empieza con la cifra de la anterior."],
     None),
  ],
  cierre=("Que la campaña quede apuntada",
          ["Si este Todos los Santos lo cobras con calculadora, el año que viene volverás a pedir a ojo. Carrito5 es gratuito hasta 1.000 artículos, se instala en el ordenador de la floristería y guarda cada venta con su artículo y su cliente. Ramos y centros dados de alta hoy, cobrados el sábado sin pensar, y el pedido del año que viene sale solo."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué días se vende más en Todos los Santos de 2026?",
     "El 1 de noviembre cae en domingo, así que la venta se concentra el viernes 30 y, sobre todo, el sábado 31 de octubre por la mañana."),
    ("¿Cómo evito la merma de flor fresca?",
     "Comprando por lo que se vendió el año pasado por tipo de producto. Si tienes las ventas registradas en el programa de caja, la cifra está ahí."),
    ("¿Sirve un TPV para cobrar ramos y centros?",
     "Sí. Se dan de alta como artículos con precio cerrado y se cobran de una pasada. La flor suelta se cobra por unidad desde el catálogo."),
    ("¿Qué me aporta la ficha de cliente en una floristería?",
     "Saber qué compró cada cliente el año pasado, atenderle con eso delante y avisarle la semana anterior si quiere lo mismo. Todos los Santos, San Valentín y el Día de la Madre son campañas de cliente que repite."),
    ("¿Y si se cae internet el sábado?",
     "Carrito5 guarda los datos en tu ordenador y sigue cobrando e imprimiendo tickets sin conexión."),
  ],
  relacionadas=[("TPV para floristerías", "tpv-floristeria.html", "Lo específico de la floristería"),
                ("Calendario comercial 2026-2027", "blog/calendario-comercial-2026-2027-fechas-clave.html", "San Valentín y Día de la Madre"),
                ("Descargar Carrito5", "descargar-tpv-gratis.html", "Antes del jueves 29"),
                ("Funciona sin internet", "verifactu-sin-conexion-internet-offline.html", "Cobrar con la línea caída")]),

}
