# -*- coding: utf-8 -*-
"""Blog de carrito5.com: tercera capa, preguntas 7 a 12.

Portatil como TPV, limite de 1.000 articulos, si es obligatorio tener TPV,
como elegir uno, mantenimiento y copias, y TPV en tablet. Mismas reglas de
funciones confirmadas que blog_2026_09.py.

Sobre obligatoriedad: la norma VeriFactu (RD 1007/2023) regula los sistemas
informaticos de facturacion; no obliga a tener uno. Se dice asi y se remite
al asesor.
"""

BLOG_PREGUNTAS_2 = {

# ------------------------------------------------------------------ 14 ene
"puedo-usar-mi-portatil-como-tpv": dict(
  title="¿Puedo Usar mi Portátil como TPV? Sí, y Suele Ser Mejor Idea",
  desc="Un portátil con Windows, una impresora de tickets y un lector USB son una caja completa. Requisitos reales y cuándo conviene un equipo fijo.",
  kw="usar portatil como tpv, portatil tpv tienda, ordenador portatil caja tienda, tpv en portatil windows, requisitos ordenador tpv, convertir portatil en tpv",
  h1="¿Puedo usar mi portátil como TPV?",
  sub="Sí. Un portátil con Windows, una impresora de tickets y un lector USB son una caja completa. Para una tienda pequeña es a menudo la mejor opción, y para la mesa de la calle, la única.",
  publicado="2027-01-14",
  para="Quien tiene un portátil y no quiere comprar un equipo de TPV",
  resumen=[
    "Un portátil con Windows 7, 8, 10 u 11 sirve como TPV sin más que conectarle por USB una impresora de tickets y un lector de códigos de barras, e instalar un programa de caja. No hace falta pantalla táctil, ni un equipo «de TPV», ni potencia: un portátil de hace cinco años con disco SSD cobra durante años.",
    "Ventajas: ya lo tienes, ocupa poco, se lleva a la mesa de la calle o al mercadillo y tiene batería para un corte de luz. Lo que conviene: un soporte que lo eleve y proteja en el mostrador, un concentrador USB si tiene pocos puertos, y copias de los datos fuera del equipo.",
  ],
  cuerpo=[
    ("Requisitos reales",
     ["Menos de lo que se piensa. Un programa de caja de escritorio pide un Windows que arranque, un par de puertos USB y espacio en disco para los datos, que en una tienda pequeña son unos pocos cientos de megas al año. Un portátil de 2018 con 4 gigas de memoria funciona. Lo que más se nota en la velocidad no es el procesador sino el disco: si el portátil tiene disco mecánico, cambiarlo por un SSD cuesta unos 40 euros y lo hace arrancar en veinte segundos en vez de tres minutos.",
      "Lo que no hace falta: pantalla táctil, tarjeta gráfica, un equipo con etiqueta «TPV», ni Windows Pro. Y no hace falta que sea nuevo: uno reacondicionado por 200 euros vale."],
     ["<strong>Windows 7, 8, 10 u 11</strong> que arranque.",
      "<strong>Disco SSD</strong>: la mejora que más se nota.",
      "<strong>Dos puertos USB</strong>, o un concentrador de 10 euros.",
      "<strong>Sin táctil, sin gráfica, sin Pro</strong>."]),
    ("Conectar impresora y lector",
     ["La impresora de tickets térmica va por USB y Windows la reconoce; el cajón se conecta a la impresora con su cable RJ11. El lector de códigos va por USB en modo teclado y no necesita nada. Si el portátil tiene un solo puerto USB, un concentrador de cuatro resuelve. Si la impresora es de red, se conecta al router y el portátil la ve por wifi o cable, aunque para una caja conviene cable."],
     None),
    ("Ventajas que un equipo fijo no tiene",
     ["Batería: si se va la luz, el portátil sigue y la impresora no, pero la venta queda registrada y el ticket se imprime al volver. Movilidad: se lleva a la mesa de Sant Jordi, al mercadillo, a la feria, y cobra igual con un programa que guarde los datos en local. Y precio: ya está pagado.",
      "El inconveniente es el mostrador: un portátil abierto ocupa espacio, la pantalla se mueve y el teclado se llena de cosas. Un soporte elevado de 20 euros con un teclado y un ratón aparte lo convierte en un puesto de caja limpio, y deja el portátil a salvo de cafés."],
     None),
    ("Cuándo conviene un equipo fijo",
     ["Cuando hay dos personas cobrando por turnos en el mismo puesto y el portátil se lo lleva alguien a casa. Cuando la tienda tiene mucho volumen y se quiere pantalla grande y cajón integrado. O cuando el portátil es el ordenador personal de la familia y los niños lo usan por la tarde. En esos casos, un mini PC de 200 euros con un monitor es la solución, y el programa es el mismo."],
     None),
    ("Los datos: copia fuera del portátil",
     ["Un portátil se cae, se moja y se roba más que un equipo fijo. Si los datos de la tienda están en él, hay que tener copia fuera: un disco externo cada semana, o la nube que la tienda use. Con la copia, un portátil roto se sustituye en una tarde: se instala el programa en otro y se recupera la copia. Pregunta al fabricante de tu programa cómo se hace la copia antes de necesitarla."],
     None),
  ],
  cierre=("El portátil que ya tienes, con un programa gratuito",
          ["Carrito5 se instala en cualquier portátil con Windows, imprime en la impresora de tickets por USB, lee con el lector en modo teclado y guarda los datos en el propio equipo para cobrar sin internet en la calle. Es gratuito hasta 1.000 artículos. Descárgalo en el portátil que tienes y saca un ticket de prueba."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué portátil necesito para usarlo como TPV?",
     "Cualquiera con Windows 7, 8, 10 u 11 que arranque, con un par de puertos USB. Un SSD lo hace mucho más ágil. No hace falta táctil ni potencia."),
    ("¿Cómo conecto la impresora y el lector al portátil?",
     "Por USB los dos. La impresora la reconoce Windows; el lector funciona como un teclado. El cajón va a la impresora con cable RJ11."),
    ("¿Puedo llevarme el portátil a un mercadillo o a la calle y cobrar?",
     "Sí, con un programa que guarde los datos en el propio equipo. Con batería, cobras sin enchufe; la impresora necesita corriente o una batería externa."),
    ("¿Y si se rompe o me lo roban?",
     "Con copia de los datos fuera del portátil, se instala el programa en otro equipo y se recupera la copia en una tarde. Sin copia, se pierde todo."),
    ("¿Es mejor un equipo de TPV que un portátil?",
     "Solo si hay varias personas cobrando por turnos, mucho volumen o el portátil es el de casa. Para una tienda pequeña, el portátil con un soporte y un teclado aparte es una caja completa."),
  ],
  relacionadas=[("Programa de caja registradora gratis", "programa-caja-registradora-gratis.html", "Tu PC como caja"),
                ("¿Cuánto cuesta un TPV?", "blog/cuanto-cuesta-un-tpv-para-una-tienda-pequena.html", "Las partidas del hardware"),
                ("Sant Jordi 2027", "blog/sant-jordi-dia-del-libro-2027-libreria-floristeria.html", "El portátil en la mesa de la calle"),
                ("¿Se puede cobrar sin internet?", "blog/se-puede-cobrar-sin-internet-con-un-tpv.html", "Programa local")]),

# ------------------------------------------------------------------ 4 feb
"que-pasa-cuando-paso-de-1000-articulos-en-carrito5": dict(
  title="¿Qué Pasa Cuando Paso de 1.000 Artículos en Carrito5?",
  desc="El plan Inicio es gratuito hasta 1.000 artículos. Al llegar, el programa sigue y se amplía con licencia comercial o con Caja 5. Cómo se cuentan.",
  kw="carrito5 limite 1000 articulos, carrito5 plan inicio limite, que pasa al superar limite tpv gratis, carrito5 licencia comercial precio, carrito5 ampliar catalogo, tpv gratis limite articulos",
  h1="¿Qué pasa cuando paso de 1.000 artículos en Carrito5?",
  sub="Es la pregunta que más nos hacen por WhatsApp y la que menos webs de software contestan claro. Aquí va completa: qué cuenta como artículo, qué pasa al llegar y qué opciones hay.",
  publicado="2027-02-04",
  para="Quien usa o va a usar el plan gratuito de Carrito5",
  resumen=[
    "El plan Inicio de Carrito5 es gratuito de forma indefinida hasta 1.000 artículos en catálogo. No hay límite de tickets, de tiempo ni de funciones dentro de ese catálogo. Cuando el catálogo llega a 1.000 artículos, el programa no se apaga ni pierde datos: para seguir añadiendo referencias se amplía con la licencia comercial, un pago acotado sin cuota ni comisión.",
    "Si la tienda necesita mucho más catálogo, varias cajas sobre el mismo stock o un programa en propiedad, la opción de la misma casa es Caja 5. Para saber cuántos artículos cuentan en tu caso (con tallas y colores cada variante cuenta), escríbenos por WhatsApp con tu colección y te lo decimos antes de instalar.",
  ],
  cuerpo=[
    ("Qué cuenta como artículo",
     ["Un artículo es cada referencia distinta del catálogo con su propio stock. Un cuaderno de una marca en tamaño A4 es un artículo; el mismo en A5, otro. En moda, con la matriz de tallas y colores, cada combinación de talla y color es una variante con su stock propio, así que cuenta dentro del límite: una camiseta en cinco tallas y tres colores son quince.",
      "Lo que no cuenta: los clientes, los tickets, las ventas históricas, las devoluciones ni los vales. El límite es solo del catálogo activo."],
     ["<strong>Cuenta</strong>: cada referencia con stock propio, incluidas las variantes de talla y color.",
      "<strong>No cuenta</strong>: clientes, tickets, ventas, vales.",
      "<strong>Sin límite</strong> de tiempo ni de número de tickets."]),
    ("Qué pasa el día que llegas a 1.000",
     ["El programa sigue cobrando, imprimiendo y descontando stock con normalidad. Lo que no permite es dar de alta el artículo 1.001 hasta ampliar. No se pierde nada, no hay que reinstalar y no hay prisa: se puede seguir vendiendo lo que hay mientras se decide. Muchas tiendas, antes de ampliar, limpian el catálogo: referencias que no se han vendido en un año y no se van a reponer se dan de baja, y el hueco que dejan suele bastar una temporada más."],
     None),
    ("Las dos salidas",
     ['<div class="c5-tabla-wrap"><table class="c5-tabla"><thead><tr><th></th><th>Licencia comercial de Carrito5</th><th>Caja 5</th></tr></thead><tbody>'
      '<tr><td>Para quién</td><td>La tienda que sigue con una caja y necesita más catálogo</td><td>La tienda que necesita varias cajas, más gestión o el programa en propiedad</td></tr>'
      '<tr><td>Cómo se paga</td><td>Un pago acotado, sin cuota mensual ni comisión</td><td>Licencia en propiedad para PC; también versión en la nube para varias tiendas</td></tr>'
      '<tr><td>Qué cambia</td><td>El límite de catálogo</td><td>El producto: más funciones y otra escala</td></tr>'
      '<tr><td>Quién lo hace</td><td>Ábaco Infoelectrónica S.L.</td><td>La misma empresa</td></tr>'
      '</tbody></table></div>',
      "Los precios concretos de la licencia comercial y de Caja 5 se dan por WhatsApp o teléfono, porque dependen de la configuración; los publica la web de Ábaco Software para Caja 5."],
     None),
    ("Cómo saber dónde estás antes de instalar",
     ["Cuenta las referencias que de verdad vendes, no las que tienes en el almacén. Una tienda de ropa con 150 modelos por temporada y una media de ocho variantes por modelo son 1.200 en catálogo activo, y ahí el plan gratuito se queda corto a la segunda temporada, salvo que se den de baja las variantes agotadas de la anterior. Una papelería con 800 referencias cabe. Una juguetería con 2.000, no. Si dudas, escríbenos con la cifra y te decimos cuál es tu caso sin que pierdas la tarde de instalar."],
     None),
  ],
  cierre=("Empieza gratis, y decide cuando llegues",
          ["El plan Inicio de Carrito5 no caduca, no pide tarjeta y no cobra comisión. Si tu catálogo cabe en 1.000 artículos, es tu programa de caja sin coste; si crece, se amplía sin perder nada. Descárgalo, da de alta lo que más vendes y mira dónde te quedas."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cuál es el límite del plan gratuito de Carrito5?",
     "1.000 artículos en catálogo. Sin límite de tickets, de tiempo ni de funciones dentro de ese catálogo."),
    ("¿Las tallas y colores cuentan como artículos?",
     "Sí: cada variante de talla y color tiene su stock y cuenta dentro del límite. Una camiseta en cinco tallas y tres colores son quince."),
    ("¿Se apaga el programa al llegar a 1.000?",
     "No. Sigue cobrando con normalidad; solo no permite dar de alta más artículos hasta ampliar. No se pierde nada."),
    ("¿Cuánto cuesta ampliar?",
     "La licencia comercial es un pago acotado sin cuota ni comisión; el precio se da por WhatsApp o teléfono según la configuración. Caja 5, el programa en propiedad, publica sus precios en la web de Ábaco Software."),
    ("¿Puedo dar de baja artículos para ganar hueco?",
     "Sí. Las referencias que no se han vendido en un año y no se van a reponer se dan de baja y dejan sitio. Es lo que hacen muchas tiendas antes de ampliar."),
  ],
  relacionadas=[("Descargar Carrito5", "descargar-tpv-gratis.html", "Qué incluye el plan gratuito"),
                ("Sobre Carrito5", "sobre-carrito5.html", "Quién está detrás y por dónde cobra"),
                ("Matriz de tallas y colores", "tallas-y-colores.html", "Cómo cuentan las variantes"),
                ("Caja 5 para PC", "https://www.abacosoftware.com/caja5_pc.asp", "El programa en propiedad")]),

# ------------------------------------------------------------------ 4 mar
"es-obligatorio-tener-tpv-en-una-tienda": dict(
  title="¿Es Obligatorio Tener un TPV en una Tienda?",
  desc="Ninguna ley obliga a tener TPV. La norma exige ticket por cada venta y, desde 2027, que el programa que uses cumpla VeriFactu. Qué significa en la tienda.",
  kw="es obligatorio tener tpv, tpv obligatorio tienda, obligatorio programa facturacion tienda, verifactu obligatorio tpv, se puede vender sin tpv, tienda sin tpv legal",
  h1="¿Es obligatorio tener un TPV en una tienda?",
  sub="No hay una ley que diga «toda tienda debe tener un TPV». Hay una que dice cómo tiene que comportarse el programa si lo tienes, y otra que dice que cada venta lleva su ticket. Entre las dos, la respuesta práctica.",
  publicado="2027-03-04",
  para="Quien abre una tienda o cobra todavía con libreta",
  resumen=[
    "No es obligatorio tener un TPV ni un programa de caja: la norma no impone el medio. Lo que obliga es, primero, a emitir factura simplificada (el ticket) por cada venta a consumidor, con los datos que fija el reglamento de facturación; y segundo, desde el 1 de enero de 2027 para sociedades y el 1 de julio de 2027 para autónomos, a que cualquier sistema informático que uses para facturar cumpla VeriFactu, con registros encadenados y QR en el ticket.",
    "En la práctica, una tienda que emite tickets a diario lo hace con un programa, y ese programa tiene que estar adaptado. Facturar a mano con talonario sigue siendo posible en teoría, pero en una tienda con decenas de ventas al día no es viable. Esto es información general, no asesoramiento fiscal: consulta tu caso con tu asesor.",
  ],
  cuerpo=[
    ("Lo que dice la norma, separado en dos",
     ["La primera obligación es antigua: el reglamento de facturación exige emitir factura por cada operación, y en ventas a consumidor final permite la factura simplificada, que es el ticket, con un contenido mínimo: número, fecha, datos del vendedor, descripción, tipo de IVA e importe. Cómo se emite no lo dice: puede ser un programa, una caja registradora o un talonario.",
      "La segunda es nueva: la Ley 11/2021 y el Real Decreto 1007/2023 regulan los sistemas informáticos de facturación. Si usas uno, tiene que garantizar que los registros no se pueden alterar ni borrar, encadenarlos con huella y poner el QR en cada ticket. Obliga a las sociedades desde el 1 de enero de 2027 y a los autónomos desde el 1 de julio de 2027. No obliga a tener el sistema; obliga a que el que tengas cumpla."],
     ["<strong>Obligatorio</strong>: el ticket con su contenido mínimo en cada venta.",
      "<strong>Obligatorio si usas programa</strong>: que cumpla VeriFactu en 2027.",
      "<strong>No obligatorio</strong>: tener programa. En la práctica, casi siempre hay uno."]),
    ("Por qué en la práctica sí hace falta",
     ["Una tienda con cuarenta ventas al día no puede escribir cuarenta tickets a mano con número correlativo, tipo de IVA y desglose. Y una caja registradora antigua que emite tickets es, a efectos de la norma, un sistema de facturación, así que también tiene que cumplir o su fabricante tener declaración responsable. Es decir: la norma no obliga a tener TPV, pero cualquier tienda con mostrador acaba teniendo un sistema que emite tickets, y ese sistema tiene que estar adaptado.",
      "Por eso la pregunta útil no es «¿es obligatorio?» sino «¿cumple el que tengo?». Y la respuesta la da la declaración responsable del fabricante."],
     None),
    ("Lo que no es obligatorio y te dirán que sí",
     ["No es obligatoria una cuota a Hacienda. No es obligatorio un módulo aparte, ni un certificado adicional para el caso general, ni una pantalla táctil, ni un datáfono concreto. No es obligatorio que el programa sea de pago: un programa gratuito adaptado cumple igual que uno de suscripción. Y no es obligatorio cambiar de banco ni de datáfono por VeriFactu, que regula el programa de facturación, no el cobro."],
     None),
    ("Lo que sí conviene aunque no sea obligatorio",
     ["Un programa de caja da lo que el talonario no: el stock que se descuenta con cada venta, la ficha del cliente para devoluciones y avisos, las etiquetas con código de barras para cobrar rápido, y el registro de ventas que hace el inventario de fin de año y el pedido de la campaña siguiente. Para una tienda pequeña es la diferencia entre saber y suponer, y desde que existen planes gratuitos, no cuesta dinero."],
     None),
  ],
  cierre=("No es obligatorio; es gratis y cumple",
          ["Carrito5 emite la factura simplificada con su contenido mínimo y el QR de VeriFactu, guarda los registros como exige la norma y es gratuito hasta 1.000 artículos, para Windows. Si hoy cobras con libreta o con una caja registradora sin declaración responsable, es la forma de cumplir sin gastar. Para tu caso concreto, tu asesor."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Hay alguna ley que obligue a tener TPV en una tienda?",
     "No. La norma obliga a emitir ticket por cada venta y, desde 2027, a que cualquier sistema informático de facturación que uses cumpla VeriFactu. No impone el medio. Consúltalo con tu asesor."),
    ("¿Puedo vender solo con un talonario de facturas?",
     "En teoría sí, si cada venta lleva su factura simplificada con el contenido mínimo. En una tienda con decenas de ventas al día no es viable."),
    ("¿Mi caja registradora antigua es un sistema de facturación?",
     "Si emite tickets, sí. Su fabricante tiene que tener declaración responsable de VeriFactu para ese modelo, o hay que sustituirla en 2027."),
    ("¿Es obligatorio pagar por el programa?",
     "No. Un programa gratuito adaptado cumple igual que uno de pago. Lo que importa es la declaración responsable del fabricante."),
    ("¿Desde cuándo tiene que cumplir mi programa?",
     "Desde el 1 de enero de 2027 si eres sociedad y desde el 1 de julio de 2027 si eres autónomo, según el RD-ley 15/2025."),
  ],
  relacionadas=[("Factura simplificada y ticket", "factura-simplificada-ticket.html", "El contenido mínimo del ticket"),
                ("VeriFactu: cuándo entra en vigor", "verifactu-entrada-en-vigor.html", "Las dos fechas"),
                ("Ley Antifraude y RD 1007/2023", "verifactu-ley-antifraude-rd1007-2023.html", "La norma completa"),
                ("Programa de caja registradora gratis", "programa-caja-registradora-gratis.html", "De la caja al programa")]),

# ------------------------------------------------------------------ 8 abr
"como-elegir-un-tpv-para-una-tienda-de-barrio-diez-preguntas": dict(
  title="Cómo Elegir un TPV para una Tienda: Diez Preguntas",
  desc="Diez preguntas al vendedor antes de instalar: por dónde cobra, si funciona sin internet, tallas, devoluciones, cómo sacar los datos y VeriFactu.",
  kw="como elegir un tpv, elegir tpv tienda pequeña, que tpv comprar para mi tienda, preguntas antes de comprar tpv, comparar tpv comercio, tpv tienda barrio cual elegir",
  h1="Cómo elegir un TPV para una tienda de barrio: diez preguntas",
  sub="El vendedor te va a enseñar veinte funciones. Tú hazle diez preguntas, y si alguna la contesta con rodeos, ya sabes lo que necesitas saber.",
  publicado="2027-04-08",
  para="Quien va a elegir programa de caja para una tienda pequeña",
  resumen=[
    "Para elegir un TPV en una tienda de barrio, diez preguntas al vendedor deciden más que cualquier demostración: por dónde cobra el programa (cuota, comisión, hardware); si funciona sin internet; si tiene declaración responsable de VeriFactu; si lleva tallas y colores; si hace devoluciones y vales sobre el ticket; si imprime etiquetas con código de barras; cómo se sacan los datos si un día te vas; qué límite tiene y cómo se cuenta; quién coge el teléfono cuando falla; y si se puede probar con el catálogo real antes de pagar.",
    "Un programa que contesta las diez con claridad es candidato. Uno que responde con «eso lo vemos después» a la primera o a la séptima, no.",
  ],
  cuerpo=[
    ("Las diez preguntas y la respuesta buena",
     ['<div class="c5-tabla-wrap"><table class="c5-tabla"><thead><tr><th>Pregunta</th><th>Respuesta que conviene oír</th><th>Señal de alarma</th></tr></thead><tbody>'
      '<tr><td>1. ¿Por dónde cobra el programa?</td><td>Una cifra clara: gratis hasta un límite, o una cuota, o una licencia. Sin comisión por cobro.</td><td>«Depende», o una comisión por venta escondida en el datáfono.</td></tr>'
      '<tr><td>2. ¿Cobra sin internet?</td><td>Sí, los datos están en el ordenador.</td><td>«Tiene un modo offline» sin decir cuántas ventas guarda.</td></tr>'
      '<tr><td>3. ¿Tiene declaración responsable de VeriFactu?</td><td>Sí, y te la mando por escrito para la versión actual.</td><td>«Estamos en ello» o «llegará en la próxima versión».</td></tr>'
      '<tr><td>4. ¿Lleva tallas y colores?</td><td>Sí, con matriz: un modelo, todas sus variantes con stock.</td><td>«Puedes crear un artículo por talla».</td></tr>'
      '<tr><td>5. ¿Hace devoluciones y vales sobre el ticket?</td><td>Sí, localizando la venta original, con el vale en la ficha del cliente.</td><td>«Las devoluciones las apuntas aparte».</td></tr>'
      '<tr><td>6. ¿Imprime etiquetas con código de barras?</td><td>Sí, con código propio para lo que no lo trae.</td><td>«Necesitas un módulo de etiquetas» de pago.</td></tr>'
      '<tr><td>7. ¿Cómo saco mis datos si me voy?</td><td>Con una explicación concreta de qué se exporta y cómo.</td><td>Silencio, o «nadie se va».</td></tr>'
      '<tr><td>8. ¿Qué límite tiene y cómo se cuenta?</td><td>Una cifra y si cuenta variantes o modelos.</td><td>Un límite de tiempo o de tickets que se pasa en rebajas.</td></tr>'
      '<tr><td>9. ¿Quién coge el teléfono cuando falla?</td><td>Un número, un horario y una persona en España.</td><td>«Abre un ticket» o un chat sin horario.</td></tr>'
      '<tr><td>10. ¿Puedo probarlo con mi catálogo antes de pagar?</td><td>Sí, sin tarjeta y sin límite de tiempo, o con uno largo.</td><td>«Prueba de 7 días» o una demo con datos de ejemplo.</td></tr>'
      '</tbody></table></div>'],
     None),
    ("Por qué estas diez y no las veinte funciones",
     ["Las funciones se ven en la demostración y casi todos los programas tienen las mismas. Lo que separa a uno de otro está en las diez preguntas: el coste real a cinco años, la dependencia de internet, el cumplimiento fiscal, y cuatro cosas que en una tienda pequeña se hacen a diario (tallas, devoluciones, etiquetas, soporte). Un programa que las contesta bien y tiene pocas funciones vale más que uno con cuarenta funciones y una comisión por venta."],
     None),
    ("Cómo hacer la prueba con el catálogo real",
     ["Instala el candidato, da de alta treinta referencias reales con sus códigos, una prenda con tallas y colores si vendes ropa, y haz cinco ventas, una devolución y un vale. Imprime un ticket y escanea el QR con el móvil. Si en una tarde has podido hacer todo eso sin llamar a nadie, el programa es candidato. Si has tenido que llamar tres veces o algo era «de pago», ya lo sabes antes de pagar.",
      "Haz la prueba con dos programas, no con uno. Comparar es lo que enseña."],
     ["<strong>Treinta referencias reales</strong>, con códigos.",
      "<strong>Una prenda con tallas</strong>, si vendes moda.",
      "<strong>Cinco ventas, una devolución, un vale</strong>.",
      "<strong>Un ticket con QR</strong>, escaneado con el móvil."]),
    ("La pregunta once, para ti",
     ["¿Cuántos artículos vendes de verdad, y cuántas cajas tienes? Con esas dos cifras sabes si un plan gratuito con límite de catálogo te cabe, si necesitas licencia, o si tu tienda es de otra escala y necesita varias cajas sobre el mismo stock. Contestarla antes de mirar programas ahorra la mitad de las comparaciones."],
     None),
  ],
  cierre=("Las diez respuestas de Carrito5",
          ["Gratis hasta 1.000 artículos, sin comisión; cobra sin internet; adaptado a VeriFactu; matriz de tallas y colores; devoluciones y vales sobre el ticket en la ficha del cliente; etiquetas con código propio; una caja sobre un ordenador con Windows; WhatsApp y teléfono en España en horario comercial; y se prueba sin tarjeta y sin límite de tiempo con tu catálogo real. Sobre cómo sacar los datos y cómo cuentan las variantes en tu caso, pregúntanos por WhatsApp antes de instalar."],
          "Descargar Carrito5 y hacer la prueba", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué es lo primero que hay que preguntar al elegir un TPV?",
     "Por dónde cobra: cuota, comisión por venta o hardware obligatorio. Es lo que decide el coste a cinco años, y lo que más se esconde."),
    ("¿Cómo compruebo que cumple VeriFactu?",
     "Pidiendo la declaración responsable por escrito para la versión actual. Si no la tienen, no cumple, digan lo que digan."),
    ("¿Qué funciones son imprescindibles en una tienda pequeña?",
     "Tallas y colores si vendes moda, devoluciones y vales sobre el ticket, etiquetas con código de barras, ficha de cliente y que funcione sin internet."),
    ("¿Cómo pruebo un TPV antes de pagar?",
     "Con treinta referencias reales, una prenda con tallas, cinco ventas, una devolución, un vale y un ticket con QR escaneado. Con dos programas, para comparar."),
    ("¿Cuándo un plan gratuito se queda corto?",
     "Cuando el catálogo supera su límite contando variantes, o cuando hay varias cajas sobre el mismo stock. Cuenta artículos y cajas antes de mirar programas."),
  ],
  relacionadas=[("Mejor TPV gratis 2026", "mejor-tpv-gratis-2026.html", "Los cinco tipos, comparados"),
                ("¿Cuánto cuesta un TPV?", "blog/cuanto-cuesta-un-tpv-para-una-tienda-pequena.html", "La pregunta uno, con cifras"),
                ("¿Se puede cobrar sin internet?", "blog/se-puede-cobrar-sin-internet-con-un-tpv.html", "La pregunta dos"),
                ("¿Qué pasa cuando paso de 1.000 artículos?", "blog/que-pasa-cuando-paso-de-1000-articulos-en-carrito5.html", "La pregunta ocho")]),

# ------------------------------------------------------------------ 6 may
"que-mantenimiento-necesita-un-tpv-copias-impresora-actualizaciones": dict(
  title="¿Qué Mantenimiento Necesita un TPV? Tres Tareas",
  desc="Tres tareas que no se saltan: copia de los datos cada semana fuera del equipo, cabezal de la impresora limpio para que el QR se lea, y actualizaciones.",
  kw="mantenimiento tpv, copia seguridad tpv, limpiar impresora tickets cabezal, actualizar programa tpv, mantenimiento caja tienda, que hacer si falla el tpv",
  h1="¿Qué mantenimiento necesita un TPV?",
  sub="Menos del que venden los contratos de mantenimiento y más del que hace la mayoría de tiendas. Tres tareas, ninguna de más de diez minutos.",
  publicado="2027-05-06",
  para="Quien lleva un TPV y no quiere que le falle un sábado",
  resumen=[
    "Un TPV de tienda con un programa de escritorio necesita tres tareas de mantenimiento: una copia de los datos fuera del equipo cada semana (disco externo o nube), porque los datos están en el ordenador de la tienda; limpiar el cabezal de la impresora de tickets cada pocas semanas con alcohol isopropílico, porque un QR de VeriFactu borroso es un ticket que no cumple; e instalar las actualizaciones del programa cuando salen, porque con VeriFactu la versión instalada tiene que ser la de la declaración responsable.",
    "Además, una vez al año: limpiar el polvo del ordenador, revisar el SSD y cambiar el rollo de papel por uno de calidad. Un contrato de mantenimiento mensual rara vez cubre nada de esto; cubre que alguien venga cuando ya ha fallado.",
  ],
  cuerpo=[
    ("Uno: la copia de los datos, cada semana",
     ["Con un programa que guarda los datos en el ordenador de la tienda, el ordenador es el único sitio donde están el catálogo, el stock, los clientes y las ventas de años. Si el disco muere, se pierden. La copia semanal en un disco externo que se lleva a casa, o en la nube que la tienda use, es la única tarea que de verdad no se puede saltar. Cuesta diez minutos y un disco de 30 euros.",
      "Cómo se hace depende del programa: unos tienen un botón de copia, otros piden copiar una carpeta. Pregunta al fabricante antes de necesitarla, y haz una prueba de recuperación una vez, en otro equipo, para saber que la copia sirve. Con VeriFactu, además, los registros de facturación se conservan; la copia es también la garantía de eso."],
     ["<strong>Cada semana</strong>, en disco externo o nube.",
      "<strong>Fuera de la tienda</strong>: una copia en el mismo ordenador no es una copia.",
      "<strong>Probada una vez</strong>: recuperar en otro equipo y ver que abre."]),
    ("Dos: la impresora, el cabezal y el papel",
     ["La impresora térmica es la pieza que más falla y la que menos se cuida. El cabezal acumula residuo del papel y empieza a imprimir líneas blancas; en un texto no se nota, en un QR sí, y un QR que no se lee es un ticket que no cumple VeriFactu. Cada tres o cuatro semanas, con la impresora apagada, un bastoncillo con alcohol isopropílico por el cabezal, dejar secar y listo. Dos minutos.",
      "El papel: el más barato del paquete de cien deja más residuo y se borra antes. Un rollo de calidad cuesta céntimos más y evita la mitad de las limpiezas. Y el cortador: si empieza a atascarse, es el momento de limpiarlo, no de esperar al sábado."],
     None),
    ("Tres: las actualizaciones del programa",
     ["Con VeriFactu, la versión del programa instalada tiene que corresponder a la declaración responsable del fabricante. Cuando sale una actualización, se instala, se guarda la declaración responsable nueva si la hay, y se hace un ticket de prueba. No es semanal: son unas pocas al año. Lo que no conviene es ignorarlas durante dos años y descubrir en una comprobación que la versión ya no es la declarada.",
      "Windows también se actualiza, y es mejor que lo haga fuera del horario de la tienda: en la configuración se le pone un horario activo de mañana a tarde para que no reinicie con la tienda llena."],
     None),
    ("Una vez al año, y lo que no hace falta",
     ["Una vez al año: abrir el ordenador y quitar el polvo del ventilador, comprobar el estado del SSD con la herramienta del fabricante, cambiar el cable USB de la impresora si está pelado, y revisar que el cajón abre limpio. Una tarde de enero.",
      "Lo que no hace falta: un contrato de mantenimiento mensual que solo cubre la visita cuando ya ha fallado. Con las tres tareas hechas, lo que falla es el hardware, y el hardware de un TPV de tienda se sustituye por menos de lo que cuesta un año de contrato."],
     None),
  ],
  cierre=("Copia, cabezal, actualización: lo demás es gratis",
          ["Carrito5 guarda los datos en tu ordenador y se actualiza cuando hay versión nueva; la copia se hace desde el programa y te explicamos cómo por WhatsApp antes de que la necesites. Es gratuito hasta 1.000 artículos, para Windows. Si dudas de si tu copia sirve o de si tu impresora imprime bien el QR, escríbenos: es una conversación de cinco minutos que evita un sábado malo."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cada cuánto hay que hacer copia de los datos del TPV?",
     "Cada semana, en un disco externo que se lleve a casa o en la nube. Una copia en el mismo ordenador no protege de que el disco muera."),
    ("¿Cómo limpio la impresora de tickets?",
     "Con la impresora apagada, un bastoncillo con alcohol isopropílico por el cabezal, cada tres o cuatro semanas. Evita las líneas blancas que hacen ilegible el QR."),
    ("¿Tengo que actualizar el programa por VeriFactu?",
     "Sí, cuando el fabricante saque versión nueva: la versión instalada tiene que corresponder a la declaración responsable. Son unas pocas al año."),
    ("¿Necesito un contrato de mantenimiento?",
     "Para una tienda pequeña, rara vez. Con copia semanal, impresora limpia y programa actualizado, lo que falla es hardware, y se sustituye por menos que un año de contrato."),
    ("¿Cómo evito que Windows reinicie con la tienda llena?",
     "Poniendo en la configuración de Windows un horario activo que cubra el horario de la tienda; las actualizaciones se instalan fuera de él."),
  ],
  relacionadas=[("Cerrar por vacaciones en agosto", "blog/cerrar-por-vacaciones-agosto-tienda-sin-perder-clientes.html", "La copia antes de cerrar"),
                ("¿Qué impresora de tickets comprar?", "blog/que-impresora-de-tickets-comprar-para-un-tpv.html", "La pieza que más falla"),
                ("Primera semana con VeriFactu", "blog/verifactu-en-vigor-primera-semana-comprobaciones.html", "El QR que no se lee"),
                ("¿Puedo usar mi portátil como TPV?", "blog/puedo-usar-mi-portatil-como-tpv.html", "Copia fuera del portátil")]),

# ------------------------------------------------------------------ 10 jun
"hay-tpv-gratis-para-tablet-o-movil": dict(
  title="¿Hay TPV Gratis para Tablet o Móvil? Sí, y No Es Este",
  desc="Hay TPV gratuitos para tablet y móvil, casi todos en la nube y con comisión por cobro. Carrito5 es de escritorio para Windows. Cuándo conviene cada uno.",
  kw="tpv gratis tablet, tpv android gratis, tpv ipad gratis tienda, tpv movil gratis comercio, tpv tablet o pc, carrito5 tablet",
  h1="¿Hay TPV gratis para tablet o móvil?",
  sub="Sí los hay, y no es este. Lo decimos en el título para no hacerte perder tiempo, y después contamos cuándo la tablet es buena idea y cuándo el ordenador lo es más.",
  publicado="2027-06-10",
  para="Quien quiere cobrar con una tablet o un móvil",
  resumen=[
    "Hay TPV gratuitos para tablet Android, iPad y móvil: aplicaciones que funcionan en el navegador o como app, con los datos en la nube, y muchas ligadas a una pasarela de cobro que cobra comisión por cada venta con tarjeta. Sirven bien para quien empieza con poco volumen, para puestos móviles y para hostelería pequeña.",
    "Carrito5 no es uno de ellos: es un programa de escritorio para Windows, con los datos en el ordenador, sin comisión y que funciona sin internet. Si quieres tablet, no lo instales. Si tienes una tienda con mostrador, catálogo, tallas y stock, el ordenador suele ser mejor idea, y aquí explicamos por qué.",
  ],
  cuerpo=[
    ("Lo que hay para tablet",
     ["Tres familias. Las aplicaciones de las plataformas de cobro, que regalan el TPV y ganan con la comisión de cada pago con tarjeta: buenas para empezar, caras cuando se factura. Los TPV en la nube con plan gratuito y módulos de pago, que funcionan en cualquier tablet con navegador: flexibles, dependientes de internet, con cuota al crecer. Y las apps de hostelería con mesas y comandas, que en comercio no encajan.",
      "Todas comparten dos cosas: los datos viven fuera de la tienda, y sin conexión se paran o quedan limitadas."],
     None),
    ("Cuándo la tablet es buena idea",
     ["Cuando no hay mostrador: un puesto de mercado, una food truck, una tienda efímera, un artesano en ferias. Cuando el volumen es bajo y la comisión por cobro no duele todavía. Cuando se cobra de pie, moviéndose por el local. Y cuando lo que se vende no tiene tallas ni stock que llevar por variante. Ahí una tablet con una app gratuita y un lector de tarjetas es una caja razonable."],
     ["<strong>Sin mostrador</strong>: mercados, ferias, tiendas efímeras.",
      "<strong>Poco volumen</strong>: la comisión no pesa aún.",
      "<strong>Sin tallas ni stock</strong> por variante."]),
    ("Cuándo el ordenador es mejor idea",
     ["Cuando hay mostrador, catálogo de cientos de referencias, tallas y colores, devoluciones a diario y una impresora de tickets fija. Cuando se cobra con el datáfono del banco y no se quiere una comisión encima. Cuando internet en el local no es de fiar. Y cuando se quiere que los datos estén en la tienda y no en un servidor ajeno. Es el caso de la mayoría de tiendas de barrio de ropa, calzado, regalo, papelería, joyería o mascotas.",
      "El ordenador no tiene que ser nuevo ni táctil: un portátil de hace años con un SSD, una impresora de 80 euros y un lector de 30 son una caja completa."],
     None),
    ("Lo que Carrito5 es y no es",
     ["Carrito5 es un programa de escritorio para Windows 7, 8, 10 y 11. No tiene versión para Android, iPad, Mac ni navegador, y no la anunciamos como próxima. A cambio: sin comisión por venta, sin cuota hasta 1.000 artículos, funciona sin internet, lleva tallas y colores, ficha de cliente con devoluciones y vales, y etiquetas con código de barras. Si necesitas tablet, te orientamos hacia lo que hay aunque no sea nuestro; si tienes una tienda con mostrador, pruébalo."],
     None),
  ],
  cierre=("Si es tablet, no es Carrito5; si es mostrador, pruébalo",
          ["Carrito5 se instala en un ordenador o portátil con Windows y es gratuito hasta 1.000 artículos, sin comisión y sin internet obligatorio. Si tu tienda tiene mostrador, catálogo y tallas, descárgalo y compara con la app de tablet que estés mirando: la diferencia se ve en la primera devolución y en la primera comisión."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Existe algún TPV gratis para tablet Android o iPad?",
     "Sí: apps de plataformas de cobro que ganan con la comisión por venta, y TPV en la nube con plan gratuito y módulos de pago. Los datos están fuera de la tienda y necesitan internet."),
    ("¿Carrito5 funciona en tablet?",
     "No. Es un programa de escritorio para Windows. No tiene versión para Android, iPad, Mac ni navegador."),
    ("¿Cuándo conviene una tablet como TPV?",
     "Sin mostrador (mercados, ferias), con poco volumen y sin tallas ni stock por variante. Ahí una app gratuita con lector de tarjetas es una caja razonable."),
    ("¿Cuándo conviene el ordenador?",
     "Con mostrador, catálogo grande, tallas, devoluciones diarias, impresora fija, datáfono del banco e internet poco fiable. La mayoría de tiendas de barrio."),
    ("¿Puedo usar un portátil en vez de un equipo de TPV?",
     "Sí. Un portátil con Windows, una impresora de tickets y un lector USB son una caja completa, y se lleva a la calle."),
  ],
  relacionadas=[("Mejor TPV gratis 2026", "mejor-tpv-gratis-2026.html", "Los cinco tipos, incluidos los de tablet"),
                ("¿Puedo usar mi portátil como TPV?", "blog/puedo-usar-mi-portatil-como-tpv.html", "La alternativa a la tablet"),
                ("¿Se puede cobrar sin internet?", "blog/se-puede-cobrar-sin-internet-con-un-tpv.html", "Nube frente a local"),
                ("Sobre Carrito5", "sobre-carrito5.html", "Qué es y qué no es")]),

}
