# -*- coding: utf-8 -*-
"""Blog de carrito5.com: diciembre de 2026.

Navidad en ejecucion, el vale de devolucion, lo que cambia el 1 de enero con
VeriFactu, el inventario de fin de año y la semana de cambios de Reyes.
Mismas reglas de funciones confirmadas que blog_2026_09.py.
"""

BLOG_2026_12 = {

# ------------------------------------------------------------------ 1 dic
"navidad-tres-semanas-que-deciden-el-ano": dict(
  title="Navidad en la Tienda: las Tres Semanas que Deciden el Año",
  desc="Del 1 al 24 de diciembre de 2026, semana a semana: los dos sábados grandes, la reposición de urgencia, la caja con la tienda llena y qué no hacer el 23.",
  kw="navidad tienda ventas, campaña navidad comercio, diciembre tienda que hacer, sabados navidad comercio, vender mas navidad tienda pequeña",
  h1="Las tres semanas de Navidad, semana a semana",
  sub="El pedido ya está hecho y el género ya está en la tienda. Ahora toca lo único que no se puede preparar: vender bien con la tienda llena.",
  publicado="2026-12-01",
  para="Regalo, juguetería, moda, joyería, perfumería",
  resumen=[
    "La campaña de Navidad de 2026 en la calle son tres semanas y media, del martes 1 al jueves 24 de diciembre, con dos sábados grandes, el 12 y el 19, y un pico final el martes 22 y el miércoles 23. La primera semana se vende poco y se mira mucho; la segunda se repone de urgencia lo que se agota; la tercera se cobra sin parar.",
    "Lo que decide el resultado en esas semanas es la velocidad de la caja, saber qué queda de cada talla sin ir al almacén, y no dejar la tienda con una sola persona los dos sábados.",
  ],
  cuerpo=[
    ("Semana del 1 al 6: mirar, no comprar",
     ["La primera semana de diciembre la gente entra, mira, pregunta precios y se va. Es normal y no significa que la campaña vaya mal. Es la semana de tomar nota: qué preguntan, qué cogen y dejan, qué talla o color piden y no hay. Esa información es la que decide el pedido de urgencia de la semana siguiente.",
      "Con la venta registrada por referencia y por talla, esa nota la toma el programa. Lo que se ha vendido en la primera semana, poco pero significativo, marca la tendencia. Y si hay reservas del Cyber Monday, es la semana de confirmar con el proveedor que llegan."],
     None),
    ("Semana del 7 al 13: la reposición de urgencia y el primer sábado",
     ["El lunes 7 y el martes 8 (festivo en buena parte de España, cuidado con el horario del proveedor) se hace el último pedido que va a llegar a tiempo. Se pide lo que la primera semana ha dicho que se mueve, por referencia y por talla, y se pide con la condición de que llegue antes del 17. Lo que no llegue antes del 17 no sirve.",
      "El sábado 12 es el primer sábado grande. Dos personas en tienda como mínimo, el género repuesto el viernes por la tarde, y la caja lista: rollo de la impresora cambiado, lector probado, y la respuesta a «¿lo tienes en otra talla?» en la pantalla."],
     ["<strong>Pedido de urgencia</strong> el lunes 7, con la condición de entrega antes del 17.",
      "<strong>Sábado 12</strong>: dos personas, género repuesto el viernes.",
      "<strong>Reservas</strong>: avisar a quien reservó de que su artículo está y hasta cuándo."]),
    ("Semana del 14 al 20: el segundo sábado, el grande",
     ["El sábado 19 es el día de más venta del año en casi todo el comercio de regalo. Todo lo que se pueda hacer antes, se hace antes: el escaparate montado el jueves, el almacén ordenado por referencia, las etiquetas de todo lo que llegó el 17 impresas y puestas. Ese día la caja no puede parar por nada: ni por buscar un precio, ni por una duda de talla, ni por una gestión que pueda esperar a que pase el pico.",
      "Es también la semana de las reservas no recogidas: el domingo 20 vuelve a la venta lo que se reservó y no se recogió, avisando antes a quien lo reservó."],
     None),
    ("Del 21 al 24: el último empujón y lo que no hay que hacer",
     ["El martes 22 y el miércoles 23 vende quien no ha comprado todavía, y compra rápido y lo que hay. No es momento de reponer ni de reordenar: es momento de cobrar y de sugerir alternativas cuando no queda la talla. La ficha del cliente ayuda: si alguien busca un regalo para quien ya compró en la tienda, su historial dice qué talla usa.",
      "Lo que no hay que hacer el 23 por la tarde: cambiar precios, mover el escaparate, empezar el inventario. El 24 se cierra a mediodía en muchas tiendas y lo que quede se mira el 26 con calma. Y un detalle: el 24 por la mañana todavía vende, y bastante."],
     None),
    ("El 26: la campaña se apunta",
     ["El día 26 la tienda abre para cambios y para las rebajas que algunos adelantan. Antes de nada, un vistazo a lo vendido del 1 al 24 por referencia y por talla, comparado con lo pedido en octubre. Esa comparación es el pedido del año que viene. Si la venta ha quedado en el programa, es un vistazo; si ha quedado en tickets de papel, no la va a hacer nadie."],
     None),
  ],
  cierre=("Si aún cobras con calculadora, el sábado 19 lo vas a notar",
          ["Carrito5 se instala en el ordenador de la tienda en unos minutos y es gratuito hasta 1.000 artículos. Lector de códigos de barras, tallas y colores en pantalla, ficha de clientes y ticket con QR. Todavía da tiempo a dar de alta las referencias de campaña antes del sábado 12, y a que el sábado 19 la caja sea pasar el lector."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cuáles son los días de más venta de la Navidad de 2026?",
     "Los sábados 12 y 19 de diciembre, con el 19 como día más fuerte del año, y el martes 22 y el miércoles 23 como último pico. El 24 por la mañana también vende."),
    ("¿Hasta cuándo puedo hacer un pedido de reposición?",
     "Hasta el lunes 7 o el martes 8, con la condición de que llegue antes del 17. Lo que llegue después no se vende en Navidad."),
    ("¿Qué hago con las reservas que no se recogen?",
     "Avisar a quien reservó y devolver el artículo a la venta el 20 de diciembre, como se anunció al reservar."),
    ("¿Cuándo hago balance de la campaña?",
     "El 26, antes de abrir los cambios: lo vendido del 1 al 24 por referencia y por talla, contra lo pedido en octubre. Es el pedido del año que viene."),
    ("¿Da tiempo a instalar un TPV en diciembre?",
     "Sí, si es esta semana. Carrito5 se instala en minutos y las referencias de campaña se dan de alta en una tarde con el lector."),
  ],
  relacionadas=[("Cyber Monday sin web: reservas", "blog/cyber-monday-tienda-sin-venta-online.html", "De dónde salen las reservas"),
                ("Política de devoluciones para Navidad", "blog/politica-devoluciones-campana-navidad.html", "Antes de los cambios"),
                ("TPV para jugueterías y regalos", "tpv-jugueteria-regalos.html", "El sector de diciembre"),
                ("Matriz de tallas y colores", "tallas-y-colores.html", "Qué queda de cada talla, en pantalla")]),

# ------------------------------------------------------------------ 9 dic
"vale-de-devolucion-tienda-como-funciona": dict(
  title="El Vale de Devolución en la Tienda: Cómo Llevarlo",
  desc="Qué es un vale de devolución, qué puede exigir la tienda, qué caducidad es razonable y cómo llevarlos en la ficha del cliente para saber cuántos hay vivos.",
  kw="vale devolucion tienda, vale de compra tienda fisica, caducidad vale devolucion, vale devolucion ley, como hacer vale devolucion, gestionar vales tienda",
  h1="El vale de devolución: qué es, qué puede exigir la tienda y cómo llevarlo",
  sub="Un vale mal llevado es dinero que la tienda debe y no sabe a quién. Un vale bien llevado es una venta que vuelve en marzo.",
  publicado="2026-12-09",
  para="Todo el comercio con cambios de regalo",
  resumen=[
    "El vale de devolución es el documento con el que una tienda reconoce a un cliente un importe para gastar en ella tras una devolución. En tienda física, cuando el producto no tiene defecto, la tienda no está obligada a devolver dinero y puede ofrecer vale, siempre que su política lo diga y esté a la vista. El vale debe indicar importe, fecha y condiciones, y es razonable que no tenga una caducidad corta.",
    "Lo que evita problemas es llevarlos apuntados: cada vale en la ficha del cliente, con su importe y su fecha, para saber en cualquier momento cuántos hay en circulación y por cuánto, y para localizarlo aunque el cliente pierda el papel. Información general, no asesoramiento legal.",
  ],
  cuerpo=[
    ("Qué es y cuándo se puede dar",
     ["Cuando un cliente devuelve algo que no tiene defecto, la tienda física no está obligada a devolverle el dinero. Puede no aceptar la devolución, o aceptarla a cambio de otro artículo o de un vale. Lo que decide es la política de la tienda, y esa política tiene que estar anunciada antes de la compra, en un cartel y en el ticket.",
      "Si el producto sí tiene defecto, la cosa cambia: entra la garantía legal y el cliente puede exigir reparación, sustitución o, si no es posible, la devolución del dinero. Ahí no cabe imponer un vale. Para el detalle de tu caso, tu asesor o la oficina de consumo de tu comunidad autónoma."],
     None),
    ("Qué tiene que llevar el vale",
     ["Un vale es un reconocimiento de deuda de la tienda con el cliente, así que conviene que sea claro. Importe, fecha de emisión, condiciones de uso (en qué se puede gastar, si se puede fraccionar) y, si la hay, fecha de validez. Sobre la caducidad hay debate y las oficinas de consumo suelen exigir plazos razonables; un vale que caduca en treinta días invita a la reclamación. Un año es una práctica habitual y defendible.",
      "Y un número o referencia que lo identifique, para poder localizarlo si el papel se pierde. Ahí es donde el programa de caja hace la diferencia."],
     ["<strong>Importe</strong> y fecha de emisión.",
      "<strong>Condiciones</strong>: en qué se gasta, si se fracciona, si devuelve cambio.",
      "<strong>Validez</strong> razonable, si se pone.",
      "<strong>Referencia</strong> que lo relacione con la devolución original y con el cliente."]),
    ("Llevarlos apuntados: el problema que nadie ve hasta marzo",
     ["Muchas tiendas emiten vales a mano, con sello y firma, y no los apuntan en ningún sitio. En enero tienen veinte vales en circulación y no saben por cuánto. En marzo aparece uno con el sello y nadie recuerda si se había usado. Y cuando un cliente lo pierde, la discusión es inevitable.",
      "Con el vale apuntado en la ficha del cliente en el momento de la devolución, la tienda sabe en cualquier momento cuántos vales hay vivos y por cuánto, el cliente puede usarlo aunque no traiga el papel, y cuando se gasta queda marcado como usado. En Carrito5 la devolución sobre el ticket original y el vale en la ficha del cliente están en el plan gratuito."],
     None),
    ("Cómo se hace, paso a paso",
     ['<ol class="c5-pasos">'
      '<li><strong>Localiza la venta original</strong>: por el ticket, o por la ficha del cliente si no lo trae.</li>'
      '<li><strong>Devuelve el artículo al stock</strong> con su talla y color, para que vuelva a estar disponible.</li>'
      '<li><strong>Si hay cambio por otro artículo</strong>, cobra o devuelve la diferencia según la política.</li>'
      '<li><strong>Si hay vale</strong>, emítelo con su importe y déjalo en la ficha del cliente. Entrega el papel, pero el registro es el que manda.</li>'
      '<li><strong>Cuando el cliente lo use</strong>, se descuenta de la compra y queda marcado como usado.</li>'
      '</ol>'],
     None),
  ],
  cierre=("Los vales de esta Navidad, apuntados desde el primero",
          ["Carrito5 hace la devolución sobre el ticket original, devuelve el artículo al stock y deja el vale en la ficha del cliente. Es gratuito hasta 1.000 artículos, para Windows. Instalado antes del 26 de diciembre, cada vale de la campaña queda registrado, y en marzo sabes cuántos quedan vivos."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Puedo dar un vale en vez de devolver el dinero?",
     "En tienda física y sin defecto en el producto, sí, si tu política lo dice y está a la vista antes de la compra. Con defecto entra la garantía y el cliente puede exigir reparación, sustitución o devolución del dinero."),
    ("¿Cuánto puede durar un vale?",
     "No hay un plazo fijado en la norma general, y las oficinas de consumo piden plazos razonables. Un año es habitual y defendible; treinta días invita a la reclamación. Consúltalo con tu asesor."),
    ("¿Qué pasa si el cliente pierde el vale?",
     "Si está apuntado en su ficha con su importe y su fecha, se localiza y se usa igual. Si solo existe en papel, es palabra contra palabra."),
    ("¿Cómo sé cuántos vales tengo en circulación?",
     "Si cada vale está registrado en la ficha del cliente y se marca como usado al gastarse, la cifra sale del programa. Con vales a mano, no la sabe nadie."),
    ("¿El vale devuelve cambio si se gasta menos?",
     "Lo decide la tienda y debe constar en las condiciones del vale. Lo habitual es que el resto quede como saldo, no en dinero."),
  ],
  relacionadas=[("Política de devoluciones para Navidad", "blog/politica-devoluciones-campana-navidad.html", "La regla antes de la campaña"),
                ("Cambios después de Reyes", "blog/cambios-despues-de-reyes-semana-del-7-de-enero.html", "La semana de los vales"),
                ("TPV para boutiques", "tpv-boutique.html", "Ficha de clienta, devoluciones y vales"),
                ("Descargar Carrito5", "descargar-tpv-gratis.html", "Antes del 26 de diciembre")]),

# ------------------------------------------------------------------ 15 dic
"verifactu-1-enero-2027-que-cambia-en-la-caja": dict(
  title="VeriFactu el 1 de Enero de 2027: Qué Cambia en la Caja",
  desc="Para las sociedades, desde el 1 de enero de 2027 cada ticket lleva QR y registro encadenado. Qué ve el cliente, qué ve Hacienda y qué hace quien cobra.",
  kw="verifactu 1 enero 2027, que cambia verifactu, ticket qr verifactu, verifactu en la caja, verifactu tienda que hacer, verifactu sociedades enero",
  h1="1 de enero de 2027: lo que cambia en la caja con VeriFactu",
  sub="A dos semanas de la fecha, lo que conviene saber no es la ley entera sino qué pasa el día 2 cuando abras y cobres el primer ticket.",
  publicado="2026-12-15",
  para="Sociedades con tienda; autónomos que quieran adelantarse",
  resumen=[
    "Desde el 1 de enero de 2027, las sociedades tienen que emitir sus tickets y facturas con un sistema adaptado a VeriFactu. En la práctica, cada ticket sale con un código QR y una mención a VeriFactu, y el programa guarda cada venta como un registro encadenado al anterior, con huella, que no se puede borrar ni alterar sin dejar rastro.",
    "Para quien cobra no cambia nada si el programa está adaptado: se cobra igual. Lo que cambia es que ya no se puede anular una venta borrándola; se anula con un registro de anulación. Los autónomos tienen hasta el 1 de julio de 2027. Información general, no asesoramiento fiscal.",
  ],
  cuerpo=[
    ("Lo que ve el cliente",
     ["Un código QR en el ticket, junto a un texto que indica que es una factura verificable o VeriFactu. El cliente puede escanear ese QR con el móvil y comprobar en la web de la Agencia Tributaria que el ticket existe y sus datos coinciden. Poca gente lo hará, pero el QR tiene que estar y ser legible: una impresora térmica con el cabezal sucio imprime un QR que no se lee, y eso es un ticket que no cumple.",
      "Por lo demás, el ticket es el mismo: la factura simplificada de siempre, con los datos que ya exigía la norma."],
     None),
    ("Lo que ve Hacienda",
     ["Menos de lo que se dice. El programa genera por cada venta un registro de facturación con unos datos concretos, lo encadena con el anterior mediante una huella, y en la modalidad VeriFactu lo remite a la Agencia Tributaria. No hay acceso en directo a la caja ni a la contabilidad, no se ven los artículos vendidos con detalle comercial, y no hay ninguna tasa ni cuota por remitir.",
      "Lo que sí cambia de verdad: una venta hecha no se puede borrar. Si se cobró mal, se anula con un registro de anulación que también queda encadenado. El programa lo hace solo; lo importante es que quien cobra sepa que «borrar el ticket» ya no existe."],
     ["<strong>Registro por venta</strong>, encadenado con huella al anterior.",
      "<strong>Anulaciones</strong> como registro, no como borrado.",
      "<strong>Sin acceso en directo</strong> ni tasa ni cuota."]),
    ("Lo que tiene que hacer quien cobra el día 2",
     ["Nada especial, si el programa está adaptado y actualizado. Cobra, imprime, y el programa hace el resto. Lo que conviene revisar el día 2 por la mañana, antes del primer cliente: que los datos fiscales de la empresa en el programa sean correctos, que el ticket de prueba lleve el QR y se lea, y que la declaración responsable del fabricante esté guardada.",
      "Si el programa no está adaptado, ya no es momento de esperar: hay que instalar uno que sí lo esté, aunque sea entre Navidad y Reyes, y dar de alta primero las referencias que más rotan."],
     None),
    ("Lo que no cambia",
     ["No cambia el IVA, no cambian los tipos, no cambia la factura simplificada ni cuándo hay que hacer factura completa. No hay que enviar nada a mano ni entrar en ninguna web cada día. No hay que comprar hardware nuevo salvo que la impresora no saque el QR legible. Y no hay que contratar ningún servicio con nadie: lo que exige la norma lo incorpora el programa.",
      "Un proveedor que a estas alturas te ofrezca «el módulo VeriFactu» como extra de pago te está vendiendo algo que debería venir dentro."],
     None),
  ],
  cierre=("Si el día 2 tu programa no saca el QR",
          ["Carrito5 está adaptado a VeriFactu, emite el ticket con su QR desde la primera venta y es gratuito hasta 1.000 artículos. Se instala en el ordenador de la tienda en unos minutos, también entre Navidad y Reyes. Si tu sociedad llega al 1 de enero sin programa adaptado, es la salida más rápida y no cuesta nada."],
          "Descargar Carrito5 y sacar un ticket de prueba", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué cambia en el ticket el 1 de enero de 2027?",
     "Lleva un código QR y una mención a VeriFactu. El resto del ticket es la factura simplificada de siempre."),
    ("¿Hacienda ve mis ventas en tiempo real?",
     "No. El programa genera un registro por venta, encadenado al anterior, y lo remite. No hay acceso en directo a la caja ni a la contabilidad."),
    ("¿Puedo anular un ticket que he cobrado mal?",
     "Sí, pero como anulación registrada, no como borrado. El programa lo hace solo; lo importante es saber que borrar ya no existe."),
    ("¿Tengo que hacer algo el día 2 por la mañana?",
     "Comprobar los datos fiscales en el programa, sacar un ticket de prueba y ver que el QR se lee, y tener guardada la declaración responsable del fabricante. Nada más si el programa está adaptado."),
    ("Soy autónomo. ¿Me afecta el 1 de enero?",
     "No, tu fecha es el 1 de julio de 2027. Puedes adelantarte de forma voluntaria, y evitas cambiar de programa el día que arrancan las rebajas de verano."),
  ],
  relacionadas=[("Cien días para las sociedades", "blog/verifactu-100-dias-sociedades-1-enero-2027.html", "La cuenta atrás de septiembre"),
                ("VeriFactu: cuándo entra en vigor", "verifactu-entrada-en-vigor.html", "El calendario completo"),
                ("Factura simplificada y ticket", "factura-simplificada-ticket.html", "Lo que tiene que llevar el ticket"),
                ("Funciona sin internet", "verifactu-sin-conexion-internet-offline.html", "Cobrar con la línea caída")]),

# ------------------------------------------------------------------ 22 dic
"inventario-fin-de-ano-tienda-sin-cerrar": dict(
  title="Inventario de Fin de Año en la Tienda sin Cerrar",
  desc="Por qué hacer inventario a 31 de diciembre, qué pide el asesor y cómo contar la tienda por familias en tres tardes sin cerrar, con el stock del programa.",
  kw="inventario fin de año tienda, como hacer inventario tienda, inventario 31 diciembre, inventario tienda pequeña, recuento stock tienda, inventario sin cerrar",
  h1="Inventario de fin de año: contar la tienda sin cerrarla",
  sub="El asesor lo pide en enero, la ley lo exige a las sociedades y a la tienda le sirve para saber cuánto dinero tiene en el almacén. Se puede hacer sin colgar el cartel de cerrado por inventario.",
  publicado="2026-12-22",
  para="Todo el comercio, especialmente sociedades",
  resumen=[
    "El inventario a 31 de diciembre es la lista valorada de todo lo que hay en la tienda y en el almacén ese día. Las sociedades están obligadas a llevarlo en el libro de inventarios, y a cualquier comercio le sirve para saber cuánto dinero tiene inmovilizado y qué no se vende.",
    "No hace falta cerrar: se cuenta por familias en tres tardes entre el 26 y el 31, con el stock del programa como lista de partida, y se corrigen las diferencias. Con las ventas registradas todo el año, el recuento es comprobar, no contar desde cero. Información general; el detalle contable, con tu asesor.",
  ],
  cuerpo=[
    ("Por qué se hace y quién está obligado",
     ["El Código de Comercio obliga a las sociedades a llevar un libro de inventarios y cuentas anuales, y el inventario de existencias a cierre de ejercicio es parte de él. Para un autónomo en estimación directa también cuenta: las existencias finales entran en el cálculo del rendimiento. En los dos casos lo pide el asesor en enero, y en los dos casos hay que darle una lista con cantidades y valor.",
      "Aparte de la obligación, hay una razón de negocio: el inventario dice cuánto dinero hay parado en el almacén, y qué parte de ese dinero lleva más de un año sin moverse. Para una tienda pequeña es la cifra más importante del año y la que menos se mira."],
     None),
    ("El método: contar por familias, sin cerrar",
     ["Cerrar por inventario un día entre Navidad y Reyes es perder uno de los mejores días del año. La alternativa es contar por familias en varias tardes, con el stock del programa como lista de partida.",
      '<ol class="c5-pasos">'
      '<li><strong>Saca del programa el stock por familia</strong> el 26 por la mañana. Esa es la lista que vas a comprobar, no a construir.</li>'
      '<li><strong>Cuenta una familia por tarde</strong>, después de cerrar: el 26, el 28 y el 30, por ejemplo. Las ventas de esos días se descuentan solas.</li>'
      '<li><strong>Anota solo las diferencias</strong> entre lo contado y lo que dice el programa. Si el stock ha estado bien llevado, son pocas.</li>'
      '<li><strong>Corrige el stock</strong> en el programa con las diferencias, y apunta el motivo si lo sabes: rotura, robo, error de alta.</li>'
      '<li><strong>El 31, la lista final</strong> con cantidades y precio de compra es el inventario. Se guarda y se manda al asesor.</li>'
      '</ol>',
      "Con la matriz de tallas y colores, la ropa se cuenta por modelo y se comprueba talla a talla contra la pantalla. Es la familia que más diferencias suele dar y la que más vale contar bien."],
     None),
    ("Las diferencias: lo que enseñan",
     ["Si el programa dice ocho y hay seis, faltan dos. Puede ser un robo, un error al dar de alta, una devolución mal hecha o una venta cobrada sin pasar por el programa. Si es esto último, es la señal de que en la tienda se cobra a veces «de cabeza», y eso en 2027 es un problema con VeriFactu además de un problema de stock.",
      "Si el programa dice seis y hay ocho, sobran dos: una entrada que no se dio de alta, o una devolución que no se registró. Menos grave, pero igual de informativo."],
     ["<strong>Faltan</strong>: robo, error de alta, venta sin registrar.",
      "<strong>Sobran</strong>: entrada sin dar de alta, devolución sin registrar.",
      "<strong>Cuadra</strong>: la tienda lleva el stock bien y el inventario del año que viene es un trámite."]),
    ("Lo que dice el inventario sobre 2027",
     ["Con la lista valorada delante, dos preguntas. Cuánto dinero hay en referencias que llevan más de un año sin venderse: eso va a las rebajas de enero al precio que haga falta. Y qué familias tienen el stock más alto respecto a lo que venden: ahí se compra de más, y el pedido de primavera se recorta.",
      "Son las dos decisiones que más dinero mueven en una tienda pequeña, y salen de una lista que el asesor pide de todas formas."],
     None),
  ],
  cierre=("Para que el inventario del año que viene sea comprobar",
          ["Si este año el inventario es contar desde cero, el problema es que el stock no está en ningún programa. Carrito5 descuenta cada venta de su referencia, registra devoluciones y lleva tallas y colores, y es gratuito hasta 1.000 artículos. Con el recuento de este año cargado como stock inicial, el inventario de 2027 es sacar una lista y comprobarla."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Estoy obligado a hacer inventario a 31 de diciembre?",
     "Las sociedades sí, dentro del libro de inventarios y cuentas anuales. A los autónomos en estimación directa las existencias finales les entran en el cálculo del rendimiento. En los dos casos lo pide el asesor. Confirma tu caso con él."),
    ("¿Tengo que cerrar la tienda para hacer inventario?",
     "No. Se cuenta por familias en varias tardes después de cerrar, con el stock del programa como lista de partida, y las ventas de esos días se descuentan solas."),
    ("¿Qué valor pongo a cada artículo?",
     "El precio de compra, no el de venta. Es lo que pide la contabilidad. Tu asesor te dirá el criterio exacto."),
    ("¿Qué hago con las diferencias?",
     "Corregir el stock en el programa y apuntar el motivo si se sabe. Muchas diferencias en una familia señalan un problema: robo, altas mal hechas o ventas sin registrar."),
    ("¿Cómo cuento la ropa con tallas?",
     "Por modelo, comprobando talla a talla contra la matriz del programa. Es la familia que más diferencias da."),
  ],
  relacionadas=[("Rebajas de enero 2027", "blog/rebajas-enero-2027-fechas-ley-preparar.html", "Adónde va lo que no se vende"),
                ("Matriz de tallas y colores", "tallas-y-colores.html", "Contar moda por variante"),
                ("VeriFactu: lo que cambia en la caja", "blog/verifactu-1-enero-2027-que-cambia-en-la-caja.html", "La otra fecha del 31"),
                ("Descargar Carrito5", "descargar-tpv-gratis.html", "Cargar el recuento como stock inicial")]),

# ------------------------------------------------------------------ 29 dic
"cambios-despues-de-reyes-semana-del-7-de-enero": dict(
  title="Cambios después de Reyes: la Semana del 7 de Enero",
  desc="Del 7 al 10 de enero de 2027 la tienda de regalo hace más cambios que ventas. Cómo ordenar la cola de cambios, los vales y el arranque de rebajas.",
  kw="cambios despues de reyes, devoluciones enero tienda, semana cambios reyes comercio, cambios regalos reyes tienda, 7 enero tienda cambios rebajas",
  h1="La semana del 7 de enero: cambios, vales y rebajas a la vez",
  sub="Reyes cae en miércoles. El jueves 7 abre la tienda con tres colas mezcladas: quien cambia, quien viene a las rebajas y quien quiere las dos cosas. Se puede ordenar.",
  publicado="2026-12-29",
  para="Regalo, moda, juguetería, joyería, perfumería",
  resumen=[
    "El 6 de enero de 2027 es miércoles, así que la semana de cambios empieza el jueves 7 y se concentra el viernes 8 y el sábado 9. Coincide con el arranque habitual de las rebajas de invierno, y eso crea un problema práctico: el cambio se valora al precio de compra original, no al precio rebajado, y hay que tenerlo claro y escrito.",
    "Lo que ordena la semana: la política de cambios ya anunciada en diciembre, cada venta localizable en la ficha del cliente, el vale apuntado en el momento, y una regla simple para el precio: se cambia por el importe pagado.",
  ],
  cuerpo=[
    ("El problema del precio: cambio y rebaja en el mismo día",
     ["Un cliente compró un jersey a 60 euros el 20 de diciembre. El 8 de enero lo trae para cambiar de talla, y ese mismo jersey está rebajado a 40. ¿Qué vale su cambio? El importe que pagó, 60, porque el cambio es sobre la compra original. Si elige otro artículo rebajado de 40, le quedan 20 en vale; si elige uno de 60 sin rebajar, cambio limpio.",
      "Al revés también pasa: quien devuelve un artículo rebajado no puede reclamar el precio original. La regla es una y hay que decirla: el cambio se valora por lo que consta en el ticket original. Con la venta localizada en el programa, el importe está ahí y no se discute."],
     None),
    ("Ordenar las tres colas",
     ["Los tres primeros días de rebajas con los cambios encima son los de más gente y menos margen de error. Tres cosas que funcionan en tiendas pequeñas:",
      '<ul class="c5-lista">'
      '<li><strong>Cambios por la mañana, si se puede anunciar.</strong> «Cambios de 10 a 13» en el cartel de diciembre concentra los cambios cuando hay menos venta.</li>'
      '<li><strong>Una regla de precio en el cartel</strong>: «los cambios se valoran por el importe del ticket original».</li>'
      '<li><strong>Todo cambio pasa por el programa</strong>: se localiza la venta, se devuelve el artículo al stock, y el vale, si lo hay, queda en la ficha. Nada a mano, aunque haya cola. Un cambio a mano en enero es un vale sin registrar en marzo.</li>'
      '</ul>'],
     None),
    ("Lo que vuelve al stock",
     ["Cada cambio devuelve un artículo a la tienda, y ese artículo tiene que volver al stock con su talla y su color, porque mañana alguien lo va a pedir. Si el cambio se hace a mano, el stock del programa dice que no hay y el jersey está en el almacén. En una semana con cien cambios, eso es un stock que no sirve para nada durante las rebajas.",
      "Con la devolución hecha sobre el ticket original, el artículo vuelve solo a su variante, y a las rebajas se entra con el stock real."],
     None),
    ("Cuando el que viene no es quien compró",
     ["Es la situación más común en enero: viene quien recibió el regalo, sin ticket, y no sabe cuándo se compró. La venta se localiza por la ficha de quien compró, si se registró a su nombre, o por fecha y artículo. Por eso en diciembre convenía registrar las ventas de regalo a nombre del comprador. Y por eso el ticket regalo, si la tienda lo da, ayuda: identifica la venta sin mostrar el precio.",
      "Si no se localiza de ninguna forma, entra la política: sin ticket ni localización, cambio al precio actual del artículo, o no hay cambio, según lo que se anunció. Lo importante es que la regla sea la misma para todos y estuviera escrita en diciembre."],
     None),
  ],
  cierre=("Cien cambios sin un papel a mano",
          ["Carrito5 localiza la venta original por ticket o por ficha del cliente, devuelve el artículo al stock con su talla y color, y deja el vale registrado. Todo en el plan gratuito, hasta 1.000 artículos, para Windows. Si la semana del 7 de enero la vas a hacer con libreta, todavía estás a tiempo de instalarlo entre Navidad y Reyes."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cuándo empiezan los cambios de Reyes en 2027?",
     "Reyes es el miércoles 6 de enero, así que los cambios empiezan el jueves 7 y se concentran el viernes 8 y el sábado 9."),
    ("Si el artículo está rebajado, ¿por cuánto se cambia?",
     "Por el importe que consta en el ticket original. La rebaja no sube ni baja el valor del cambio. Ponlo en el cartel."),
    ("¿Qué hago si viene la persona que recibió el regalo, sin ticket?",
     "Localizar la venta por la ficha del comprador o por fecha y artículo. Si no se localiza, aplicar la política anunciada, igual para todos."),
    ("¿Por qué no hacer los cambios a mano si hay cola?",
     "Porque el artículo no vuelve al stock y el vale no queda registrado. En marzo es un vale que nadie sabe si se usó y un jersey que el programa dice que no hay."),
    ("¿Puedo poner horario de cambios?",
     "Sí, si lo anuncias con la política de diciembre. Cambios por la mañana concentra la cola cuando menos venta hay."),
  ],
  relacionadas=[("Política de devoluciones para Navidad", "blog/politica-devoluciones-campana-navidad.html", "La regla escrita en noviembre"),
                ("El vale de devolución, cómo llevarlo", "blog/vale-de-devolucion-tienda-como-funciona.html", "Registrado desde el primero"),
                ("Rebajas de enero 2027", "blog/rebajas-enero-2027-fechas-ley-preparar.html", "La otra cola del 7"),
                ("TPV para tiendas de ropa", "tpv-tienda-ropa.html", "Cambios de talla en pantalla")]),

}
