# -*- coding: utf-8 -*-
"""Blog de carrito5.com: segunda capa de diciembre de 2026.

Perfumeria, tienda de mascotas y herboristeria de cara a enero. Mismas
reglas de funciones confirmadas que blog_2026_09.py.
"""

BLOG_2026_12B = {

# ------------------------------------------------------------------ 3 dic
"perfumeria-navidad-cofres-fragancia-de-siempre": dict(
  title="Perfumería en Navidad: Cofres, Fragancias y Quién Usa Cuál",
  desc="La perfumería vende cofres en diciembre a quien no sabe qué fragancia usa a quien regala. La ficha con la fragancia habitual y cada cofre con su código.",
  kw="perfumeria navidad ventas, cofres navidad perfumeria, regalar perfume navidad tienda, perfumeria diciembre campaña, tpv perfumeria",
  h1="Perfumería en Navidad: la fragancia de siempre y el cofre de este año",
  sub="«¿Cuál usa mi madre?» es la pregunta de diciembre en una perfumería. Si su madre compra ahí, la respuesta está en la ficha. Si no, este es el año de apuntarlo.",
  publicado="2026-12-03",
  para="Perfumerías, droguerías y cosmética",
  resumen=[
    "En perfumería la Navidad es el mes de los cofres y de la fragancia repetida: buena parte de los regalos son el perfume de siempre en formato regalo, comprado por alguien que no lo usa. La ficha de cliente con la fragancia habitual de cada clienta resuelve la venta; el cofre con código propio y etiqueta resuelve la caja; y la política de cambios, sin abrir y con precinto, resuelve enero.",
    "Los cofres llegan en noviembre y cada uno es una referencia nueva: se dan de alta al llegar con su código y su etiqueta, o en diciembre se cobran buscando.",
  ],
  cuerpo=[
    ("La fragancia de siempre, comprada por otra persona",
     ["El hijo entra y pregunta por «uno que huele a...». La perfumería que tiene a la madre en la ficha de cliente, con sus compras del año, sabe cuál es y en qué tamaño lo lleva. Vende el cofre de esa fragancia y, de paso, la crema de la misma línea. La que no la tiene, adivina.",
      "Este es el año de empezar: cada venta de una clienta habitual a su nombre, con el artículo. En marzo, cuando venga a reponer, ya está; y en diciembre de 2027, cuando venga el hijo, también."],
     None),
    ("Los cofres: cada uno es una referencia nueva",
     ["Los cofres de Navidad llegan en noviembre y muchos traen un código de barras distinto del perfume suelto, o no traen ninguno útil. Cada cofre se da de alta como referencia nueva al llegar, con su precio, y si el código no se lee, código propio y etiqueta. Son cuarenta o sesenta referencias en una perfumería de barrio: una tarde.",
      "Lo que se gana: el 19 de diciembre, con la tienda llena, el cofre se cobra pasando el lector; y el 26, el stock dice qué cofres quedan para rebajarlos en enero antes de que se queden de un año a otro."],
     ["<strong>Alta al llegar</strong>, cofre a cofre, con su precio.",
      "<strong>Etiqueta propia</strong> si el código no se lee.",
      "<strong>Stock por cofre</strong> para saber qué rebajar en enero."]),
    ("La política de cambios en perfumería: sin abrir",
     ["El perfume tiene una regla propia que hay que escribir en el ticket: cambio solo sin abrir y con el precinto intacto, hasta el 10 de enero. Un frasco abierto no se puede revender, y el cliente lo entiende si lo lee antes. Con la venta registrada a nombre de quien compró, el cambio de enero se localiza sin ticket y se hace sobre la venta original, con vale si hay diferencia."],
     None),
    ("Enero: lo que sobra y las clientas que reponen",
     ["Los cofres que queden el 7 de enero se rebajan con etiqueta nueva y precio anterior, porque en febrero ya no son de Navidad. Y las clientas habituales vuelven en enero a reponer lo suyo: con la ficha delante, se sabe qué y se propone la novedad de su línea. Es la venta tranquila que paga el alquiler de enero."],
     None),
  ],
  cierre=("La fragancia de cada clienta, en su ficha",
          ["Carrito5 guarda cada venta en la ficha de la clienta con el artículo, da de alta los cofres con código propio y etiqueta, lleva el stock por referencia y hace el cambio de enero sobre el ticket original. Es gratuito hasta 1.000 artículos, para Windows. Instalado esta semana, los cofres de este año entran etiquetados y las clientas de diciembre quedan apuntadas."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cómo sé qué perfume usa la persona a la que le regalan?",
     "Si esa persona compra en la tienda, está en su ficha de cliente con sus compras. Si no, este año se apunta la venta a nombre de quien regala y para quién."),
    ("Los cofres traen códigos distintos. ¿Cómo los doy de alta?",
     "Como referencia nueva cada uno, al llegar en noviembre, con su precio. Si el código no se lee, código propio y etiqueta impresa."),
    ("¿Qué política de cambios pongo en perfumería?",
     "Cambio solo sin abrir y con precinto, hasta una fecha, escrito en el ticket. Un frasco abierto no se revende."),
    ("¿Qué hago con los cofres que sobran?",
     "Rebajarlos el 7 de enero con etiqueta nueva y precio anterior. En febrero ya no son de Navidad."),
    ("¿Carrito5 sirve para una perfumería?",
     "Sí: ficha de cliente con historial, códigos de barras y etiquetas, stock, devoluciones y vales. Plan gratuito hasta 1.000 artículos."),
  ],
  relacionadas=[("TPV para droguerías y perfumerías", "tpv-drogueria.html", "El sector"),
                ("Halloween en cosmética", "blog/halloween-cosmetica-maquillaje-tienda.html", "La campaña anterior"),
                ("Política de devoluciones para Navidad", "blog/politica-devoluciones-campana-navidad.html", "La regla escrita"),
                ("Día de la Madre 2027", "blog/dia-de-la-madre-2-mayo-2027-tienda-un-mes.html", "La siguiente campaña de perfumería")]),

# ------------------------------------------------------------------ 17 dic
"tienda-mascotas-navidad-regalos-y-comida": dict(
  title="Mascotas en Navidad: el Regalo y el Pienso de Siempre",
  desc="En diciembre la tienda de mascotas vende regalos para el perro a clientes que vienen cada mes por el saco. La ficha con lo que come cada animal.",
  kw="tienda mascotas navidad, regalos perros navidad tienda, tienda animales diciembre ventas, pienso cliente habitual ficha, tpv tienda mascotas",
  h1="Tienda de mascotas en Navidad: el regalo del perro y el pienso de siempre",
  sub="El cliente de una tienda de mascotas es el más fiel del comercio: viene cada mes por el mismo saco. En diciembre, además, compra regalo. Hay que saber qué come su animal y tener el regalo etiquetado.",
  publicado="2026-12-17",
  para="Tiendas de mascotas y animales",
  resumen=[
    "La tienda de mascotas tiene en diciembre dos ventas: la de siempre, el pienso y los accesorios del mes, y la de Navidad, juguetes, camas, jerséis y golosinas de regalo. El cliente es el mismo, viene cada mes, y su ficha con lo que come cada animal y cuándo lo compró es lo que hace la venta rápida y el aviso oportuno.",
    "El expositor de Navidad se monta con género etiquetado con código propio, porque los juguetes y golosinas de importación rara vez traen código útil, y en enero lo que sobre se guarda con su stock para el año que viene.",
  ],
  cuerpo=[
    ("El cliente que viene cada mes",
     ["Una tienda de mascotas vive de un cliente que compra el mismo saco de 12 kilos cada cuatro o cinco semanas, el mismo antiparasitario cada tres meses y la misma arena cada quince días. Es el negocio más previsible del comercio de barrio, y el que menos tiendas aprovechan: la ficha de cliente con lo que come cada animal, en qué tamaño y cuándo lo compró por última vez, dice cuándo va a volver y qué va a pedir.",
      "En diciembre, además, ese cliente compra regalo para el animal. Con la ficha delante, la venta es «el saco de siempre y, para Navidad, tenemos esto para un perro de su tamaño»."],
     None),
    ("El expositor de Navidad: etiquetado",
     ["Juguetes, golosinas, camas, jerséis y calendarios de adviento para perro: casi todo llega de importación con código de barras que no está en ninguna base o directamente sin él. Cada referencia recibe código propio y etiqueta al llegar, en noviembre, y va al expositor. Cuarenta referencias, una hora. Sin eso, el sábado 19 cada juguete de cinco euros es una búsqueda en la caja con la cola de sacos de pienso detrás."],
     ["<strong>Código propio y etiqueta</strong> para el género de regalo, al llegar.",
      "<strong>Expositor separado</strong> del pienso, junto a la caja.",
      "<strong>Aviso por WhatsApp</strong> a los clientes del mes con una foto del expositor."]),
    ("Las fiestas del animal: comida y precaución",
     ["En Navidad se vende más comida húmeda, más golosinas y más «premios», y el cliente pregunta qué puede dar y qué no. El consejo vende: el uvas y el chocolate no, el pavo cocido sin hueso sí. La tienda que lo explica se lleva la venta de la golosina segura y la confianza para el resto del año.",
      "Y los sacos de siempre: diciembre es un mes en que la gente se va y compra el saco antes, o vuelve tarde. La ficha con la última compra dice quién debería haber venido y no ha venido, y un mensaje evita que compre en la gran superficie del camino."],
     None),
    ("Enero: guardar y devolver",
     ["Lo que sobre del expositor de Navidad se guarda con su código y su stock: los juguetes valen para el año que viene y los jerséis para el frío de enero. Y los cambios, pocos, sobre el ticket original: el jersey que no era la talla del perro, el juguete repetido. Con el cliente en su ficha, se localiza sin ticket."],
     None),
  ],
  cierre=("Lo que come cada animal, en la ficha",
          ["Carrito5 guarda cada venta en la ficha del cliente con el artículo y la fecha, da de alta el género de regalo con código propio y etiqueta, y lleva el stock de lo que sobre. Es gratuito hasta 1.000 artículos, para Windows. Instalado esta semana, los clientes de diciembre quedan apuntados y en enero se sabe quién tiene que volver a por su saco."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué vende una tienda de mascotas en Navidad?",
     "Lo de siempre, pienso y accesorios, más regalo: juguetes, camas, jerséis, golosinas y calendarios de adviento para perro. El cliente es el mismo que viene cada mes."),
    ("¿Cómo sé cuándo va a volver un cliente a por su saco?",
     "Con la ficha de cliente: qué compra, en qué tamaño y cuándo lo compró por última vez. Un saco de 12 kilos dura cuatro o cinco semanas."),
    ("El género de regalo no trae código de barras. ¿Cómo lo cobro?",
     "Con código propio y etiqueta impresa desde el programa, al llegar en noviembre. Cuarenta referencias, una hora."),
    ("¿Qué hago con lo que sobra del expositor de Navidad?",
     "Guardarlo con su código y su stock para el año que viene. Los jerséis se venden en enero con el frío."),
    ("¿Carrito5 sirve para una tienda de mascotas?",
     "Sí: ficha de cliente con historial, códigos de barras y etiquetas, stock, devoluciones. Plan gratuito hasta 1.000 artículos."),
  ],
  relacionadas=[("TPV para tiendas de mascotas", "tpv-tienda-mascotas.html", "El sector"),
                ("Navidad: las tres semanas", "blog/navidad-tres-semanas-que-deciden-el-ano.html", "La campaña general"),
                ("Etiquetar antes de la campaña", "blog/etiquetar-genero-antes-de-campana.html", "Códigos y etiquetas"),
                ("Cuesta de enero", "blog/cuesta-de-enero-comercio-costes-fijos-revisar.html", "Lo que viene en enero")]),

# ------------------------------------------------------------------ 30 dic
"herboristeria-enero-propositos-clientes-que-vuelven": dict(
  title="Herboristería en Enero: la Ola de los Propósitos",
  desc="La segunda semana de enero entra quien quiere adelgazar, dejar de fumar o dormir mejor. Atender esa ola con consejo, ficha de cliente y stock justo.",
  kw="herboristeria enero ventas, propositos año nuevo herboristeria, parafarmacia enero dietas, herboristeria clientes que repiten, tpv herboristeria",
  h1="Herboristería en enero: la ola de los propósitos",
  sub="Del 7 al 31 de enero entra gente nueva con una intención concreta y poca idea. La herboristería que la atiende con calma y la apunta la tiene de clienta todo el año.",
  publicado="2026-12-30",
  para="Herboristerías, parafarmacias y dietética",
  resumen=[
    "En enero la herboristería y la parafarmacia tienen su segunda campaña del año, después de la de otoño: la gente que entra con un propósito de año nuevo, adelgazar, dejar de fumar, dormir mejor, hacer deporte. Es cliente nuevo, con intención, que compra el primer producto por consejo y vuelve si el consejo fue bueno.",
    "Lo que decide la campaña: el consejo, que es lo que la gran superficie no da; la ficha de cliente con lo que se llevó y para qué, para que la segunda visita empiece donde acabó la primera; y el stock de los productos de enero pedido en diciembre, sin pasarse, porque en febrero la ola baja.",
  ],
  cuerpo=[
    ("Quién entra en enero",
     ["No es la clienta habitual de la herboristería, que sigue viniendo a por lo suyo. Es gente que no ha pisado la tienda nunca y que entra la segunda semana de enero con una frase: «quiero perder lo de las fiestas», «me he propuesto dejar de fumar», «duermo fatal». Viene con intención de comprar y sin saber qué. Es la mejor clienta nueva del año, si se la atiende bien.",
      "Atenderla bien es escuchar dos minutos, proponer una cosa y no cinco, y explicar cómo se toma. Y apuntarla."],
     None),
    ("La ficha: lo que se llevó y para qué",
     ["En herboristería la segunda visita es la que hace la clienta. Si la primera se apuntó en su ficha, con el producto y una nota de para qué, cuando vuelve a las tres semanas la conversación empieza en «¿cómo te ha ido con...?», no en «¿qué se llevó?». Esa continuidad es lo que la gran superficie no puede dar y lo que convierte a la de enero en clienta de todo el año.",
      "Carrito5 guarda cada venta en la ficha del cliente con el artículo; la nota del motivo la escribe la tienda. Con eso, y con el historial, cada visita empieza donde acabó la anterior."],
     ["<strong>Registrar la primera compra</strong> a nombre de la clienta nueva.",
      "<strong>Nota del motivo</strong> en la venta: peso, tabaco, sueño, deporte.",
      "<strong>Segunda visita</strong>: preguntar cómo ha ido antes de vender nada."]),
    ("El stock de enero, pedido en diciembre",
     ["Los productos de enero son conocidos: drenantes, saciantes, sustitutivos, complementos para el sueño, chicles y parches. Se piden en la segunda quincena de diciembre con lo que se vendió en enero pasado por referencia, y se piden justos, porque la ola dura hasta finales de enero y en febrero se queda el stock. Los complementos tienen fecha de caducidad y lo que sobra en marzo es merma en octubre.",
      "Con las ventas de enero pasado en el programa, el pedido es una lista. Sin ellas, es lo que dijo el comercial."],
     None),
    ("Febrero: la ola baja y la ficha se queda",
     ["A mediados de febrero la gente nueva deja de entrar. Lo que queda es la ficha: las clientas de enero que volvieron una segunda vez son clientas del año, y las que no volvieron reciben un mensaje en marzo, sin insistir. Y el stock de enero que no se ha vendido se mira ahora, no en octubre."],
     None),
  ],
  cierre=("La clienta de enero, apuntada en su primera compra",
          ["Carrito5 guarda cada venta en la ficha de la clienta con el artículo y la nota que añada la tienda, lleva el stock por referencia para pedir enero con lo del año pasado, y lee códigos de barras para que la caja vaya rápida. Es gratuito hasta 1.000 artículos, para Windows. Instalado antes del 7 de enero, la ola de propósitos entra apuntada."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cuándo empieza la campaña de enero en la herboristería?",
     "La segunda semana de enero, después de Reyes, y dura hasta finales de mes. En febrero la gente nueva deja de entrar."),
    ("¿Qué compra la gente en enero?",
     "Drenantes, saciantes, sustitutivos, complementos para dormir, chicles y parches para dejar de fumar. Con intención y sin saber cuál."),
    ("¿Cómo convierto a la clienta de enero en clienta del año?",
     "Con consejo en la primera visita y con su compra apuntada en la ficha, con una nota del motivo. La segunda visita empieza en «¿cómo te ha ido?»."),
    ("¿Cuándo pido el stock de enero?",
     "En la segunda quincena de diciembre, con lo que se vendió en enero pasado por referencia, y justo: los complementos caducan y en febrero baja la ola."),
    ("¿Carrito5 sirve para una herboristería?",
     "Sí: ficha de cliente con historial, códigos de barras y etiquetas, stock, devoluciones. Plan gratuito hasta 1.000 artículos."),
  ],
  relacionadas=[("TPV para herboristerías", "tpv-herboristeria.html", "El sector"),
                ("TPV para parafarmacias", "tpv-tienda-parafarmacia.html", "Parafarmacia y dietética"),
                ("Cuesta de enero", "blog/cuesta-de-enero-comercio-costes-fijos-revisar.html", "El otro enero"),
                ("Balance del primer semestre", "blog/balance-primer-semestre-2027-tienda-que-mirar.html", "Clientes con ficha que repiten")]),

}
