# -*- coding: utf-8 -*-
"""Blog de carrito5.com: febrero de 2027.

Carnaval (6 al 9 de febrero de 2027), el Dia del Padre con un mes de margen y
el cambio de temporada con el stock de invierno. Mismas reglas de funciones
confirmadas que blog_2026_09.py.
"""

BLOG_2027_02 = {

# ------------------------------------------------------------------ 2 feb
"carnaval-2027-tienda-disfraces-segunda-campana": dict(
  title="Carnaval 2027 (6-9 Febrero): Segunda Campaña de Disfraces",
  desc="Carnaval 2027 cae del 6 al 9 de febrero. Cómo sacar el género que sobró de Halloween sin darlo de alta otra vez.",
  kw="carnaval 2027 fecha, carnaval 2027 tienda disfraces, vender disfraces carnaval, campaña carnaval comercio, disfraces carnaval tallas, tpv disfraces",
  h1="Carnaval 2027: la segunda campaña de la tienda de disfraces",
  sub="Del sábado 6 al martes 9 de febrero, con los colegios celebrándolo el viernes 5. Lo que sobró de Halloween ya está dado de alta; solo hay que sacarlo y reponer tallas.",
  publicado="2027-02-02",
  para="Tiendas de disfraces, fiesta y complementos",
  resumen=[
    "Carnaval de 2027 va del sábado 6 al martes 9 de febrero, con el Miércoles de Ceniza el 10. Los colegios lo celebran el viernes 5, así que la venta de disfraz infantil se concentra del lunes 1 al jueves 4, y la de adulto el jueves 4 y el viernes 5.",
    "Para la tienda de disfraces es la segunda campaña del año tras Halloween, con una ventaja: el género que sobró en octubre ya está en el programa con su código y su stock por talla. Se saca, se repone lo que falta por talla, y la política de cambios es la misma que se escribió en octubre.",
  ],
  cuerpo=[
    ("Las fechas de 2027 y cómo se reparte la venta",
     ["Carnaval cambia de fecha cada año porque depende de la Semana Santa, y en 2027 cae pronto: sábado 6, domingo 7, lunes 8 y Martes de Carnaval el 9 de febrero. En Cádiz, Tenerife, Las Palmas, Badajoz, Sitges o Águilas las fiestas se alargan varias semanas, pero la venta de disfraz en toda España se concentra en la semana del 1 al 5, porque los colegios celebran el viernes 5 y las fiestas de adultos empiezan el sábado 6.",
      "Para la tienda: escaparate el 25 de enero, género en tienda el 28, y la semana del 1 al 5 solo cobrar."],
     None),
    ("Lo que sobró de Halloween ya está hecho",
     ["Esta es la ventaja de haber llevado Halloween en el programa. Los disfraces que no se vendieron el 31 de octubre siguen dados de alta con su modelo, sus tallas y su stock. No hay que dar de alta nada: se sacan de las cajas, se colocan, y el programa ya sabe qué tallas quedan de cada uno.",
      "Lo que sí cambia es el tipo de disfraz: Halloween es terror y Carnaval es de todo, así que parte del género es nuevo y llega en enero. Ese sí se da de alta, con el lector para lo que trae código y con etiqueta propia para lo que no. Y las pelucas, el maquillaje y los complementos, que son la mitad del ticket en Carnaval, igual."],
     ["<strong>Género de Halloween</strong>: ya en el programa; sacar y colocar.",
      "<strong>Género nuevo de Carnaval</strong>: alta con lector o etiqueta propia según llega.",
      "<strong>Complementos y maquillaje</strong>: etiqueta propia, que es lo que más cola hace."]),
    ("Reponer por talla, no por modelo",
     ["El error de la segunda campaña es pedir «más de lo que se vendió en Halloween». Lo que se vendió en Halloween se vendió por tallas, y lo que sobró son las tallas que no se piden. Si el disfraz de pirata infantil se agotó en la talla 6 y quedan tres en la 12, reponer el modelo trae más talla 12. Con la matriz de tallas del programa se pide talla a talla, y el pedido de enero es la mitad y se vende entero."],
     None),
    ("Los cambios: la misma regla que en octubre",
     ["Un disfraz comprado el jueves 4 y devuelto el miércoles 10 ya ha ido a la fiesta. La política de cambios de Halloween sirve igual: cambio de talla dentro de 48 horas, sin usar y con etiqueta; sin cambios a partir del viernes 5; sin devolución de dinero. En el cartel y en el ticket. La ley no obliga a más en tienda física salvo defecto, y la tienda decide. Cada cambio que se acepte, sobre el ticket original y con el artículo de vuelta a su talla en el stock."],
     None),
    ("Y después de Carnaval, hasta Halloween",
     ["Entre el 10 de febrero y el 10 de octubre la tienda de disfraces vive de comuniones, despedidas, fiestas temáticas y del género de fiesta. Lo que sobre de Carnaval se guarda con su código y su stock, igual que en octubre, y en septiembre se sabe con qué se empieza Halloween sin abrir una caja. Es la misma lógica de campaña en campaña: el trabajo de dar de alta se hace una vez, y el resto del año es sacar y contar."],
     None),
  ],
  cierre=("Dos campañas al año con el mismo alta",
          ["Si Halloween lo llevaste con calculadora, Carnaval es la segunda oportunidad de empezar. Carrito5 da de alta cada disfraz con su matriz de tallas, lee códigos e imprime etiquetas para complementos y maquillaje, y hace los cambios sobre el ticket original. Es gratuito hasta 1.000 artículos, para Windows. Instalado esta semana, el 1 de febrero cobras pasando el lector, y en octubre el género ya está dentro."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cuándo es Carnaval en 2027?",
     "Del sábado 6 al martes 9 de febrero de 2027. El Miércoles de Ceniza es el 10. Los colegios lo celebran el viernes 5."),
    ("¿Cuándo se venden más disfraces?",
     "Del lunes 1 al jueves 4 el infantil, por los colegios; el jueves 4 y el viernes 5 el de adulto."),
    ("¿Tengo que dar de alta otra vez lo que sobró de Halloween?",
     "No, si se dio de alta en octubre: sigue en el programa con su modelo, sus tallas y su stock. Solo se saca y se coloca."),
    ("¿Cómo hago el pedido de reposición?",
     "Talla a talla, con lo que se agotó en Halloween por modelo y talla. Reponer por modelo trae más de las tallas que sobraron."),
    ("¿Acepto devoluciones de disfraces después de Carnaval?",
     "La tienda decide; en tienda física no hay obligación salvo defecto. Lo habitual es cambio de talla en 48 horas sin usar, y sin cambios a partir del viernes 5, anunciado en el cartel y en el ticket."),
  ],
  relacionadas=[("Halloween en la tienda de disfraces", "blog/halloween-tienda-disfraces-tres-semanas.html", "La primera campaña"),
                ("Matriz de tallas y colores", "tallas-y-colores.html", "Reponer talla a talla"),
                ("Etiquetar antes de la campaña", "blog/etiquetar-genero-antes-de-campana.html", "Complementos y maquillaje"),
                ("Calendario comercial 2026-2027", "blog/calendario-comercial-2026-2027-fechas-clave.html", "Lo que viene después")]),

# ------------------------------------------------------------------ 16 feb
"dia-del-padre-19-marzo-2027-tienda-un-mes": dict(
  title="Día del Padre 2027 (19 de Marzo): un Mes para Prepararlo",
  desc="El 19 de marzo de 2027 es viernes. El regalo se compra el jueves 18 y suele comprarlo alguien que no sabe la talla. Qué preparar en el mes que queda.",
  kw="dia del padre 2027, dia del padre 19 marzo tienda, regalos dia del padre comercio, campaña dia del padre tienda, dia del padre moda hombre, vender dia del padre",
  h1="Día del Padre 2027: una campaña que se compra el día antes",
  sub="El 19 de marzo cae en viernes y es festivo en algunas comunidades. Casi nadie compra el regalo con tiempo, así que la tienda tiene que estar lista para vender rápido el jueves 18.",
  publicado="2027-02-16",
  para="Moda de hombre, complementos, perfumería, electrónica, librería",
  resumen=[
    "El Día del Padre de 2027 es el viernes 19 de marzo, festivo en algunas comunidades autónomas, y la venta se concentra el jueves 18 y el propio viernes donde se abre. Es la campaña de compra más tardía del año: la mayoría compra el día antes, con prisa, y a menudo sin saber la talla o el número.",
    "Con un mes de margen, lo que hay que hacer es corto: pedido de género de regalo para hombre antes del 26 de febrero, escaparate el 8 de marzo, y en la tienda dos cosas listas: la política de cambio de talla y la ficha de cliente de quien ya compró para ese mismo padre el año pasado.",
  ],
  cuerpo=[
    ("Por qué se compra tan tarde",
     ["El Día del Padre no tiene la carga de San Valentín ni la de la Madre, y el regalo se resuelve a última hora, muchas veces el mismo día. En 2027, con la fecha en viernes, el jueves 18 por la tarde es el momento. En las comunidades donde el 19 es festivo, el jueves es el único día; donde no lo es, el viernes por la mañana también vende.",
      "Para la tienda eso quiere decir dos cosas. Que el escaparate tiene que llevar dos semanas puesto para que la gente sepa adónde ir cuando se acuerde. Y que el jueves 18 la venta tiene que ser rápida: dos propuestas, una respuesta clara sobre la talla, un ticket."],
     None),
    ("El comprador no sabe la talla, y la tienda sí",
     ["Es el problema de todas las campañas de regalo y aquí más: compra la hija, el hijo o la pareja, y no sabe si el padre gasta una L o una XL, un 42 o un 43. La solución tiene dos partes. La primera es una política de cambio de talla clara y anunciada: «cambio de talla hasta el 31 de marzo, sin usar y con etiqueta», en el cartel y en el ticket. Con eso el comprador se decide.",
      "La segunda es la ficha de cliente. Si ese padre ya compró en la tienda, o si el año pasado le compraron ahí, su talla está en el historial. Y si no está, este año se registra la venta a su nombre para que el que viene sí esté. Con la matriz de tallas y colores del programa, además, se ve al momento qué tallas quedan de cada modelo, que es lo que pregunta quien viene a cambiar el lunes."],
     ["<strong>Política de cambio de talla</strong> hasta el 31 de marzo, en cartel y ticket.",
      "<strong>Ficha de cliente</strong> del padre, o del comprador, con la talla del año pasado.",
      "<strong>Stock por talla</strong> en pantalla para el cambio del lunes 22."]),
    ("Qué pedir y cuándo",
     ["El género de regalo para hombre en moda es corto y repetido: camisas, jerséis ligeros de entretiempo, cinturones, carteras, calcetines de regalo. En perfumería, las fragancias de siempre. En librería, novedad de marzo y ensayo. El pedido se hace antes del 26 de febrero con lo que se vendió el 18 y el 19 de marzo del año pasado, por referencia y por talla, si quedó apuntado.",
      "Con el pedido en tienda el 8 de marzo, se da de alta con el lector, se etiqueta lo que no trae código, y el escaparate se monta ese mismo día."],
     None),
    ("El lunes 22: cambios de talla, y el pedido para 2028",
     ["El lunes y el martes después del Día del Padre vienen los cambios de talla, casi todos legítimos y rápidos si la venta está localizada y la talla nueva está en stock. Cada cambio sobre el ticket original, con la talla devuelta de vuelta a su stock.",
      "Y con la semana cerrada, la cifra: lo vendido el 18 y el 19 por referencia y por talla. Es el pedido de 2028, y este año se apunta."],
     None),
  ],
  cierre=("La talla del padre, en la ficha",
          ["Carrito5 guarda cada venta en la ficha del cliente, lleva la matriz de tallas y colores de cada modelo y hace el cambio del lunes sobre el ticket original. Es gratuito hasta 1.000 artículos, para Windows, y se instala en una tarde. Con un mes de margen, es tiempo de sobra para llegar al jueves 18 con el género dado de alta y la ficha delante."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué día es el Día del Padre en 2027?",
     "El viernes 19 de marzo de 2027, San José. Es festivo en algunas comunidades autónomas; comprueba la tuya."),
    ("¿Cuándo se compra el regalo del Día del Padre?",
     "El jueves 18 por la tarde, sobre todo, y el viernes 19 por la mañana donde no es festivo. Es la campaña de compra más tardía del año."),
    ("¿Cómo vendo ropa de hombre a alguien que no sabe la talla?",
     "Con una política de cambio de talla clara y anunciada, y con la ficha de cliente si ese padre o ese comprador ya compró en la tienda: la talla está en el historial."),
    ("¿Cuándo hago el pedido?",
     "Antes del 26 de febrero, con lo que se vendió el 18 y el 19 de marzo del año pasado por referencia y por talla."),
    ("¿Qué pasa el lunes 22?",
     "Cambios de talla, rápidos si la venta se localiza por ticket o por ficha y la talla nueva está en stock. Y el balance para el pedido de 2028."),
  ],
  relacionadas=[("San Valentín 2027", "blog/san-valentin-2027-tienda-tres-semanas.html", "La campaña anterior, misma lógica"),
                ("Matriz de tallas y colores", "tallas-y-colores.html", "Qué tallas quedan, en pantalla"),
                ("TPV para tiendas de ropa", "tpv-tienda-ropa.html", "Moda de hombre incluida"),
                ("Calendario comercial 2026-2027", "blog/calendario-comercial-2026-2027-fechas-clave.html", "Semana Santa, a continuación")]),

# ------------------------------------------------------------------ 23 feb
"cambio-de-temporada-primavera-stock-invierno": dict(
  title="Cambio de Temporada: Qué Hacer con el Stock de Invierno",
  desc="A finales de febrero la primavera llega y el invierno sigue en el almacén. Tres destinos para cada referencia y cómo pedir la primavera por talla.",
  kw="cambio de temporada tienda ropa, stock invierno que hacer, liquidar stock temporada, guardar stock temporada siguiente, pedido primavera tienda, fin de temporada comercio",
  h1="Cambio de temporada: tres destinos para el stock de invierno",
  sub="La primavera llega al almacén antes de que el invierno haya salido. Cada referencia que queda tiene que ir a uno de tres sitios, y la decisión se toma ahora, no en abril.",
  publicado="2027-02-23",
  para="Moda, calzado, complementos, hogar",
  resumen=[
    "A finales de febrero una tienda de moda tiene dos temporadas en el almacén: el invierno que no se ha vendido y la primavera que está entrando. Cada referencia de invierno va a uno de tres destinos: última rebaja, hasta que salga, si es de moda y no aguanta un año; guardar con su código y su stock, si es básico y se venderá en octubre; o salida a proveedor o a saldo, si no es ni lo uno ni lo otro.",
    "La decisión se toma con el stock por talla y color del programa delante, y el pedido de primavera se hace con lo que vendió la primavera pasada, por talla, no por modelo. Un TPV con tallas y colores hace las dos cosas.",
  ],
  cuerpo=[
    ("El almacén con dos temporadas",
     ["Es el momento más incómodo del año en una tienda de ropa. Las rebajas han terminado o están en su última semana, la primavera llega en cajas desde mediados de febrero, y el espacio es el que es. Lo que no se decida ahora se queda en el almacén hasta que alguien lo encuentre en septiembre, y para entonces ya ha costado un año de sitio y de dinero parado.",
      "La decisión no se toma modelo a modelo mirando el estante. Se toma con la lista del stock de invierno, por referencia, talla y color, y con una regla para cada tipo de artículo."],
     None),
    ("Los tres destinos",
     ['<div class="c5-tabla-wrap"><table class="c5-tabla"><thead><tr><th>Destino</th><th>Qué va ahí</th><th>Qué se hace en el programa</th></tr></thead><tbody>'
      '<tr><td>Última rebaja, hasta que salga</td><td>Moda de temporada que no se venderá igual el año que viene: estampados, colores de tendencia, modelos de campaña.</td><td>Precio nuevo en la referencia, etiqueta con los dos precios, y fuera del almacén al expositor de salida.</td></tr>'
      '<tr><td>Guardar para octubre</td><td>Básicos que se venden igual cada invierno: jerséis lisos, abrigos clásicos, calzado de invierno básico, ropa interior térmica.</td><td>Nada: la referencia sigue dada de alta con su stock por talla y color. En octubre se saca y se vende sin dar de alta.</td></tr>'
      '<tr><td>Salida</td><td>Tallas sueltas de modelos que no se reponen, artículos con más de dos temporadas, lo que no se ha vendido ni al 50 %.</td><td>Devolución a proveedor si la admite, venta a saldista o a un outlet, o donación. Salida del stock con su motivo.</td></tr>'
      '</tbody></table></div>',
      "La regla que evita discusiones: si una referencia lleva dos temporadas sin venderse ni rebajada, no es candidata a guardar. Guardarla es decidir no decidir, y cuesta el sitio de una referencia que sí se vendería."],
     None),
    ("Guardar bien: el código y el stock se quedan",
     ["Guardar género para la temporada siguiente es la opción más rentable para los básicos y la peor ejecutada. Se mete en cajas sin lista, y en octubre nadie sabe qué hay ni en qué tallas. Con el género dado de alta en el programa, guardar es solo físico: la referencia sigue con su stock por talla y color, y en octubre se saca la lista antes de abrir la caja. El pedido de invierno de 2027 se hace sabiendo qué se tiene.",
      "Un detalle práctico: la caja lleva escrito el nombre de las referencias que contiene, y en el programa se puede anotar en el artículo dónde está. Es un minuto por caja."],
     None),
    ("El pedido de primavera: por talla",
     ["Con el invierno decidido, la primavera. El error habitual es pedir por modelo: «diez de esta camisa». Lo que vende una tienda son tallas, y cada tienda tiene su curva: la de un barrio no es la de otro. Con las ventas de la primavera pasada por talla en el programa, el pedido dice que de esa camisa se vendieron dos S, cinco M, cuatro L y ninguna XL, y se pide eso. El proveedor prefiere vender por pack de tallas; hay que negociar, y tener la cifra ayuda a negociar."],
     ["<strong>Curva de tallas de tu tienda</strong>, de la primavera pasada, referencia a referencia.",
      "<strong>Pedir por talla</strong>, aunque el proveedor empuje el pack.",
      "<strong>Novedad sin histórico</strong>: poco, y con reposición pactada."]),
    ("Marzo: la primavera entra etiquetada",
     ["La primavera llega en cajas desde mediados de febrero y hasta abril. Cada caja se abre, se lee el código de lo que lo trae, se da de alta el modelo con su matriz de tallas y colores y se imprime etiqueta para lo que no trae código. Es la misma tarde de trabajo de cada campaña, y es la que hace que en abril se venda pasando el lector y se sepa qué talla queda sin ir al almacén."],
     None),
  ],
  cierre=("Con el stock por talla, la decisión es una lista",
          ["Carrito5 lleva el stock por talla y color de cada modelo, guarda las ventas por variante para hacer el pedido de primavera con la curva real de tu tienda, e imprime las etiquetas de la última rebaja con los dos precios. Es gratuito hasta 1.000 artículos, para Windows. Si el cambio de temporada lo haces mirando el estante, instálalo antes de que lleguen las cajas de marzo."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué hago con la ropa de invierno que no se ha vendido?",
     "Cada referencia va a uno de tres destinos: última rebaja hasta que salga si es moda de temporada, guardar con su código y su stock si es básico, o salida (proveedor, saldista, donación) si lleva dos temporadas sin venderse."),
    ("¿Merece la pena guardar ropa para el invierno que viene?",
     "Solo los básicos que se venden igual cada año. Y guardarlos con la referencia dada de alta en el programa, para saber en octubre qué hay y en qué tallas antes de pedir."),
    ("¿Cómo hago el pedido de primavera?",
     "Por talla, con lo que se vendió la primavera pasada de cada modelo por talla en tu tienda. Cada tienda tiene su curva y el pack del proveedor no es la tuya."),
    ("¿Cuándo llega la primavera a la tienda?",
     "Desde mediados de febrero hasta abril, en cajas. Cada caja se da de alta y se etiqueta al llegar, no cuando hace falta."),
    ("¿Qué hago con las tallas sueltas?",
     "Si son de modelos que no se reponen, salida: última rebaja fuerte, saldista o devolución a proveedor. Guardarlas no las va a vender."),
  ],
  relacionadas=[("Matriz de tallas y colores", "tallas-y-colores.html", "El stock por variante"),
                ("Rebajas de enero 2027", "blog/rebajas-enero-2027-fechas-ley-preparar.html", "La última rebaja también es rebaja"),
                ("Inventario de fin de año", "blog/inventario-fin-de-ano-tienda-sin-cerrar.html", "De dónde sale la lista"),
                ("TPV para zapaterías", "tpv-zapateria.html", "Calzado por número")]),

}
