# -*- coding: utf-8 -*-
"""Blog de carrito5.com: junio de 2027.

Rebajas de verano, el pedido de la campaña escolar (cierra el ciclo con el
primer post de septiembre), la lista final de VeriFactu para autonomos y el
balance del primer semestre. Mismas reglas de funciones confirmadas que
blog_2026_09.py.
"""

BLOG_2027_06 = {

# ------------------------------------------------------------------ 8 jun
"rebajas-verano-2027-preparar-1-julio": dict(
  title="Rebajas de Verano 2027: el 1 de Julio, Jueves y VeriFactu",
  desc="Las rebajas de verano de 2027 arrancan el jueves 1 de julio, el mismo día que VeriFactu obliga a los autónomos. Qué rebajar.",
  kw="rebajas verano 2027, cuando empiezan las rebajas de verano 2027, rebajas julio 2027, preparar rebajas verano tienda, rebajas verano ley, rebajas y verifactu",
  h1="Rebajas de verano 2027: preparar el jueves 1 de julio",
  sub="Dos cosas el mismo día: la mitad del comercio abre rebajas y todos los autónomos entran en VeriFactu. Las rebajas se preparan en la segunda quincena de junio; VeriFactu, en la primera.",
  publicado="2027-06-08",
  para="Moda, calzado, hogar, complementos",
  resumen=[
    "Las rebajas de verano de 2027 empiezan, por costumbre, el jueves 1 de julio, aunque desde 2012 cada tienda fija sus fechas y debe anunciarlas. Las reglas son las de enero: artículos que ya estaban a la venta, precio anterior en la etiqueta (el más bajo de los treinta días previos), misma calidad, y saldos identificados como saldos.",
    "Lo que cambia este año es que el 1 de julio es también la fecha de VeriFactu para los autónomos. Por eso el orden: cualquier cambio de programa, en la primera quincena de junio; las etiquetas de rebajas, la última semana. Información general; el detalle, con tu asesor.",
  ],
  cuerpo=[
    ("Las fechas de verano y lo que exige la ley",
     ["Igual que en enero, la fecha la pone cada tienda. La costumbre es el 1 de julio, y en 2027 es jueves, así que el fin de semana del 3 y 4 es el primero fuerte. La tienda anuncia sus fechas en un cartel («Rebajas del 1 de julio al 31 de agosto») y con eso cumple la obligación formal.",
      "Las exigencias sobre el género y la etiqueta son las mismas de siempre: solo se rebaja lo que ya estaba a la venta en la tienda, la etiqueta lleva el precio anterior junto al rebajado, y ese precio anterior es el más bajo aplicado en los treinta días previos. Los derechos del cliente en cambios y garantía no cambian por estar en rebajas."],
     None),
    ("Qué rebajar en verano: la primavera que no salió",
     ["La lista de rebajas de julio la da el stock de primavera y verano por referencia, talla y color. Lo que no se ha movido desde marzo, las tallas sueltas de modelos agotados en el resto, el calzado de entretiempo que en julio ya no se vende a precio. A eso, descuento fuerte desde el primer día, porque en agosto ya no lo quiere nadie y en septiembre ocupa el sitio del otoño.",
      "Lo que se vende bien en julio a precio, sandalias, moda de playa, no se rebaja el 1: se rebaja a mediados de mes si sobra, en la segunda rebaja. Y el género de otoño que ya empieza a llegar, separado y sin tocar."],
     ["<strong>Primavera sin venta desde marzo</strong>: 30 % o más desde el 1 de julio.",
      "<strong>Tallas sueltas</strong> de modelos que no se reponen: igual.",
      "<strong>Verano que aún se vende</strong>: sin rebaja hasta mediados de julio.",
      "<strong>Otoño que llega</strong>: separado y a su precio."]),
    ("La última semana de junio: etiquetas con dos precios",
     ["Del 24 al 30 de junio se cambia el precio de cada referencia rebajada en el programa, se imprime la etiqueta con el precio anterior y el rebajado, y se coloca. Doscientas referencias son una tarde con dos personas. El precio anterior sale del histórico de la referencia, que es lo que evita el error clásico de poner el de temporada cuando el artículo estuvo más barato hace tres semanas.",
      "El 30 por la tarde, cartel de fechas en el escaparate y venta de prueba: un artículo rebajado, uno a precio normal, una prenda con talla. El ticket sale con los precios correctos y con el QR."],
     None),
    ("VeriFactu y rebajas el mismo día: el orden",
     ["Si eres autónomo y tu programa no está adaptado, el cambio de programa va en la primera quincena de junio, no la última semana, y desde luego no el 1 de julio. Cambiar de programa y etiquetar rebajas la misma semana es garantía de error en las dos cosas. En la primera quincena se instala el programa nuevo y se cobra con él; en la segunda se preparan las rebajas con un programa que ya se conoce; y el 1 de julio solo hay rebajas.",
      "Si tu programa ya está adaptado, la comprobación de VeriFactu es la del artículo anterior: declaración responsable guardada y QR legible. Diez minutos."],
     None),
    ("Segunda rebaja y el final de agosto",
     ["Hacia el 15 de julio baja un escalón lo que no ha salido, y el verano que empieza a sobrar entra en rebaja. A finales de agosto, con el otoño llegando, lo que quede va a saldo o sale. La tienda que ha llevado el stock en el programa hace cada uno de esos cortes con una lista en cinco minutos; la que no, lo hace mirando el estante y guardando en cajas lo que no sabe si venderá."],
     None),
  ],
  cierre=("Etiquetas de rebajas en una tarde, con el programa ya conocido",
          ["Carrito5 guarda el precio de cada referencia, imprime la etiqueta con el precio anterior y el rebajado, lleva el stock por talla y color y ya está adaptado a VeriFactu. Es gratuito hasta 1.000 artículos, para Windows. Si eres autónomo y aún no has cambiado, instálalo esta semana: en la última de junio etiquetas rebajas con un programa que ya conoces."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cuándo empiezan las rebajas de verano de 2027?",
     "Cada tienda fija sus fechas desde 2012 y debe anunciarlas. La costumbre es el 1 de julio, que en 2027 es jueves."),
    ("¿Qué rebajo el 1 de julio?",
     "La primavera que no se ha movido desde marzo y las tallas sueltas, con descuento fuerte. El verano que aún se vende, a mediados de julio si sobra. El otoño que llega, sin tocar."),
    ("¿Qué precio anterior pongo en la etiqueta?",
     "El más bajo aplicado a ese artículo en los treinta días anteriores. Sale del histórico de la referencia en el programa."),
    ("Soy autónomo y el 1 de julio entro en VeriFactu. ¿Qué hago con las rebajas?",
     "Cambiar de programa, si hace falta, en la primera quincena de junio; preparar rebajas en la última semana con el programa ya conocido. Nunca las dos cosas la misma semana."),
    ("¿Los derechos del cliente cambian en rebajas?",
     "No. Garantía y política de cambios son los mismos que el resto del año. Puedes limitar los cambios si lo anuncias antes de vender."),
  ],
  relacionadas=[("Rebajas de enero 2027", "blog/rebajas-enero-2027-fechas-ley-preparar.html", "Las mismas reglas, en invierno"),
                ("VeriFactu para autónomos: el último mes", "blog/verifactu-autonomos-ultimo-mes-junio-2027.html", "La otra fecha del 1 de julio"),
                ("Cambio de temporada", "blog/cambio-de-temporada-primavera-stock-invierno.html", "Tres destinos para cada referencia"),
                ("Matriz de tallas y colores", "tallas-y-colores.html", "Rebajar por variante")]),

# ------------------------------------------------------------------ 15 jun
"campana-escolar-2027-papeleria-pedido-en-junio": dict(
  title="Campaña Escolar 2027: la Papelería Pide en Junio",
  desc="La vuelta al cole de septiembre se pide en junio, con lo vendido el año pasado por referencia.",
  kw="campaña escolar 2027 papeleria, pedido vuelta al cole papeleria, preparar vuelta al cole tienda, material escolar pedido junio, papeleria verano preparar septiembre",
  h1="Campaña escolar 2027: el pedido de la papelería se hace en junio",
  sub="Hace nueve meses el blog empezó con la vuelta al cole ya en marcha y lo que quedaba por hacer. Este año se llega a septiembre con el pedido hecho en junio y el sobrante de octubre contado.",
  publicado="2027-06-15",
  para="Papelerías y librerías",
  resumen=[
    "La campaña escolar de 2027 arranca en la última semana de agosto, y los mayoristas de papelería sirven los pedidos grandes con seis a ocho semanas, así que el pedido que decide septiembre se cierra en junio. Se hace con tres datos: lo que se vendió del 25 de agosto al 30 de septiembre de 2026 por referencia, lo que quedó guardado en octubre con su código, y las listas de material de los colegios de la zona para el curso 2027-2028.",
    "Quien llevó la campaña pasada en el programa tiene los dos primeros datos en un minuto. El tercero se pide a los colegios en junio, que es cuando las tienen.",
  ],
  cuerpo=[
    ("Por qué junio",
     ["El mayorista de papelería recibe en junio los pedidos de campaña de todas las papelerías de España y sirve por orden. Quien pide en junio recibe en julio lo que ha pedido; quien pide en agosto recibe lo que queda, tarde. Y las marcas que exigen los colegios, el cuaderno concreto, el rotulador concreto, son las primeras en agotarse en el mayorista, no en la tienda.",
      "Por eso el pedido de campaña es un trabajo de junio, y las dos semanas antes de cerrar la tienda en julio o agosto, si se cierra, son para recibirlo y darlo de alta."],
     None),
    ("Los tres datos del pedido",
     ['<div class="c5-tabla-wrap"><table class="c5-tabla"><thead><tr><th>Dato</th><th>De dónde sale</th><th>Qué decide</th></tr></thead><tbody>'
      '<tr><td>Lo vendido en la campaña pasada, por referencia</td><td>Del programa, si cada venta pasó por él</td><td>Cuánto pedir de cada cosa, y qué se agotó dos veces</td></tr>'
      '<tr><td>Lo que sobró y se guardó en octubre, con su código</td><td>Del stock del programa</td><td>Qué no hay que pedir porque ya está</td></tr>'
      '<tr><td>Las listas de los colegios para 2027-2028</td><td>De los colegios, en junio; de los padres, en julio</td><td>Qué marcas y qué referencias nuevas entran este año</td></tr>'
      '</tbody></table></div>',
      "Con los tres, el pedido es una resta: lo que se vendió más lo nuevo de las listas, menos lo que ya hay. Sin ellos es una apuesta, y en papelería la apuesta se paga en octubre con cajas de cuadernos de una marca que ningún colegio pidió."],
     None),
    ("Las listas de los colegios",
     ["Es el dato que más se olvida y el más barato: los colegios de la zona cierran las listas de material en junio, y muchos las cuelgan en su web o las dan a las familias con las notas. Con las listas de los cuatro o cinco colegios más cercanos delante, la papelería sabe qué marcas y qué formatos van a pedir cientos de familias en la misma semana, y pide eso en profundidad.",
      "Un paso más: preparar el «lote de cada colegio y curso» como conjunto, con su precio, para que en septiembre la familia se lo lleve entero. Cada artículo del lote se da de alta con su código, y el lote se cobra pasando cada uno o con un código propio para el conjunto, según lo que haga la tienda."],
     None),
    ("Julio: entrar el pedido etiquetado antes de cerrar",
     ["El pedido llega en julio. Se abre por proveedor, se lee el código de lo que lo trae, se imprime etiqueta para lo que no (el material a granel, los packs que se venden sueltos), y se coloca o se guarda ya etiquetado. Si la papelería cierra en agosto, cierra con la campaña dentro y etiquetada, y el 24 de agosto solo hay que subir la persiana.",
      "Es exactamente lo que el primer artículo de este blog, en septiembre de 2026, decía que había que haber hecho. Este año se hace."],
     ["<strong>Alta por lector</strong> de todo lo que trae código EAN.",
      "<strong>Etiqueta propia</strong> para lo que se vende suelto.",
      "<strong>Lotes por colegio y curso</strong>, con su precio, listos para septiembre.",
      "<strong>Ficha de cliente</strong> de las familias del año pasado, para avisar la última semana de agosto."]),
    ("Lo que cierra el ciclo",
     ["Entre septiembre de 2026 y junio de 2027 este blog ha ido campaña a campaña: la escolar, Halloween, Black Friday, Navidad, Reyes, rebajas, San Valentín, Carnaval, el Día del Padre, Semana Santa, Sant Jordi, la Madre, las comuniones, el verano. Todas con la misma mecánica: pedido con datos, género etiquetado al entrar, cliente en su ficha, balance por referencia al terminar. La papelería que empezó en septiembre cobrando con calculadora llega a este junio con un año de ventas en el programa, y el pedido sale solo."],
     None),
  ],
  cierre=("Si la campaña pasada no quedó apuntada, que esta sí",
          ["Carrito5 registra cada venta por referencia, guarda el stock con su código para el sobrante de octubre, lee códigos e imprime etiquetas para el género a granel, y lleva la ficha de las familias que repiten. Es gratuito hasta 1.000 artículos, para Windows. Instalado en junio, el pedido de 2028 sale del programa; el de este año sale de las listas de los colegios y de lo que recuerdes."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Cuándo hay que hacer el pedido de la vuelta al cole?",
     "En junio. Los mayoristas sirven por orden con seis a ocho semanas, y las marcas que exigen los colegios se agotan primero en el mayorista."),
    ("¿Con qué datos hago el pedido?",
     "Lo vendido en la campaña pasada por referencia, lo que sobró y se guardó con su código, y las listas de material de los colegios de la zona para el curso que viene."),
    ("¿Dónde consigo las listas de los colegios?",
     "En los propios colegios en junio, en su web si la tienen, o de las familias con las notas de fin de curso. Con cuatro o cinco colegios cercanos basta."),
    ("¿Cómo preparo los lotes por colegio y curso?",
     "Cada artículo del lote dado de alta con su código, y el lote con su precio cerrado, cobrado artículo a artículo o con un código propio del conjunto, según lo que haga la tienda."),
    ("¿Cuándo doy de alta el pedido?",
     "En julio, según llega, con el lector para lo que trae código y etiqueta propia para lo suelto. Si cierras en agosto, cierras con la campaña dentro y etiquetada."),
  ],
  relacionadas=[("Vuelta al cole: las tres semanas que quedan", "blog/vuelta-al-cole-papeleria-ultimas-semanas.html", "Donde empezó el blog"),
                ("TPV para papelerías", "tpv-papeleria.html", "El sector"),
                ("Etiquetar antes de la campaña", "blog/etiquetar-genero-antes-de-campana.html", "La tarde de julio"),
                ("Calendario comercial 2026-2027", "blog/calendario-comercial-2026-2027-fechas-clave.html", "El año entero")]),

# ------------------------------------------------------------------ 22 jun
"verifactu-1-julio-2027-lista-final-autonomos": dict(
  title="VeriFactu, 1 de Julio de 2027: la Lista Final para Autónomos",
  desc="Nueve días. Lo que tiene que estar hecho el 30 de junio, lo que se revisa el 1 de julio antes del primer cliente y qué hacer la semana del 5 si algo falla.",
  kw="verifactu 1 julio 2027 autonomos, verifactu lista comprobacion, verifactu que hacer el 1 de julio, verifactu autonomos checklist, verifactu ya en vigor autonomos",
  h1="Nueve días: la lista final de VeriFactu para autónomos",
  sub="El jueves 1 de julio no hay que hacer nada especial si lo de esta lista está hecho el 30. Si no lo está, la lista dice qué hacer el 2.",
  publicado="2027-06-22",
  para="Autónomos con tienda",
  resumen=[
    "El 1 de julio de 2027 los autónomos entran en VeriFactu. La lista final tiene tres partes: lo que tiene que estar hecho el 30 de junio (programa adaptado instalado y en uso, declaración responsable guardada, datos fiscales correctos), lo que se revisa el 1 de julio antes de abrir (un ticket de prueba con QR legible), y lo que se hace la primera semana (ningún ticket fuera del programa, ningún error borrado en vez de anulado).",
    "No hay que pagar nada, ni darse de alta en nada, ni hacer nada en la web de Hacienda ese día. Información general, no asesoramiento fiscal.",
  ],
  cuerpo=[
    ("El 30 de junio por la noche: hecho o no hecho",
     ['<div class="c5-tabla-wrap"><table class="c5-tabla"><thead><tr><th>Punto</th><th>Cómo se comprueba</th><th>Si falla</th></tr></thead><tbody>'
      '<tr><td>Programa adaptado, instalado y en uso</td><td>Llevas días cobrando con él y los tickets salen con QR</td><td>Instálalo el 1 por la mañana antes de abrir; con Carrito5 son minutos, y las treinta referencias que más vendes, una hora</td></tr>'
      '<tr><td>Declaración responsable guardada</td><td>La tienes en una carpeta y en el correo, de la versión instalada</td><td>Pídela hoy al fabricante; si no la tiene, el programa no está adaptado</td></tr>'
      '<tr><td>Datos fiscales correctos</td><td>Nombre, NIF y dirección del ticket coinciden con el censo</td><td>Se corrigen en la configuración del programa en dos minutos</td></tr>'
      '<tr><td>Impresora que imprime el QR legible</td><td>El QR de un ticket se lee con el móvil</td><td>Cabezal limpio, densidad más alta, papel decente</td></tr>'
      '<tr><td>Rebajas etiquetadas aparte</td><td>Las etiquetas con dos precios ya están puestas</td><td>No mezclar: primero el programa, después las etiquetas</td></tr>'
      '</tbody></table></div>'],
     None),
    ("El 1 de julio antes del primer cliente",
     ["Un ticket de prueba. Se cobra un artículo cualquiera, se imprime, se escanea el QR con el móvil y se comprueba que abre la página de la Agencia Tributaria con los datos del ticket. Se anula esa venta de prueba en el programa, como anulación registrada, que además sirve para comprobar que quien cobra sabe anular. Y se abre.",
      "Nada más. No hay que entrar en ninguna web, ni enviar nada, ni comunicar nada. Si el programa está adaptado, lo hace solo."],
     None),
    ("La primera semana: dos hábitos",
     ["Toda venta pasa por el programa, aunque sea un artículo de dos euros con cola en la puerta y la persona de refuerzo recién llegada. Es el hábito que más cuesta en tiendas que cobraban «de cabeza» las ventas pequeñas, y es el que más importa desde el 1 de julio.",
      "Y ningún ticket se tira: si se cobró mal, se anula en el programa y se vuelve a hacer. Quien cobra tiene que saber dónde está la anulación antes de que haga falta, no con el cliente delante."],
     ["<strong>Toda venta por el programa</strong>, sin excepción de importe.",
      "<strong>Errores anulados</strong>, no borrados ni tirados.",
      "<strong>Al final de la semana</strong>, comparar lo vendido según el programa con caja y datáfono."]),
    ("Si algo falla la semana del 5",
     ["Si el QR no se lee en algunos tickets, es la impresora, y se arregla en el momento. Si el programa se cuelga o no imprime, se llama al soporte del fabricante ese día, no la semana siguiente. Si el programa resulta no estar adaptado pese a lo que dijeron, se cambia ese día: la situación se corrige el día que se instala uno adaptado, y cada día que pasa es un día más facturando sin cumplir. Consúltalo con tu asesor, y no lo dejes para después del verano."],
     None),
    ("Lo que cierra el año",
     ["Con esto termina la serie de VeriFactu de este blog: cien días para las sociedades en septiembre, lo que cambia el 1 de enero, la primera semana en vigor, cien días para autónomos en marzo, el último mes en mayo, y esta lista. Desde el 1 de julio de 2027 todo el comercio español factura con VeriFactu y la obligación deja de ser noticia. Lo que queda es el hábito: toda venta por el programa, todo error anulado, todo ticket con su QR."],
     None),
  ],
  cierre=("Si el 30 por la noche falta el primer punto",
          ["Carrito5 se instala en minutos, está adaptado a VeriFactu, saca el ticket con su QR desde la primera venta y es gratuito hasta 1.000 artículos. El 1 de julio por la mañana, antes de abrir, da tiempo a instalarlo y dar de alta lo que más vendes. Mejor hoy, con nueve días."],
          "Descargar Carrito5 y sacar un ticket de prueba", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Tengo que hacer algo en la web de Hacienda el 1 de julio?",
     "No. Si el programa está adaptado, genera y remite los registros solo. No hay alta, ni tasa, ni comunicación que hacer ese día."),
    ("¿Qué compruebo el 1 de julio antes de abrir?",
     "Un ticket de prueba: se imprime, se escanea el QR con el móvil y se comprueba que abre la página de la Agencia Tributaria. Después se anula esa venta en el programa."),
    ("¿Qué pasa si cobro una venta sin pasarla por el programa?",
     "Es una venta sin registro de facturación, que desde el 1 de julio es un incumplimiento. El hábito es toda venta por el programa, sea del importe que sea."),
    ("¿Y si me equivoco al cobrar?",
     "Se anula la venta en el programa, como anulación registrada, y se vuelve a hacer. No se borra ni se tira el ticket."),
    ("Mi programa falla el día 2. ¿Qué hago?",
     "Llama al soporte ese día. Si el programa no está adaptado pese a lo prometido, cámbialo ese mismo día: la situación se corrige cuando instalas uno adaptado. Consúltalo con tu asesor."),
  ],
  relacionadas=[("El último mes: VeriFactu para autónomos", "blog/verifactu-autonomos-ultimo-mes-junio-2027.html", "Lo que se dijo en mayo"),
                ("Primera semana con VeriFactu: cinco comprobaciones", "blog/verifactu-en-vigor-primera-semana-comprobaciones.html", "Lo que revisaron las sociedades"),
                ("VeriFactu para autónomos", "verifactu-autonomos.html", "La página de referencia"),
                ("Rebajas de verano 2027", "blog/rebajas-verano-2027-preparar-1-julio.html", "El mismo día")]),

# ------------------------------------------------------------------ 29 jun
"balance-primer-semestre-2027-tienda-que-mirar": dict(
  title="Balance del Primer Semestre 2027: Cinco Cifras de Tienda",
  desc="Cinco cifras de enero a junio que dicen cómo va la tienda: ventas por campaña, stock parado, clientes con ficha, vales vivos y costes fijos frente a enero.",
  kw="balance tienda primer semestre, cifras tienda revisar, analizar ventas tienda, stock parado tienda, balance comercio junio, que mirar en mi tienda",
  h1="Primer semestre de 2027: cinco cifras antes del verano",
  sub="No hace falta un informe de cuarenta páginas. Cinco números sacados del programa de caja dicen si el año va bien, y qué cambiar en septiembre.",
  publicado="2027-06-29",
  para="Todo el comercio de calle",
  resumen=[
    "A 30 de junio, cinco cifras bastan para saber cómo va una tienda pequeña: lo vendido por campaña (rebajas, San Valentín, Padre, Semana Santa, Madre, comuniones) comparado con 2026; el dinero parado en referencias sin venta desde enero; cuántos clientes tienen ficha con historial y cuántos han repetido; cuántos vales de devolución siguen vivos y por cuánto; y lo que la tienda paga cada mes en costes fijos frente a enero.",
    "Las cuatro primeras salen del programa de caja si cada venta pasó por él. La quinta, del extracto del banco. Con las cinco delante, el plan de septiembre se escribe en una tarde.",
  ],
  cuerpo=[
    ("Uno: lo vendido por campaña, contra el año pasado",
     ["Cada campaña del semestre tiene sus fechas y su artículo en este blog: rebajas del 7 de enero, San Valentín el 12 y 13 de febrero, el Día del Padre el 18 y 19 de marzo, Semana Santa del 21 al 28, el Día de la Madre el 29 y 30 de abril, las comuniones de mayo. Lo vendido en cada tramo, por referencia, contra el mismo tramo de 2026 si existe, dice qué campañas crecen y cuáles no, y en cuáles el pedido se quedó corto o sobró.",
      "Si 2026 no está en el programa, esta es la primera cifra que existe, y en 2028 será la comparación."],
     None),
    ("Dos: el dinero parado",
     ["La lista de referencias con stock y sin ninguna venta desde el 1 de enero, valorada a precio de compra. Es el dinero que la tienda tiene en el almacén y no va a recuperar sin rebajarlo, y es la cifra más incómoda y más útil del semestre. Lo que salga aquí va a las rebajas del 1 de julio con descuento fuerte, o sale de la tienda en agosto. Guardarlo para «ver si en otoño» es lo que ha hecho que esté ahí desde enero."],
     ["<strong>Sin venta desde enero</strong>: a rebajas fuertes el 1 de julio.",
      "<strong>Sin venta desde 2026</strong>: salida en agosto, al precio que sea.",
      "<strong>Tallas sueltas</strong> de modelos agotados: igual."]),
    ("Tres: los clientes con ficha, y los que han repetido",
     ["Cuántos clientes tienen ficha con al menos una compra registrada, y cuántos de ellos han comprado dos veces o más en el semestre. Es la cifra que mide si la tienda está construyendo algo que no depende de la calle: una lista propia de gente que vuelve. Si en enero había cincuenta fichas y en junio hay trescientas, las campañas de otoño empiezan con trescientos avisos por WhatsApp que en 2026 no existían.",
      "Y los que han repetido son la base: son a quienes se avisa primero de la vuelta al cole, de Halloween, de las reservas de diciembre."],
     None),
    ("Cuatro: los vales vivos",
     ["Cuántos vales de devolución hay emitidos y no usados, y por cuánto. Es dinero que la tienda debe a sus clientes y que tiene que estar en la cuenta. Si los vales están registrados en la ficha de cada cliente desde la campaña de Navidad, la cifra sale del programa. Si están en papeles con sello, no la sabe nadie, y en el balance de fin de año aparecerá como sorpresa."],
     None),
    ("Cinco: los costes fijos, contra enero",
     ["Del extracto del banco: lo que la tienda paga cada mes en cuotas, suscripciones, comisiones y mantenimientos, comparado con lo que pagaba en diciembre antes de la revisión de la cuesta de enero. Si la revisión se hizo, aquí se ve el ahorro. Si no se hizo, junio es tan buen mes como enero para hacerla, y el programa de caja sigue siendo el primer recibo que mirar."],
     None),
    ("Lo que se escribe para septiembre",
     ["Con las cinco cifras delante, el plan de septiembre cabe en una hoja: qué campañas de otoño reforzar y cuáles no, qué género no volver a pedir, a qué clientes avisar primero, cuántos vales tener en cuenta, y qué recibos siguen sobrando. Y una sexta línea que este blog ha repetido en cada artículo desde septiembre de 2026: el pedido de cada campaña sale de lo que vendió la anterior, y eso solo existe si cada venta pasó por el programa. A 30 de junio de 2027, con VeriFactu ya obligatorio para todos, esa condición se cumple sola."],
     None),
  ],
  cierre=("Las cinco cifras salen de un programa gratuito",
          ["Carrito5 registra cada venta por referencia, talla y color, guarda los clientes con su historial y los vales en su ficha, y lleva el stock para saber qué no se ha vendido desde enero. Es gratuito hasta 1.000 artículos, para Windows. Si este semestre las cifras no existen, que sea el último: instalado en julio, el balance de diciembre tiene las cinco."],
          "Descargar Carrito5 gratis", "/descargar-tpv-gratis.html"),
  faqs=[
    ("¿Qué cifras debo mirar a mitad de año en una tienda pequeña?",
     "Cinco: ventas por campaña contra el año pasado, dinero parado en stock sin venta desde enero, clientes con ficha y cuántos han repetido, vales de devolución vivos, y costes fijos mensuales contra enero."),
    ("¿De dónde salen esas cifras?",
     "Las cuatro primeras, del programa de caja, si cada venta pasó por él. La quinta, del extracto del banco."),
    ("¿Qué hago con el stock sin venta desde enero?",
     "A las rebajas del 1 de julio con descuento fuerte. Lo que lleva desde 2026, salida en agosto. Guardarlo es lo que lo ha tenido parado."),
    ("¿Cómo sé cuántos vales tengo pendientes?",
     "Si están registrados en la ficha de cada cliente y se marcan como usados al gastarse, el programa lo dice. Si están en papel, no lo sabe nadie."),
    ("¿Para qué sirve saber cuántos clientes han repetido?",
     "Para las campañas de otoño: son a quienes se avisa primero de la vuelta al cole, de Halloween y de las reservas de diciembre. Es la lista propia de la tienda."),
  ],
  relacionadas=[("Cuesta de enero: costes fijos", "blog/cuesta-de-enero-comercio-costes-fijos-revisar.html", "La quinta cifra"),
                ("El vale de devolución", "blog/vale-de-devolucion-tienda-como-funciona.html", "La cuarta cifra"),
                ("Inventario de fin de año", "blog/inventario-fin-de-ano-tienda-sin-cerrar.html", "La segunda cifra, en diciembre"),
                ("Calendario comercial 2026-2027", "blog/calendario-comercial-2026-2027-fechas-clave.html", "Todas las campañas del semestre")]),

}
